### ISSUE TITLE
Link to Github from dramatiq.io

### ISSUE THREAD

**Issue by pirate** [Bogdanp/dramatiq#101]
It's really hard to find a link to the github source from dramatiq.io, but it's often the first thing people look for when landing there.

Can you add a link like "view the source on github" or "view github" to the homepage?

**Comment by Bogdanp** [comment]
There was already a "Fork me on Github" banner, but I can see how people could easily miss that. I added a link to the sidebar. It should be up in about a minute. Thanks!
