### ISSUE TITLE
Class based actors cannot have constructor arguments

### ISSUE THREAD

**Issue by d53dave** [Bogdanp/dramatiq#107]
## What OS are you using?
macOS 10.13.3

## What version of Dramatiq are you using?
1.3.0

## What did you do?
I tried defining an actor inheriting from `GenericActor` that had constructor arguments, e.g. `def __init__(name):`

## What did you expect would happen?
Dramatiq would start up fine.

## What happened?
TypeError was thrown:

```
  File "/usr/local/miniconda3/envs/csaopt-worker/lib/python3.6/site-packages/dramatiq/generic.py", line 32, in __new__
    clazz_instance = clazz()
TypeError: __init__() missing 1 required positional argument: 'name'
```

**Comment by Bogdanp** [comment]
I'm afraid this is by design. Generic actors are immediately instantiated so that they may be registered with their workers. 

What are you trying to achieve?

**Comment by Bogdanp** [comment]
That is possible, but not super pretty. For example:

`broker.py`:
```python
import dramatiq
from dramatiq.brokers.rabbimtq import RabbitmqBroker

broker = RabbitmqBroker(...)
dramatiq.set_broker(broker)
```

`actors.py`:
```python
import dramatiq

@dramatiq.actor
def do_stuff(x, y):
  return x + y
```

`service.py`:
```python
from dramatiq import Message

from .broker import broker

# ...
# inside a request handler
broker.enqueue(Message(
  queue_name="default",
  actor_name="do_stuff",
  args=(1, 2), kwargs={},
  options={},
))
```

So your service never actually has to import the actor code and neither does your actor code have to import service code. You can just tell dramatiq to load the broker and the actors modules on boot:

```sh
$ dramatiq broker:broker actors some_other_actors_module
```

**Comment by d53dave** [comment]
Thanks, I'm closing this issue since I can work around that by setting attributes on the instantiated objects.

I'll open a thread on your discussion board regarding another question I had about separating workers.
