### ISSUE TITLE
Integration with new sentry client

### ISSUE THREAD

**Issue by mecurc** [Bogdanp/dramatiq#114]
Hello, @Bogdanp, Thanks for dramatiq!

As described at [Raven README.md](https://github.com/getsentry/raven-python/blob/master/README.rst) Raven SDK is being phased out for [Sentry-Python](https://github.com/getsentry/sentry-python).

It will be cool to update docs(raven example) and [add official integration](https://github.com/getsentry/sentry-python/issues/46) to SDK.

https://getsentry.github.io/sentry-python\

[discuss topic](https://discuss.dramatiq.io/t/integration-with-new-sentry-sdk/88)

**Comment by Bogdanp** [comment]
Thanks! I may take a stab at adding an integration to the new sentry package this weekend.

**Comment by Bogdanp** [comment]
I opened a PR: https://github.com/getsentry/sentry-python/pull/109

**Comment by dmitry-vakhnenko** [comment]
wow! Cool!10:53, 6 октября 2018 г., Bogdan Popa <notifications@github.com>:I opened a PR: getsentry/sentry-python#109

**Comment by dmitry-vakhnenko** [comment]
Maybe just add to `dramatiq` package or something like `dramatiq.contrib` package?

If we put this middleware inside dramatiq package it can be a good feature for promoting.

**Comment by jmagnusson** [comment]
I took some time to implement an integration towards the new SDK.
Github: https://github.com/jmagnusson/sentry-dramatiq
PyPI: https://pypi.org/project/sentry-dramatiq/

It doesn't really have any battle experience yet, but from the limited testing I've done so far it seems to work fine. It takes the monkey patching approach, similar to how many of the other sentry-sdk integrations are doing it.

Let me know your thoughts, I'd be thankful for any feedback. And if you want I'd gladly submit it as a PR here. 

One improvement I'm imagining is integrating it with the CLI as we could start it before any application code has been imported to catch as many errors as possible. Plus we could avoid doing `sentry_sdk.init(middleware=[DramatiqMiddleware()])` where we initialize the broker and define the actors. (That might be accessed by a web app or such, where there's no need for the Dramatiq integration).

@Bogdanp I noticed that `middleware` is accepted as a regular arg in `Broker` and `StubBroker`, but not in `RabbitmqBroker` or `RedisBroker`. This makes for some [pretty awkward code](https://github.com/jmagnusson/sentry-dramatiq/blob/master/sentry_dramatiq/__init__.py#L41) in the already awkward monkey patching that I've implemented.

Speaking of - Perhaps we could change dramatiq's code to not initialize the middleware until they're first being accessed? Then `sentry_sdk.init()` could be called after the broker initialization, [something which is currently not possible](https://github.com/jmagnusson/sentry-dramatiq#known-limitations).

**Comment by jmagnusson** [comment]
Note to self: flush sentry-sdk hub on worker exit ([like in Celery](https://github.com/getsentry/sentry-python/blob/master/sentry_sdk/integrations/celery.py#L123))

**Comment by jmagnusson** [comment]
Quick update here - been running the integration for a week in production now. Everything seems to work well so far, `sentry-sdk` seems to be far better at catching errors compared to `raven`.

**Comment by Bogdanp** [comment]
> Let me know your thoughts, I'd be thankful for any feedback. And if you want I'd gladly submit it as a PR here.

I think this is great, although I haven't had a chance to play around with your package yet. Thank you for building it!  I'd be happy to reference it in the documentation.  If you want, send in a PR and I'll merge it.  Otherwise, I'll mention it myself when I find some time.

> @Bogdanp I noticed that middleware is accepted as a regular arg in Broker and StubBroker, but not in RabbitmqBroker or RedisBroker. This makes for some pretty awkward code in the already awkward monkey patching that I've implemented. I think the current code should work fine, but I thought I'd just let you know about it.

Yes, that's unfortunate, but it's not something I'm going to change for now b/c I don't want to break backwards-compatibility.

> One improvement I'm imagining is integrating it with the dramatiq CLI as we could start sentry's error reporting before any application code has been imported, to catch as many errors as possible. Plus we could avoid doing sentry_sdk.init(middleware=[DramatiqMiddleware()]) where we initialize the broker and define the actors. (That might be accessed by a web app or such, where there's no need for the Dramatiq integration).

This will be possible via https://github.com/Bogdanp/dramatiq/issues/127 once I get around to implementing it.

**Comment by Bogdanp** [comment]
I've updated the docs to recommend `sentry-dramatiq` so I'm closing this.

**Comment by jmagnusson** [comment]
Great! I'll try to find some time to submit a PR later on.

Feel free to let me know of any feedback you might have if you try it out.
