### ISSUE TITLE
Question about comparison with other task queue libraries

### ISSUE THREAD

**Issue by coleifer** [Bogdanp/dramatiq#122]
Kool project, I'm the author of [huey](https://github.com/coleifer/huey), a different task queue project for python...also born out of a strong dislike for celery. I had just a couple questions from reading the 'comparison' doc.

> Celery has poor support for delayed tasks. Delayed tasks are put on the same queue that is used for normal tasks and they’re simply pulled into worker memory until they can be executed, making it hard to autoscale workers by queue size.

I was looking at the code for `dramatiq` and it appears that it may do the same thing, using a `PriorityQueue` on the consumer thread. If the message isn't ready, then it seems like it is continually being pushed and popped until it becomes ready to run -- is that correct? It might be worth noting that this is the approach being used (if I'm understanding correctly).

I was looking around and it seemed like `dramatiq` only supports a multi-thread worker model. If that's the case, it might be worthwhile calling attention to the fact that `dramatiq` can only run on a single core (due to using worker threads and the GIL and all that).

For what it's worth, [huey](https://github.com/coleifer/huey) implements most of the features you're comparing on. It also does a few other cool things like crontab-like scheduling, task pipelining, very simple implementation, and it also supports process/thread/greenlet worker models. Hope you find it interesting if you decide to check it out.

**Comment by Bogdanp** [comment]
Thanks! I am aware of huey.

> I was looking at the code for dramatiq and it appears that it may do the same thing, using a PriorityQueue on the consumer thread. If the message isn't ready, then it seems like it is continually being pushed and popped until it becomes ready to run -- is that correct? It might be worth noting that this is the approach being used (if I'm understanding correctly).

Queues and queue consumers for standard and delay queues are separate (both in memory and inside the broker) so delayed messages can't impact standard messages like they can in Celery (this is easy to test: enqueue 100k delayed messages and one standard message under both systems; Celery will be forced to process some of the delayed messages before it processes the standard one).

Here are two minimal programs that showcase the problem I'm talking about:

`test_dramatiq.py`:
```python
import dramatiq


@dramatiq.actor
def p(s):
    print(s)


if __name__ == "__main__":
    for _ in range(100_000):
        p.send_with_options(args=("delayed",), delay=300_000)
    p.send("standard")
    print("!!! messages enqueued !!!")
```

`$ python test_dramatiq.py &; dramatiq test_dramatiq`

`test_celery.py`:
```python
import celery

c = celery.Celery()


@c.task(name="p")
def p(s):
    print(s)


if __name__ == "__main__":
    for _ in range(100_000):
        p.apply_async(args=("delayed",), countdown=300)
    p.delay("standard")
    print("!!! messages enqueued !!!")
```

`$ python test_celery.py &; celery worker -A test_celery:c`

> I was looking around and it seemed like dramatiq only supports a multi-thread worker model. If that's the case, it might be worthwhile calling attention to the fact that dramatiq can only run on a single core (due to using worker threads and the GIL and all that).

Dramatiq is both multi-threaded and multi-process so it *can* take advantage of multiple cores.

> For what it's worth, huey implements most of the features you're comparing on. It also does a few other cool things like crontab-like scheduling, task pipelining, very simple implementation, and it also supports process/thread/greenlet worker models. Hope you find it interesting if you decide to check it out.

I'd be happy to merge any PR you send my way if you want to add huey to the comparison table!

**Comment by bersace** [comment]
Hi, I have some feedback on both projects.

I wrote both https://gitlab.com/dalibo/dramatiq-pg and https://gitlab.com/dalibo/huey-pg . This helped me dive into internal API and basic usage.

From feature view, huey win by `huey.periodic_task`. Also, dramatiq depending on prometheus-client looks odd. Why is this mandatory ? However, dramatiq code base is somewhat lighter.

However, writing a Postgres broker for dramatiq was more easier. By default, huey uses threads for workers, but storage object is shared amongs worker threads. This mean storage class has to maintain thread safety.

Overall, dramatiq API lookes cleaner: broker class is named broker. broker have access to full message object rather than a binary payload. The consume/ack/nack API is meaningful for every broker. Also, i prefer explicit `actor.send()`.

That would be nice if dramatiq had `actor.schedule('* * * * */5')(arg=1)`  or the usual declarative `@dramatiq.periodic_actor`.

**Comment by coleifer** [comment]
@bersace -- Huey provides some hooks, notably [on_startup()](https://huey.readthedocs.io/en/latest/api.html#Huey.register_startup), which can be used to create connections to the database, etc. Huey can run workers as greenlets, threads or processes, all of which may have different implications for the library implementing the storage layer. e.g., if you have a connection pool with a socket open to Redis and then you fork a new process, what should happen? This is handled by the `redis-py` library. Similarly, `peewee`, which provides the SQLite storage layer, also handles managing the connections in a thread-safe way.

**Comment by bersace** [comment]
@coleifer yes, it's up to storage to manage thread safety.
