### ISSUE TITLE
Get rid of Prometheus' file locking mechanism

### ISSUE THREAD

**Issue by Bogdanp** [Bogdanp/dramatiq#127]
Instead of automatically spinning up a Prometheus exposition server inside of a random worker process, the CLI utility should give users the ability to fork and execute a separate Python module. That would remove the need for locking in the Prometheus middleware and open things up for more interesting use cases with shared memory between the workers (think a "stats" module).

Concretely, that would look something like this:

`expose_metrics.py`
```python
from http.server import BaseHTTPRequestHandler, HTTPServer

import prometheus_client as prom
import prometheus_client.multiprocess as prom_mp


class MetricsHandler(BaseHTTPRequestHandler):
    def do_GET(self):
        registry = prom.CollectorRegistry()
        prom_mp.MultiProcessCollector(registry)
        output = prom.generate_latest(registry)
        self.send_response(200)
        self.send_header("content-type", prom.CONTENT_TYPE_LATEST)
        self.end_headers()
        self.wfile.write(output)


def server_forever():
    try:
        httpd = HTTPServer("0.0.0.0", MetricsHandler)
        httpd.serve_forever()
    except KeyboardInterrupt: 
        httpd.shutdown()

    return 0
```

This would then be run from the command line with:

    $ dramatiq app:broker -e expose_prometheus:serve_forever

To make things easier on users, the prometheus module will likely export this functionality so users would actually run:

    $ dramatiq app:broker -e dramatiq.middleware.prometheus:serve_forever

**Comment by flowersw** [comment]
Along with this, would it make sense to update the version of prometheus_client (up to the latest) required for those who want to include it?

**Comment by Bogdanp** [comment]
@flowersw yup, it would.

**Comment by Bogdanp** [comment]
This is implemented in `master`.

**Comment by kuba-lilz** [comment]
@Bogdanp 
Is this really in master? `dramatiq --help` doesn't seem to contain anything about `-e` flag, and looking at `dramatiq/cli.py` I don't see that argument supported there.

**Comment by Bogdanp** [comment]
@kuba-lilz It ended up being called `-f` or `--fork-function` instead of `-e`.

**Comment by kuba-lilz** [comment]
Ah, didn't spot that, thank you for clarifications!
