### ISSUE TITLE
Redis 5 comes with new awesome type - STREAMS

### ISSUE THREAD

**Issue by dmitry-vakhnenko** [Bogdanp/dramatiq#131]
Recently released REDIS (version 5) comes with new type -- streams
https://redis.io/topics/streams-intro

Can it improve something in dramatiq?

**Comment by MoorsTech** [comment]
Not sure about streams but I'm running an instance of dramatiq with a modified delay queue implementation that uses sorted sets and ZPOPMIN to retrieve messages that are due for delivery.
I personally didn't like the way delay queues were implemented (no offense @Bogdanp ) as it has some stability and performance issues for me.
I'd be happy to submit a PR with my solution for delay queues now that Redis 5 is in stable release but I doubt @Bogdanp would approve of making redis 5 a requirement.

**Comment by dmitry-vakhnenko** [comment]
Can you share it in PR? It can be accepted because main message queue for dramatiq is RabbitMQ. But Redis 5+ will be popular ;D soon.

Also, your implementation can be added to next milestone (i am rly want 2.0!)

**Comment by Bogdanp** [comment]
> as it had some stability and performance issues for me.

I'd be curious to hear more about those issues.

I don't know that I'd want to make Redis 5 a requirement though, you're right.

**Comment by Bogdanp** [comment]
Closing for now as I don't want to make Redis 5 a hard dep.
