### ISSUE TITLE
Bad shebang in dramatiq-gevent

### ISSUE THREAD

**Issue by defrank** [Bogdanp/dramatiq#145]
# Issues

GitHub issues are for bugs.  If you have questions, please ask them on the [discussion board](https://discuss.dramatiq.io).

## Checklist

* [x] Does your title concisely summarize the problem?
* [x] Did you include a minimal, reproducible example?
* [x] What OS are you using?
* [x] What version of Dramatiq are you using?
* [x] What did you do?
* [x] What did you expect would happen?
* [x] What happened?

## What OS are you using?

* Alpine Linux 3.7
* Ubuntu 18.04

## What version of Dramatiq are you using?

1.4.0

## What did you do?

```
pip install dramatiq[redis]==1.4.0 gevent
dramatiq-gevent
```

## What did you expect would happen?

Dramatiq workers help output.

## What happened?

```
ash: dramatiq-gevent: not found
```

/usr/local/bin/dramatiq-gevent:
```
#!/Users/bogdan/.virtualenvs/dramatiq/bin/python
try:
    from gevent import monkey; monkey.patch_all()  # noqa
except ImportError:
    import sys
    sys.stderr.write("error: gevent is missing. Run `pip install gevent`.")
    sys.exit(1)

import sys

from dramatiq.cli import main

if __name__ == "__main__":
    sys.exit(main())
```

**Comment by Bogdanp** [comment]
Thanks! The wheel was mangled due to https://github.com/pypa/setuptools/issues/994 so I removed it from PyPI. If you clear your caches and reinstall, it should work fine.
