### ISSUE TITLE
start a worker programmatically instead of from command line

### ISSUE THREAD

**Issue by guzuomuse** [Bogdanp/dramatiq#164]
thanks for this great library.
i want to use pyinstaller to package a standalone executable service on windows.
so i want o run a worker programmatically instead of using dramatiq command-line 
if i'm right the code should some like these:

```
if __name__== __main__:
      worker=dramatiq.Worker(my_broker)
      worker.start()
```

but the child thread exit instantly as the main process finished. from source code i saw the consumer inherit Thread with the daemon parameter set True

so the question is  :  whether we should expose this daemon parameter so that we can set True or False instead of hard coding?

if i'm wrong, anybody be kind to show me how to achieve this as celery does ? thanks.

**Comment by Bogdanp** [comment]
FYI, this kind of thing is better suited for the discussion board.

Rather than parameterize the `daemon` flag, I think you should just add a little 

```python
while True:
  sleep(1)
```

loop after you start the worker. This'll also give you a good place to insert signal (eg. `SIGTERM`) handling code.

**Comment by guzuomuse** [comment]
@Bogdanp ,thanks you,  in fact i do use  while True as you suggest.

by the way, i want to post these topic to the discussion board  ,but the board can't be accessed , it gave me a 400 error yesterday, i'm sorry to put it here. 
thank you again.
