### ISSUE TITLE
Improve Message.encode / Message.decode to add adapter

### ISSUE THREAD

**Issue by jssuzanne** [Bogdanp/dramatiq#17]
Hi,

I try to send uuid in the arguments and I don't want cast this value when I call my actor. 

dramatiq should add some hook to add adapter for the json (uuid, datetime, date, ...) to let the dev to implement their adapter.

**Comment by cailiang9** [comment]
Or can at lease use pickle as default serializer to support widely used numpy arrays.
If messages are not supposed to be seen by other languages like js, this would be a simple and good solution.

**Comment by Bogdanp** [comment]
Pickle represents somewhat of a security issue, but I'll add some encoding hooks over the holidays here!

**Comment by jssuzanne** [comment]
You also see the encoding of pyramid, they allow to add adapter for encoding

**Comment by Bogdanp** [comment]
#20 has been released in version `0.16` 🎉

**Comment by nachopro** [comment]
Hi, I want to know what is the right way to use a custom encoder:

I saw that `global_encoder` is defined as a `JSONEncoder` in the message.py
But I don't understand how to use another encoder. Is a custom middleware needed to achieve this?

Thanks.

**Comment by Bogdanp** [comment]
@nachopro you only need to call `set_encoder` once, before you send out any messages. Personally, I'd call it right after the call to `set_broker`.

**Comment by nachopro** [comment]
@Bogdanp I understand that your example is valid for a Flask project.
In a Django project with multiple apps or multiple `tasks` modules your way may be some inconsistent or tricky (for a newcomer like me).

I made a PR ;)
