### ISSUE TITLE
Feature request: Is there plans for a map() or chunk() function?

### ISSUE THREAD

**Issue by andyp05** [Bogdanp/dramatiq#170]
Are there any plans to implement a function similar to the chunk feature of multiprocessing.map() to reduce the overhead of messaging to the workers? Current;y I have a function that executes quickly 0.1s but I have to run it on millions of values. multiprocessing.map uses all cores and is pretty efficient (300,000 calls/s) over 16 cores. Dramatiq using redis running the same function using group() in a list comprehension works but is running at only 3,000/s. Thanks.

**Comment by andyp05** [comment]
Are there any plans to implement a function similar to the chunk feature of multiprocessing.map() to reduce the overhead of messaging to the workers? Current;y I have a function that executes quickly 0.1s but I have to run it on millions of values. multiprocessing.map uses all cores and is pretty efficient (300,000 calls/s) over 16 cores. Dramatiq using redis running the same function using group() in a list comprehension works but is running at only 3,000/s.  Thanks.

**Comment by Bogdanp** [comment]
I'm not sure I quite get it so you'll have to elaborate. Are you looking for a way to enqueue messages faster? Why can't you use `multiprocessing.map` or enqueue off of a thread pool to do this?

**Comment by andyp05** [comment]
I can't use multiprocessing.map() in a django app. It works fine in a regular python app, but I am trying to put the function in a web app. The following function works outside of django and runs at 300k/s. A typical run iterates over 4 million combinations.:

```
mp_pool = mp.Pool(processes=16)
all_res = mp_pool.map(process_combo, itertools.combinations(range(len(df_cycle)), 5))
```

If I translate the above functionality using dramatiq's group() function with 16 workers, the performance drops to 3k/s

```
    jobs = dramatiq.group([process_combo.message(combo) for combo in
                          itertools.combinations(range(len(df_cycle)), 5)]).run()
    all_res = jobs.get_results(block=True, timeout=100_000)
```
The overhead of sending 4 million individual messages kills performance. I think celery implements a map() function to solve this exact issue. Haven't tried it. Would love to stick with dramatiq. 

Hope this explains this better.

**Comment by Bogdanp** [comment]
Since you're using Django, make sure you don't have the `AdminMiddleware` turned on. That middleware is great for introspection but it can kill publishing times. If you want to speed things up beyond that, then enqueueing from inside a thread or process pool might still help.

**Comment by andyp05** [comment]
I do have AdminMiddleware turned off. I will try threading. In the meantime, please consider a mapping function. Thanks for your quick replies.

**Comment by rpkilby** [comment]
> I can't use multiprocessing.map() in a django app.

@andyp05 are you not able to use multiprocessing.map due to issues with the ORM?
