### ISSUE TITLE
Callback to send update to the task scheduler

### ISSUE THREAD

**Issue by dickreuter** [Bogdanp/dramatiq#173]
I have been using celery for a while but am looking for an alternative due to the lack of windows support. Dramqtiq is the top competitor. What I'm really looking for is for something that can distribute 1000 long running tasks onto 10 machines. Each should pick up the next job when it has completed the task, and give a callback with updates (in celery this can be nicely achieved with @task(bind=True), as the task instance itself can be accessed and I can send the status back to the instance that sent it with an update).

Is there a similar functionality available in dramatiq? Any suggestions would be appreciated. If not, is this something that could be implemented?

A nice example where this is demonstrated as well is here: https://blog.miguelgrinberg.com/post/using-celery-with-flask

**Comment by Bogdanp** [comment]
To sequence results between tasks, you can use the [composition primitives](https://dramatiq.io/cookbook.html#composition). There's no built-in way right now to send status updates back via the result backend, however. For that, you could potentially use a custom middleware.

This kind of thing is better suited for the [forum](https://www.reddit.com/r/dramatiq/) so I'd rather we continue this discussion there if you want to.
