### ISSUE TITLE
How to modify dramatiq appropriately

### ISSUE THREAD

**Issue by isaacleeai** [Bogdanp/dramatiq#176]
how can I modify dramtiq with minimal conflicts with future pushes?

**Comment by Bogdanp** [comment]
@isaacleeai Reddit's a more appropriate place for this kind of discussion. Generally:

* avoid changing code as much as possible; you should be able to do most things you want by leveraging middleware
* for things like modifying the multiprocessing code, a good approach might be to change things from the outside in, like we do in https://github.com/Bogdanp/dramatiq/blob/master/bin/dramatiq-gevent (i.e. monkeypatch things, then run the standard dramatiq code).

For code you absolutely have to change, I'm afraid there's no easy answer. Rebasing tends to make applying your changes onto upstream fairly straightforward so it might help to look into that.
