### ISSUE TITLE
`ResultTimeout` with Redis

### ISSUE THREAD

**Issue by isaacleeai** [Bogdanp/dramatiq#177]
# Issues

GitHub issues are for bugs.  If you have questions, please ask them on the [discussion board](https://discuss.dramatiq.io).

## Checklist

* [x] Does your title concisely summarize the problem?
* [x] Did you include a minimal, reproducible example?
* [x] What OS are you using?
* [x] What version of Dramatiq are you using?
* [x] What did you do?
* [x] What did you expect would happen?
* [x] What happened?

## What OS are you using?

CentOs7

## What version of Dramatiq are you using?

1.5.0

## What did you do?

called function completes and returns a list successfully ( I have chekd this with print statement, and it prints correctly whenever I call the function asynchronously ), but when I try to retrieve the retruned result with `tacotron.send(model).get_result(backend = result_backend, block=True)`, I get:
```
Traceback (most recent call last):
  File "actor.py", line 55, in <module>
    ret = tacotron.send().get_result(backend = result_backend, block=True)
  File "/home/msl/.virtualenvs/venv_tts/lib/python3.5/site-packages/dramatiq-1.5.0-py3.5.egg/dramatiq/message.py", line 147, in get_result
    return backend.get_result(self, block=block, timeout=timeout)
  File "/home/msl/.virtualenvs/venv_tts/lib/python3.5/site-packages/dramatiq-1.5.0-py3.5.egg/dramatiq/results/backends/redis.py", line 81, in get_result
    raise ResultTimeout(message)
dramatiq.results.errors.ResultTimeout: tacotron()
```

this is how I defined `tacotron(model)`:
```
@dramatiq.actor
def tacotron(model):
    return model.GetMel("President Trump met with other leaders at the Group of 20 conference.", 0)
```
I have put print statement inside `GetMel` of `model`, and it prints correctly -- i.e. right before it returns, I check the content of the list that is being returned, and they are fine. It prints within 1 second of the request.

Result backend: Redis
I'm not sure if this is correct. How I installed and started Redis:
```
sudo pip install redis
sudo yum install redis
sudo systemctl start redis
```

Broker: RabbitMQ

## What did you expect would happen?

for  `tacotron.send(model).get_result(backend = result_backend, block=True)` to return successfully

## What happened?

`get_result(block=True)` hung then errored
```
Traceback (most recent call last):
  File "actor.py", line 55, in <module>
    ret = tacotron.send().get_result(backend = result_backend, block=True)
  File "/home/msl/.virtualenvs/venv_tts/lib/python3.5/site-packages/dramatiq-1.5.0-py3.5.egg/dramatiq/message.py", line 147, in get_result
    return backend.get_result(self, block=block, timeout=timeout)
  File "/home/msl/.virtualenvs/venv_tts/lib/python3.5/site-packages/dramatiq-1.5.0-py3.5.egg/dramatiq/results/backends/redis.py", line 81, in get_result
    raise ResultTimeout(message)
dramatiq.results.errors.ResultTimeout: tacotron()
```

**Comment by Bogdanp** [comment]
Looks like you might not have set up your result backend correctly. Did you add the results middleware to your broker?

**Comment by isaacleeai** [comment]
I do so as instructed in your instructions:
```
result_backend = RedisBackend()

broker = RabbitmqBroker()
broker.add_middleware(Results(backend=result_backend))
dramatiq.set_broker(broker)
```

**Comment by Bogdanp** [comment]
And you're running your workers in the background before running main, right?

Try increasing the timeout `.get_result(block=True, timeout=900000)`.

**Comment by Bogdanp** [comment]
If that doesn't help, then upload the repo somewhere and I'll take a look later today.

**Comment by isaacleeai** [comment]
I'm not sure if that will fix. I checked by putting a print statement inside the function that I call, and it takes abut 0.5 seconds for the function to complete. However, even if it does complete, the returned value from the function never gets to my client.

**Comment by Bogdanp** [comment]
Yeah, you can just e-mail me the relevant bits if you want.

**Comment by isaacleeai** [comment]
Thanks a lot. I'll triple-check before I send you code and if I still can't figure out, I'll send you via your email.

**Comment by isaacleeai** [comment]
**Update:** I have undone all the changes to the source code, and replaced a call to my library to a much simpler one:

```
@dramatiq.actor
def test_basic(model):
    print("hello from test_basic")
    t = "return this"
    return t
```

Still, the error persists. From dramatiq server console, I can see that `"hello from test_basic"` is printed, but I still get `dramatiq.results.errors.ResultTimeout: test_basic()`

Could it be because I am using virtual envirionment and my `redis-server` is located in `/usr/bin/redis-server` and `rabbitmq-server` is in `/usr/sbin/rabbitmq-server` while `dramatiq` is in `~/.virtualenvs/venv_tts/bin/dramatiq` and the dramatiq library is in `/home/msl/.virtualenvs/venv_tts/lib`? 

I made sure to donwload all dependencies with `sudo paty/to/venv/python -m pip install -e '.[all]'`

**Comment by isaacleeai** [comment]
**update:** started from scratch. On a different computer ( CentOS7 with Python3.5 ), I have installed `dramatiq` with exactly the following commands:
```
sudo /usr/bin/python3.6 -m pip install -e '.[all]'
sudo yum install redis
sudo yum install rabbitmq-server
```

Then I wrote two files: `actor.py` -- used to start worker and given to as input to `dramatiq` binary

```python
import time
import dramatiq
from dramatiq.brokers.rabbitmq import RabbitmqBroker
from dramatiq.results.backends.redis import RedisBackend
from dramatiq.results import Results

result_backend = RedisBackend()

broker = RabbitmqBroker()
broker.add_middleware(Results(backend=result_backend))
dramatiq.set_broker(broker)

@dramatiq.actor
def test_basic(model):
    print("hello from test_basic")
    t = "return this"
    return t
```

And `request.py` which sends a simple request.
```python
# request.py
import actor
import time

if __name__ == '__main__':
    start = time.time()
    print("start time: " + str(start))
    ret = actor.test_basic.send().get_result(block=True)
    print(ret)
    d = time.time() - start
    print(d)
```

Then I booted up worker with `dramatiq` binary and sent a request as below:
```
dramatiq -p 1 -t 1 actor
python3.6 request.py
```

On the terminal window with the worker, I clearly see the printed message:
`"hello from test_basic"`

but I get this error on the terminal that called `request.py`:
```
Traceback (most recent call last):
  File "request.py", line 7, in <module>
    ret = actor.test_basic.send().get_result(block=True)
  File "/usr/local/lib/python3.5/site-packages/dramatiq/message.py", line 147, in get_result
    return backend.get_result(self, block=block, timeout=timeout)
  File "/usr/local/lib/python3.5/site-packages/dramatiq/results/backends/redis.py", line 81, in get_result
    raise ResultTimeout(message)
dramatiq.results.errors.ResultTimeout: test_basic()
```

**Comment by Bogdanp** [comment]
Ah, sorry for not noticing this earlier.  Your issue is that you haven't told the actor to store its results.

```python
@dramatiq.actor
def test_basic(model):
    print("hello from test_basic")
    t = "return this"
    return t
```

should be 

```python
@dramatiq.actor(store_results=True)
def test_basic(model):
    print("hello from test_basic")
    t = "return this"
    return t
```

This is [shown](https://dramatiq.io/reference.html#dramatiq.results.Results) in the docs, but it's not really emphasized. Sorry!

**Comment by isaacleeai** [comment]
Oh, that's embarrassing haha. Thanks a lot! Saved me my day.

**Comment by sathk882** [comment]
This discussion saved my time.

**Comment by Bogdanp** [comment]
I'm happy to take pointers re. what the documentation could be doing better to help in these cases.

**Comment by sathk882** [comment]
may be need to highlight in get_results and wait methods in documentation

**Comment by denny4nl** [comment]
This discussion is really helpful to save me time.
