### ISSUE TITLE
Dependencies not installed when installing from source

### ISSUE THREAD

**Issue by isaacleeai** [Bogdanp/dramatiq#178]
# Issues

GitHub issues are for bugs.  If you have questions, please ask them on the [discussion board](https://discuss.dramatiq.io).

## Checklist

* [v ] Does your title concisely summarize the problem?
* [ v] Did you include a minimal, reproducible example?
* [ v] What OS are you using?
* [ v] What version of Dramatiq are you using?
* [ v] What did you do?
* [ v] What did you expect would happen?
* [ v] What happened?

## What OS are you using?

CentOS7

## What version of Dramatiq are you using?

1.5.0

## What did you do?

git-clonned, then ran `python setup.py install`

## What did you expect would happen?
for `redis` and `watch` to be installed correctly with dependencies

## What happened?

`redis` was not installed so I installed manually with:
```
pip install redis
sudo yum install redis
```

and `watch` was not installed either, and not sure how to install manually.

**Comment by Bogdanp** [comment]
You need to specify the dependency set you want and you need to use pip.

For example:

```
git clone https://github.com/Bogdanp/dramatiq
cd dramatiq
pip install '.[redis, watch]'
```

**Comment by isaacleeai** [comment]
Thanks. After installing as such, in order to use RabbitMQ broker and Redis result backend, I would need to start both with:
```
sudo rabbitmq-server
sudo systemctl start redis
```
am I correct?

**Comment by Bogdanp** [comment]
Yes, though you'll probably want to start the rmq service with `sudo systemctl start rabbitmq-server` (or whatever the server is called on centos) instead of running it in the foreground (which `sudo rabbitmq-server` would do).

**Comment by isaacleeai** [comment]
Thanks. Unfortunately, this was not the source of the problem for the hanging that I have reported in this [issue](https://github.com/Bogdanp/dramatiq/issues/177). Do you think you could help me out? Thanks a lot
