### ISSUE TITLE
Move to Semaphore CI

### ISSUE THREAD

**Issue by Bogdanp** [Bogdanp/dramatiq#180]
I belive that Travis will soon stop offering its free service due to the acquisition by Idera so we should switch to Semaphore before that happens.

**Comment by ryanhiebert** [comment]
I don't have any particular reason to believe that Travis is gonna become non-free, but I've not been very happy with their service of late, unfortunately. I've personally been looking to migrate to GitHub actions, though I haven't gotten that working anywhere yet and I don't know if there might be some show stopping limitations.

**Comment by rpkilby** [comment]
Even if they don't end their free service, they recently fired a lot of their senior engineers. I'm wondering if Travis will remain a viable option in the long run (e.g., will they update to Ubuntu bionic, given the significant development costs?). 

I've also been looking to migrate projects to a different CI service. Asking out of curiosity - any reason you're going with Semaphore? Have you looked into/tried Circle or Azure DevOps?

**Comment by Bogdanp** [comment]
@rpkilby I've been using Semaphore V2 for some non-OSS projects and it's been a joy to work with:

* VMs not containers,
* simple, fast UI,
* (metered) ssh access to the build machine so you can debug problems,
* 21.5hrs of build time on a 2 vCPU, 4GB ram machine for free every month as opposed to circle's 0.5hrs on a single container.

I believe they plan on offering free OSS builds eventually so that's also a plus.  That said, I've never used Circle or Azure DevOps and this isn't set in stone.  What do you like about them?

**Comment by rpkilby** [comment]
I just recently started looking into Circle, and have seen Azure used on some other OSS projects. I haven't really formed an opinion at this point. I was mostly asking since I'm not familiar with Semaphore.

**Comment by ryanhiebert** [comment]
@Bogdanp : It's very cool that you used GitHub actions. I expect I'll be using the work you did as a template to get me started on my other projects. Do you feel like it's a good solution?

**Comment by Bogdanp** [comment]
Now that I've got it working I think it's fairly nice! There are a few problems, though:

* the docs could be better,
* the ux is lacking: you can't see an action's logs while it's running, for one; nor can you restart an action after it fails afaict (although there is a button for it),
* one action failing automatically pre-emptively cancels all other actions.

**Comment by ryanhiebert** [comment]
Interesting. I wonder if you can split things up into different workflows to avoid the cancelling behavior. Anyway, thanks for sharing your thoughts, I appreciate it.

**Comment by zupo** [comment]
I moved all my personal and work projects from TravisCI to CircleCI last year. Some insights available on https://github.com/niteoweb/pyramid-realworld-example-app/issues/37. 

Mostly, I went for the speed. And yep, CirlceCI is fast.
