### ISSUE TITLE
`bench.py` syntax error

### ISSUE THREAD

**Issue by isaacleeai** [Bogdanp/dramatiq#181]
# Issues

GitHub issues are for bugs.  If you have questions, please ask them on the [discussion board](https://discuss.dramatiq.io).

## Checklist

* [ v] Does your title concisely summarize the problem?
* [ v] Did you include a minimal, reproducible example?
* [ v] What OS are you using?
* [ v] What version of Dramatiq are you using?
* [ v] What did you do?
* [ v] What did you expect would happen?
* [ v] What happened?

## What OS are you using?

CentOS7

## What version of Dramatiq are you using?

1.5.0, python 3.5, redis 5.0.3. 

## What did you do?

`python bench.py --help`

## What did you expect would happen?

help message

## What happened?

```
  File "bench.py", line 71
    raise argparse.ArgumentTypeError(f"benchmark must be one of {benchmarks!r}")
                                                                              ^
SyntaxError: invalid syntax
```

**Comment by Bogdanp** [comment]
You need Python 3.6 to run this script.
