### ISSUE TITLE
[feature request] add crontab like interface to schedule tasks like in tasktiger

### ISSUE THREAD

**Issue by cailiang9** [Bogdanp/dramatiq#19]
related interfaces can be seen here: https://github.com/closeio/tasktiger

**Comment by jssuzanne** [comment]
+1 cron service could be a good feature

**Comment by Bogdanp** [comment]
I've thought about this and ultimately decided that implementing something like this would mean building in a lot of functionality that already exists in things like [`apscheduler`](https://apscheduler.readthedocs.io/en/latest/) so I'm just going to recommend that people use that in conjunction with Dramatiq.

I'll probably write a little how-to on using the two of 'em together and link it here when I do.

**Comment by rakanalh** [comment]
APScheduler example:
```
import os
import django

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "settings")
django.setup()

from apscheduler.schedulers.background import BlockingScheduler  # noqa

from myapp.tasks import MyTask  # noqa


if __name__ == '__main__':
    scheduler = BlockingScheduler()
    scheduler.add_job(MyTask.send, 'interval', minutes=1)
    scheduler.start()
    print('Press Ctrl+{0} to exit'.format('Break' if os.name == 'nt' else 'C'))
    scheduler.shutdown()

```

**Comment by ericgj** [comment]
Hi, ran into problems with using APScheduler in this way.  It pickles arguments, so any `Actor.send` is going to need `self` (i.e. the actor) as the first argument, and actors can't be pickled.  I tried various things but it seems impossible to use bound methods as jobs -- with or without additional arguments. Really it's an issue for APScheduler I suppose but have others found a way around this in the context of Dramatiq?

**Comment by Bogdanp** [comment]
Hi @ericgj! If you can't use the `MemoryJobStore` (which doesn't use pickle), I'd write dispatcher functions that *can* be pickled. For example:

```python
def dispatch_some_task(*args, **kwargs):
  return some_task.send(*args, **kwargs)

if __name__ == "__main__":
  scheduler = BlockingScheduler()
  scheduler.add_jobstore("redis")
  scheduler.add_job(dispatch_some_task, args=(1, 2,), 'interval', minutes=1)
  scheduler.start()
```

If you want to get a little crazy you could do something like this:

`cron.py`:
```python
import importlib 

from apscheduler.schedulers.background import BackgroundScheduler
from apscheduler.triggers.cron import CronTrigger
from functools import wraps

scheduler = BackgroundScheduler()
scheduler.add_jobstore("redis")

def _dispatch(module_path, func_name):
  module = importlib.import_module(module_path)
  actor = getattr(module, func_name)
  return actor.send()

def cron(crontab):
  trigger = CronTrigger.from_crontab(crontab)
  def decorator(actor):
    module_path = actor.fn.__module__
    func_name = actor.fn.__name__
    scheduler.add_job(_dispatch, trigger=trigger, args=(module_path, func_name,))
    return actor
  return decorator
```

`some_module.py`:
```python
import dramatiq

from .cron import cron

@cron("* * * * *")
@dramatiq.actor
def do_stuff():
  ...
```

I wrote that off the top of my head (read: I haven't actually run the above code), but I think something like that should work. It may even be a good idea to generalize it a little bit further and publish it as a separate package.

**Comment by ericgj** [comment]
Thanks. If I was working with plain old decorated actors something like that would work. The deeper issue is I'm trying to tackle sequencing/chaining tasks, where the sequence of tasks is dynamic (can be user defined essentially). I will have to rethink how I was doing that.

**Comment by ericgj** [comment]
Actually for anyone interested, and to save some work, it looks like APScheduler does something similar under the hood. I haven't tried it, but looks like you can pass a `module:object` string to `scheduler.add_job`. See 

- https://github.com/agronholm/apscheduler/blob/master/apscheduler/job.py#L155-L157
- https://github.com/agronholm/apscheduler/blob/master/apscheduler/util.py#L256-L279

(Thanks for this great project by the way - and hello from Elm world :wave: )

**Comment by Bogdanp** [comment]
Nice find and thanks for the kind words! I wrote a little post [here](https://defn.io/2018/01/11/dramatiq-cron/) combining the two approaches.

Nice to see ya in Python land. :D

**Comment by ericgj** [comment]
FYI, I sorted sequencing/chaining tasks with a custom middleware. Similar to the "callbacks" middleware, but more involved because each task has its own success callback which is the next task in the sequence with all associated state needed to run it.  Here's a [gist](https://gist.github.com/ericgj/6491240e2c132c188f29f5f5ac8dd8a0).  

If you think this would be useful to include somewhere as an example or if there's some kind of "dramatiq-contrib" I'd be happy to drop it there.

**Comment by Bogdanp** [comment]
That's really neat! I like your approach. Would you mind adding that to the discussion around composition in https://github.com/Bogdanp/dramatiq/issues/29 ? I'll post my thoughts in there sometime this weekend, once I've had a chance to sit down and think about the subject a little more.

**Comment by tyan4g** [comment]
APScheduler is bad .I think no one want's to use it in production really...

**Comment by 2miksyn** [comment]
Thinks, better way on 
*NIX is using ‘cron’ for scheduling tasks

**Comment by ericgj** [comment]
I don't know that this is the best place for general conversation about scheduling, but just to note APScheduler fills a different need than cron. When you have multiple, dynamic, user-defined schedules within your application -- I may be missing something, but in my experience cron is not the best tool for that.

**Comment by bersace** [comment]
Maybe some of you will be interested in [periodiq](https://gitlab.com/bersace/periodiq). It's a simple cron-like scheduler I wrote for dramatiq. The source code [fit in one file](https://gitlab.com/bersace/periodiq/blob/master/periodiq.py) and is easy to review.

Here is a sample from [example.py](https://gitlab.com/bersace/periodiq/blob/master/example.py) :

``` python
@dramatiq.actor(periodic=cron('*/15 * * * *'))
def quarthourly():
    logger.info("Quart-hourly.")

@dramatiq.actor(periodic=cron('@hourly'))
def hourly():
    logger.info("Hourly.")
```
