### ISSUE TITLE
RabbitMQ broker should close connection after declare_queue

### ISSUE THREAD

**Issue by hugochinchilla** [Bogdanp/dramatiq#193]
## Checklist

* [x] Does your title concisely summarize the problem?
* [x] Did you include a minimal, reproducible example?
* [x] What OS are you using?
* [x] What version of Dramatiq are you using?
* [x] What did you do?
* [x] What did you expect would happen?
* [x] What happened?

## What OS are you using?

Docker image built from library/python:3.7.0

## What version of Dramatiq are you using?

1.5.0

## What did you do?

Importing functions decorated with `@dramatiq.actor` causes a connection to be established against rabbitmq.

```python
from myproject.workers import send_email
```

```python
import dramatiq
from dramatiq.brokers.rabbitmq import RabbitmqBroker

from myproject.settings import settings

# Setup dramatiq
rabbitmq_broker = RabbitmqBroker(url=settings.RABBITMQ_BROKER_URL)
dramatiq.set_broker(rabbitmq_broker)


@dramatiq.actor()
def send_email():
    pass
```

When the process which imported the module is closed the following error appears on rabbitmq log:

```
client unexpectedly closed TCP connection
```

I've tried to fix the problem with an `atexit` callback:

```python
@atexit.register
def close_broker_connection():
    global rabbitmq_broker
    rabbitmq_broker.close()
```

It works if I try to reproduce the issue in a python console, but when I run the code in production (inside an Apache Airflow DAG) the isse persist and the `atexit` trigger seems not to do anything.

## What did you expect would happen?

If the actor is never used (call to `send_email.send()`) no connections to rabbitmq should left open.

The broker should close the current connection after `declare_queue` or at least give an option to decide which behavior to do.

## What happened?

explained above.

**Comment by hugochinchilla** [comment]
I have written a custom middleware that fixer my problem with unexpected closed connections:

```python
class ConnectionClose(Middleware):
    """
    Middleware that automatically closes rabbitmq connections after declare_actor
    """

    @property
    def actor_options(self):
        return set()

    def after_declare_actor(self, broker, actor):
        broker.close()
```

What I don't like is that for each function defined as an `actor` a connection has to be created and then discarded which causes a lot of connections/disconnections for just an import, even if the actor is never invoked.

I think the registration of queues should be lazy and happen only on the first call to `actor.send()`, I can see how this can become a problem for the worker to discover queues but still I think this should be the way to do it.

**Comment by Bogdanp** [comment]
@hugochinchilla take a look at the solution in #163 for lazily declaring queues, maybe that'll help. As it stands, this is not going to change any time soon.

**Comment by hugochinchilla** [comment]
Thank you @Bogdanp , this helps.
