### ISSUE TITLE
Test with StrubBroker takes too much time while throwing no exception (within Django)

### ISSUE THREAD

**Issue by waegaein** [Bogdanp/dramatiq#197]
## What OS are you using?

Ubuntu 16.04 or macOS 10.13.6

## What version of Dramatiq are you using?

Dramatiq[rabbitmq, watch] 1.5.0
with
Python 3.7.1
Django 2.1.7
django-dramatiq 0.5.3
pytest 4.1.1
pytest-django 3.4.1

## What did you do?

I ran pytest with the following settings, conftest and test file.
```
--settings.py (for test)--

DRAMATIQ_BROKER = {
    "BROKER": "dramatiq.brokers.stub.StubBroker",
    "OPTIONS": {},
    "MIDDLEWARE": [
        "dramatiq.middleware.AgeLimit",
        "dramatiq.middleware.TimeLimit",
        "dramatiq.middleware.Callbacks",
        "dramatiq.middleware.Pipelines",
        "dramatiq.middleware.Retries",
        "django_dramatiq.middleware.AdminMiddleware",
        "django_dramatiq.middleware.DbConnectionsMiddleware",
    ]
}
```
```
--contfest.py--

@pytest.fixture(scope='session')
def django_db_setup(django_db_setup, django_db_blocker):
    with django_db_blocker.unblock():
        database_dump_path = SOME_PATH
        call_command('loaddata', '--database', 'default', database_dump_path)

@pytest.fixture
def broker():
    broker = dramatiq.get_broker()
    broker.flush_all()
    return broker

@pytest.fixture
def worker(broker):
    worker = dramatiq.Worker(broker, worker_timeout=10)
    worker.start()
    yield worker
    worker.stop()
```
```
---test file---

@pytest.mark.django_db
def test_DRAMATIQ_ACTOR_ANNOTATED_FUNCTION(broker, worker):
    DRAMATIQ_ACTOR_ANNOTATED_FUNCTION.send(SOME_ARGUMENTS)
    broker.join('default')

    assert worker.join() is None
```

## What did you expect would happen?

Test runs within reasonable time. Otherwise, throw exception/error.

## What happened?

Test took 100+ seconds, far longer than I expected as 'reasonable'. My task takes just a few seconds when I run it outside of the test, with RabbitMQ broker. But there was not any exception/error thrown with this long test.

**Comment by Bogdanp** [comment]
Try removing the AdminMiddleware and see if that makes a difference.

**Comment by waegaein** [comment]
Hi, Bogdan
Thank you so much for your quick&precise advice.
The test now runs within several seconds as I was hoping!
It seems that the README.md of the django-dramatiq repo needs to be modified, which states AdminMiddleware to be included in Testing section.
By the way, could you please let me know how was AdminMiddleware interrupting the test? It would make me more a fan of Dramatiq  :D

**Comment by Bogdanp** [comment]
It's hard to say without seeing your code and knowing more about your architecture, but the admin middleware stores all task information in your db so I figured that's likely where the slowdown came from (likely a lot of transaction contention or something).

Glad it helped!
