### ISSUE TITLE
Heartbeats for consumers remain in Redis after shutting them down

### ISSUE THREAD

**Issue by berkinmalkoc** [Bogdanp/dramatiq#199]
# Issues

GitHub issues are for bugs.  If you have questions, please ask them on the [discussion board](https://discuss.dramatiq.io).

## Checklist

* [x] Does your title concisely summarize the problem?
* [] Did you include a minimal, reproducible example?
* [x] What OS are you using?
* [x] What version of Dramatiq are you using?
* [x] What did you do?
* [x] What did you expect would happen?
* [x] What happened?

## What OS are you using?

Ubuntu 18.04

## What version of Dramatiq are you using?

1.5.0

## What did you do?

Started a couple of consumers, checked the presence of their heartbeats in Redis and then, stopped the the consumers with `supervisorctl stop consumer`.

## What did you expect would happen?

I expected that consumers clean up all their traces, including heartbeats in the (Redis) broker, when being shut down.

## What happened?

Heartbeats remained in Redis (and when I restarted the consumers, they appended completely new heartbeats (corresponding to their new borker_ids)).

**Comment by Bogdanp** [comment]
The new consumers will eventually remove the old hearbeats from the set so this is working as expected. We could eventually make it so each worker removes its own heartbeat upon shutdown but it's more trouble than it's worth right now.

**Comment by berkinmalkoc** [comment]
> The new consumers will eventually remove the old hearbeats from the set so this is working as expected. We could eventually make it so each worker removes its own heartbeat upon shutdown but it's more trouble than it's worth right now.

Thank you for your reply and the decision seems reasonable. But what do you exactly mean by "eventually", that is, when should we expect the "old" heartbeats to get deleted?

**Comment by Bogdanp** [comment]
They will be deleted as soon as the next maintenance cycle is triggered after each of them expire. Take a look at this block for details: https://github.com/Bogdanp/dramatiq/blob/master/dramatiq/brokers/redis/dispatch.lua#L78-L100 . As long as you're running at least one worker, this is guaranteed to happen so the set won't grow unbounded if you're worried about that.
