### ISSUE TITLE
Can I handle the log freely

### ISSUE THREAD

**Issue by QAQ110** [Bogdanp/dramatiq#205]
Sorry, I am responding to 404 by visiting https://discuss.dramatiq.io/

Can I handle the log freely, just like flask:
```
log_format = '%(asctime)s [%(threadName)s:%(thread)d] [%(filename)s:%(lineno)d] [%(levelname)s]- %(message)s'
        file_handler = RotatingFileHandler('logs/logging.log', 'a', 10 * 1024 * 1024, 10, encoding='utf-8')
        file_handler.setFormatter(logging.Formatter(log_format))
        file_handler.setLevel(logging.INFO)
        app.logger.addHandler(file_handler)
```
More is that I want to be free to control the size of the log file.

**Comment by Bogdanp** [comment]
The new discussion board is on reddit: https://www.reddit.com/r/dramatiq/

You should be able to grab the root dramatiq logger and change it however you like:

```
logging.getLogger("dramatiq").addHandler(...)
```

**Comment by QAQ110** [comment]
Thank you! Your reply perfectly solved my problem.
