### ISSUE TITLE
Add a way for actors to access the current message

### ISSUE THREAD

**Issue by nachopro** [Bogdanp/dramatiq#208]
Hello. I have an Actor (function) and I need to know if it is the first or fifth execution.
(based on his retry number I must execute a complementary code)

Maybe I should use a middleware or pipeline?

Thanks for your time.

**Comment by Bogdanp** [comment]
Can you use `retry_when`? 

```python
def should_retry(retries_so_far, e):
  ...

@actor(retry_when=should_retry)
def some_fn():
  ...
```

**Comment by nachopro** [comment]
@Bogdanp I was away from the PC these days :(
I switched my code to work with callbacks (with some introduced bugs :P) but this feature is a great solution!

I'm very glad with your response. Thanks you very much.
