### ISSUE TITLE
Should TimeLimit middleware restart hanging thread instead of stopping?

### ISSUE THREAD

**Issue by metheoryt** [Bogdanp/dramatiq#211]
if an actor exceeds time limit, hanging thread is stopped and no new thread is created, so i need to restart worker manually before active threads is going out of stock. Is this expected behaviour?

i am using:
dramatiq 1.5.0, python 3.6.7, CentOS Linux release 7.4.1708 (Core)

**Comment by Bogdanp** [comment]
That sounds like a bug. Please set up a minimal example that reproduces the behavior and I'll take a look.

**Comment by metheoryt** [comment]
It was not as simple as I thought, but seems that I found the reason

```
import dramatiq
from time import sleep
from dramatiq.brokers.redis import RedisBroker
import requests

broker = RedisBroker(url='redis://localhost')
dramatiq.set_broker(broker)

@dramatiq.actor(time_limit=5_000)
def longrun():
    log.info('running')
    sleep(60*60) # an hour
    # or alternative
    # requests.get(f'https://httpstat.us/200?sleep={60_000*60}')
```
In this example TimeLimit will log "Time limit exceeded. Raising exception in worker thread {number}" after 5 seconds, but actually raise the exception and release thread after an hour.

In my case there was an http request without timeout set, and external server was holding connection "forever", i guess.

**Comment by Bogdanp** [comment]
Ah, I see. This is working as expected in that case. Threads can only be killed once they become active (acquire the GIL) in CPython. See [this note](https://dramatiq.io/reference.html#dramatiq.middleware.TimeLimit) for details.

**Comment by z0z0r4** [comment]
Can I treat httpx.get and the worker thread blocking and not restarting as the same reason as time.sleep and the reason as GIL? I don’t quite understand
`20240925 08:36:10 | __init__.callHandlers | WARNING: Time limit exceeded. Raising exception in worker thread 140041342928576.`
