### ISSUE TITLE
Broker set when running worker doesn't affect actors

### ISSUE THREAD

**Issue by michaelbeaumont** [Bogdanp/dramatiq#214]
# Issues

If I declare an actor in `actors.py`:

```
from dramatiq import actor
@actor
  def importer():
    pass
```

and a broker in `brokers.py`:

```
from dramatiq.brokers.rabbitmq import RabbitmqBroker
broker = RabbitmqBroker(host="rabbitmq", port=5672)
```

and run `dramatiq brokers:broker actors`, I get connection errors, because the `@actor` decorator at import tries to connect to the global broker, which is unset, and so by default the host becomes `localhost`, because the global broker is independent of the `broker` the `Worker` gets.

I tried to use `set_broker` and the entrypoint `dramatiq.cli.main`but this failed because the worker spawns multiple processes.

I fear I just don't get the intended usage of brokers here and am misusing them/dramatiq. I just want to connect to a different RabbitMQ host for all of my actors (i actually want it to be configurable from the command line), but it's turning out to be a surprisingly difficult task.

## Checklist

* [x] Does your title concisely summarize the problem?
* [x] Did you include a minimal, reproducible example?
* [x] What OS are you using?
* [x] What version of Dramatiq are you using?
* [x] What did you do?
* [x] What did you expect would happen?
* [x] What happened?

## What OS are you using?

Arch Linux/Docker/Kubernetes

## What version of Dramatiq are you using?

`1.6.0`

## What did you do?

Tried to change the broker at runtime for workers for all actors using the `broker` argument.

## What did you expect would happen?

The worker sets the default/global broker for all actors and they can connect to the queue.

## What happened?

The broker argument is ignored by the `@actor` decorator, where it is instead "hardcoded".

**Comment by Bogdanp** [comment]
In `brokers.py`, you should set the default broker by calling `set_broker`.

```python
import dramatiq
from dramatiq.brokers.rabbitmq import RabbitmqBroker


dramatiq.set_broker(RabbitmqBroker(host="rabbitmq", port=5672))
```

Then you can run your workers by invoking dramatiq:

```
dramatiq brokers actors
```

When dramatiq loads your modules, it does so in the order that they are specified. So `brokers` will be loaded first, then `actors`. Since `brokers.py` calls `set_broker`, then all subsequent modules will use that broker by default. If you wanted an actor to use a specific broker, then you would have to specify that broker when you use the `@actor` decoator:

```python
@actor(broker=foo_broker)
def some_actor:
    # uses the broker referenced by the foo_broker variable
    ...

@actor
def another_actor:
    # references the global broker (defaults to RMQ on localhost unless you use set_broker)
    ...

```

Hope that helps!

**Comment by michaelbeaumont** [comment]
Right, that makes sense, thank you. I think I was misled by the `:broker` option. What's the intended use case there?

**Comment by Bogdanp** [comment]
That option allows you to select which broker to run workers for.

Eg. if you have 2 sets of brokers in your `brokers.py` module `redis_broker` and `rmq_broker`, you'll need to run two separate sets of workers (one for each):

```
dramatiq brokers:redis_broker actors # processes messages off of redis
```

and

```
dramatiq brokers:rmq_broker actors # processes messages off of RMQ
````

Without the `:broker` option, dramatiq will discover and use the global default broker. Take a look at [this code](https://github.com/Bogdanp/dramatiq/blob/master/dramatiq/cli.py#L102) for details.

**Comment by michaelbeaumont** [comment]
In that case, the same problem I had would occur, right? All of the actors in `actors.py` defined for a certain broker, whether it's the global broker or not, will try to connect to their brokers. E.g. if I run `dramatiq brokers:rmq_broker actors` and can't connect to the redis instance, those actors in `actors.py` defined with `broker=redis` will fail at:
https://github.com/Bogdanp/dramatiq/blob/06e7b5e57188606db5be5b4910d7c63309eacff0/dramatiq/cli.py#L300-L301

i.e. you need to make separate your actors based on their broker because they connect when the decorator is called, at import.

**Comment by Bogdanp** [comment]
Yes, that’s right. Although I took your original problem to be that you hadn’t set up a global broker in the first place, so your actors were falling back to the default broker that’s in place for convenience (though I am reconsidering this functionality; in 2.0 I will probably make it so you’re forced to declare the global broker) and failing to connect to it. 

If your workers are going to be isolated based upon the broker that they connect to, then you’ll need to separate the actors either at the module level or at runtime by conditionally declaring them. If they’re not isolated, then everything will just work.

**Comment by isra17** [comment]
Just had the same confusion as OP. To me this option feels unintuitive, why doesn't the CLI call `set_broker` once it loads a broker given in the form of `dramatiq module:broker`?
