### ISSUE TITLE
min_backoff

### ISSUE THREAD

**Issue by kulias** [Bogdanp/dramatiq#215]
# Issues

GitHub issues are for bugs.  If you have questions, please ask them on the [discussion board](https://discuss.dramatiq.io).

## Checklist

* [ ] Does your title concisely summarize the problem?
* [ ] Did you include a minimal, reproducible example?
* [ ] What OS are you using?
* [ ] What version of Dramatiq are you using?
* [ ] What did you do?
* [ ] What did you expect would happen?
* [ ] What happened?

**Comment by Bogdanp** [comment]
Looks like you forgot to fill in the template.

**Comment by kulias** [comment]
I'm so sorry about it, was doing a search. Don't know why an issue had been submitted.
Please delete it and accept my apologies.

**Comment by Bogdanp** [comment]
No worries!
