### ISSUE TITLE
Error on run dramatiq on high (default) threads and worker

### ISSUE THREAD

**Issue by weiztech** [Bogdanp/dramatiq#218]
on run `dramatiq task` with broker `Rabbitmq` got error (os `Mac Mojave 10.14.5.`)

> [2019-07-22 16:30:24,823] [PID 82438] [Thread-20] [dramatiq.worker.ConsumerThread(transaction.DQ)] [CRITICAL] Consumer encountered a connection error: AMQPConnectionError: (AMQPConnectorSocketConnectError: ConnectionRefusedError(61, 'Connection refused'),)

with default settings `process` and `threads`
```
--processes PROCESSES, -p PROCESSES
                        the number of worker processes to run (default: 16)
--threads THREADS, -t THREADS
                        the number of worker threads per process (default: 8)
```

i did some research and got run command successfully with process and thread:
`dramatiq tasks -p 12 -t 6`

and if i add add more thread and process it will be error like above
`dramatiq tasks -p 14 -t 7`

not sure if `dramatiq` bug or amqp/rabbitmq limitation connection

**Comment by Bogdanp** [comment]
This is unlikely to be due to dramatiq. 

You should take a look at your RMQ configuration, the RMQ logs and the file descriptor limits on your machine. Most likely it's related to the latter since the default RMQ configuration supports a high number of connections.

**Comment by weiztech** [comment]
@Bogdanp 

increased the file descriptor fixed the issue. Thank you

**Comment by toti1212** [comment]
I think I had the same problem but running RabbitMQ as a container. How did you solve it @weiztech ? 
I'm running `django-dramatiq` with the default command (`python manage.py rundramatiq`) and I notice that the default number of threads and process is equal to the number of CPU cores (in my case 8).
Also, my Rabitmq is running with the default configuration.

**Comment by weiztech** [comment]
@toti1212 
last time, I fixed it by just increase the ` file descriptor limits` limit using `ulimit`.
check the [link]( https://marcelegger.net/rabbitmq-performance-and-file-descriptors) for more detail explanation
