### ISSUE TITLE
Shouldn't log severity be ERROR instead of WARNING when a problem occurs on worker?

### ISSUE THREAD

**Issue by th0th** [Bogdanp/dramatiq#220]
I am using sentry to collect logs with `ERROR` severity. I think I should be handling `WARNING` ones as well, however, I had to go with `>=ERROR` since some third party libraries cause much unexpected noise with warnings.

Here are the lines:

https://github.com/Bogdanp/dramatiq/blob/d7da3c7034752e154e2a1fd917f8baab5643553b/dramatiq/worker.py#L485

https://github.com/Bogdanp/dramatiq/blob/d7da3c7034752e154e2a1fd917f8baab5643553b/dramatiq/worker.py#L487

These two lines run when message processing fails on the worker. And I feel like `WARNING` suits better for the cases when a task is done but something strange happens.

What do you think?

**Comment by Bogdanp** [comment]
Yes, I think bumping both of those to `ERROR` would be good.  If you want to make a PR, I'd be happy to merge and release it.

**Comment by Bogdanp** [comment]
I'm closing this since the PR was merged. I'll cut a release this Saturday. Thanks!
