### ISSUE TITLE
some of tasks from one specific queue aren't consumed by worker

### ISSUE THREAD

**Issue by metheoryt** [Bogdanp/dramatiq#224]
I have a worker process that consumes tasks from single queue. Recently i began to notice some of tasks from this queue aren't picked up by worker and stayed in queue, some of which executed multiple times before, some didn't even executed.

I'm not sure i can reproduce this because my other queues works fine and i don't see sufficient differencies between them.

Here's how queue looks in a dashboard:
![most recent tasks](https://user-images.githubusercontent.com/6823542/64599868-01531a00-d3dc-11e9-8f5b-9e250498cc69.png)
...
![oldest tasks](https://user-images.githubusercontent.com/6823542/64599960-2a73aa80-d3dc-11e9-829a-72bc68fb5c27.png)

On the other hand, logs showing that other tasks from this queue ARE being processed by worker, for example last task was today.

Also, i have this error in worker logs, it appers a few times a day for a several months and till now, may be it can give a clue on what's happening:
```
2019-09-10 09:14:34,672 31472-Thread-4     CRITICAL | -                                    | -                           : -             : -               | dramatiq.worker.ConsumerThread(transfers.DQ): Consumer encountered an unexpected error.
Traceback (most recent call last):
  File "/root/.local/share/virtualenvs/app-ueEJiAOq/lib/python3.6/site-packages/dramatiq/worker.py", line 253, in run
    for message in self.consumer:
  File "/root/.local/share/virtualenvs/app-ueEJiAOq/lib/python3.6/site-packages/dramatiq/brokers/redis.py", line 318, in __next__
    message = Message.decode(data)
  File "/root/.local/share/virtualenvs/app-ueEJiAOq/lib/python3.6/site-packages/dramatiq/message.py", line 96, in decode
    return cls(**global_encoder.decode(data))
  File "/root/.local/share/virtualenvs/app-ueEJiAOq/lib/python3.6/site-packages/dramatiq/encoder.py", line 52, in decode
    return json.loads(data.decode("utf-8"))
AttributeError: 'NoneType' object has no attribute 'decode'
```

I don't know where to dig. I think it should help if I clear the queue and requeue all the frozen tasks, but if it bug consequence I think you would like to know about it.

## What OS are you using?
CentOS Linux 7 (Core)

## What version of Dramatiq are you using?
Dramatiq 1.6.1
redis broker

**Comment by Bogdanp** [comment]
What happens if you click on one of those jobs in the dashboard? Can you post a screenshot of the details page for one of those jobs?

**Comment by metheoryt** [comment]
Fresh example:
![image](https://user-images.githubusercontent.com/6823542/65411207-16816d00-de0e-11e9-9c6e-6c6a2b85981f.png)

Message content in `dramatiq:transfers.DQ.msgs`:
```
 1) "105616d3-9d0f-4dee-802d-85e29830d517"
 2) "{\"queue_name\":\"transfers.DQ\",\"actor_name\":\"process_transfer\",\"args\":[810020026895],\"kwargs\":{},\"options\":{\"redis_message_id\":\"105616d3-9d0f-4dee-802d-85e29830d517\",\"eta\":1569225479260},\"message_id\":\"47038aaf-3d99-448a-8617-e9cc8295ce0a\",\"message_timestamp\":1569224879260}"
```

It happens again, and for this time i think i know the cause: the ETA time is the time at which I restarted the queues, ie 27 minutes back from screenshot i was restarting the process. 
The task can be sent with 3m and 20m delay, and has min/max backoff of 10/60 minutes, so other tasks match the assumption.

Restart is doing by systemd, below part of `worker-transfers.sevice` config:
```
[Unit]
Description=transfers queue worker
PartOf=worker.service
After=worker.service

[Service]
Type=simple
WorkingDirectory=/opt/app
Environment=APPID=worker-transfers
ExecStart=/bin/pipenv run dramatiq -Q transfers -p 1 tasks
ExecReload=/bin/kill -s HUP $MAINPID
ExecStop=/bin/kill -s TERM $MAINPID
KillMode=process
Restart=on-failure
User=root
Group=root
RestartSec=42s

[Install]
WantedBy=worker.service
```

Content of root service `worker.service` (used to group several workers together for simpler management)
```
[Unit]
Description=queue workers

[Service]
Type=oneshot
ExecStart=/bin/true
# This service shall be considered active after start
RemainAfterExit=yes

[Install]
# Components of this application should be started at boot time
WantedBy=multi-user.target
```

I restart processes using `systemctl restart worker`

**Comment by Bogdanp** [comment]
Any chance you could create a minimal example that reproduces this? I can't think of a reason why this would happen and I can't repro. it locally.

>  1) "105616d3-9d0f-4dee-802d-85e29830d517"

Are you saying you encountered the same issue with this specific message as well?

Despite the errors, do the messages eventually get processed if you run the worker for long enough? That might point to some issue with ack-handling.

**Comment by metheoryt** [comment]
fresh example:
![image](https://user-images.githubusercontent.com/6823542/67006318-ad3c0380-f106-11e9-954f-7487592fdd26.png)
![image](https://user-images.githubusercontent.com/6823542/67006850-e4f77b00-f107-11e9-8386-69ac046f5c75.png)
![image](https://user-images.githubusercontent.com/6823542/67006879-f17bd380-f107-11e9-9711-dd83ef583b02.png)

The worker does not seem to be overloaded with the tasks, if task is stuck, it stuck forever, some of  them are haven't been processed even once.

And again, i was restarting processes somewhere in that time.

`105616d3-9d0f-4dee-802d-85e29830d517` it's just an example, when it occurs it occurs on bunch of tasks, and every time i need to delete and requeue all the stuck tasks. I'll try to reproduce this but I don't think that I will succeed. I see that the problem somewhere in delayed tasks & restarted process, may be in centos and redis, but that's all i know.

**Comment by metheoryt** [comment]
seems that all tasks, that have been delayed in this queue, hung up at the moment of restart, even those which eta has been in future.

**Comment by synweap15** [comment]
I have a similar issue using Redis broker, however my setup is managed with supervisord and the workers are assigned to two queues. I have 12 instances of dramatiq running on 12 servers, each instance on each server consumes tasks from "default" and from server-specific queue.

In the deployment routine upon pulling code changes, the workers are reloaded by sending a HUP signal.

However after running for a while, it seems that some workers start to drop / omit _some_ of the tasks. After forced restart of the workers, it seems some of the tasks are being picked up (the non-delayed ones), the delayed ones however get lost in limbo (or at least don't get picked up - I have to dig into this).

I've observed it on Dramatiq 1.3.0, but it occurs on 1.6.1 as well.

**Comment by Bogdanp** [comment]
I've tried to reproduce this again today and I'm unable to do it locally. Please try turning on verbose logging (`-v` flag) and post your logs here when this occurs again. 

The one thing I can think of is that during shutdown, workers requeue their pulled-but-not-processed messages, so maybe something is going wrong there, but even then, the unprocessed messages should get released eventually when the new workers decide the old/stopped ones have timed out so this is pretty bizarre.

**Comment by metheoryt** [comment]
seems that changing queue name solved the issue, i don't face it anymore

**Comment by metheoryt** [comment]
OK I found the root problem - my worker processes being killed by **systemd** when calling `systemctl stop {worker service}`.

`ExecStop=/bin/kill -s TERM $MAINPID` 

`bin/kill` is asynchronous call but systemd requires a synchronous way to stop service. When stopper process is finished but service process is still alive systemd sends SIGKILL to the process.
So it's enough to remove `ExecStop` line to trigger systemd's default stop behaviour, when it sends SIGTERM to the process by itself, waits for service gracefully stops and kills the process only after some timeout.

But there is no way to call reload synchronously, as [systemd manpage](https://www.freedesktop.org/software/systemd/man/systemd.service.html#ExecReload=) recommends.

**Comment by mwek** [comment]
We still encounter the same issue with Redis broker on Dramatiq 1.10. None of the processes gets terminated on our end.
Looking at the [PythonParser](https://github.com/andymccurdy/redis-py/blob/1a41cfd95a53a95b078084d8627be6b6fba3bb71/redis/connection.py#L319-L362), there is an option when a `None` is returned for bulk and/or multi-bulk responses. I will try installing `hiredis` to see whether this fixes the issue.

For the record, this is the stack trace:
```
[2021-04-07 08:44:15,881] [PID 9] [Thread-3] [dramatiq.worker.ConsumerThread(default.DQ)] [CRITICAL] Consumer encountered an unexpected error.
Traceback (most recent call last):
  File "/opt/virtualenv/lib/python3.7/site-packages/dramatiq/worker.py", line 259, in run
    for message in self.consumer:
  File "/opt/virtualenv/lib/python3.7/site-packages/dramatiq/brokers/redis.py", line 343, in __next__
    message = Message.decode(data)
  File "/opt/virtualenv/lib/python3.7/site-packages/dramatiq/message.py", line 96, in decode
    return cls(**global_encoder.decode(data))
  File "/opt/virtualenv/lib/python3.7/site-packages/dramatiq/encoder.py", line 52, in decode
    return json.loads(data.decode("utf-8"))
AttributeError: 'NoneType' object has no attribute 'decode'
```
