### ISSUE TITLE
Broker not overridable with `broker` argument

### ISSUE THREAD

**Issue by Qu4tro** [Bogdanp/dramatiq#226]
Hey there.

# Issues

I'm trying to specify a broker via the actor specific `broker` argument, but it seems it's ignored in lieu of the broker set in `.set_broker`.

I've setup a repo with a minimal example, that can be checked with a simple `docker-compose up`.
To have the example working, the only thing that is needed is to uncomment the `set_broker` line.
```
# FILE: actor.py (line 20)
# dramatiq.broker.set_broker(broker1)
```
https://github.com/qu4tro/dramatiq_bug_report

To be clear, my endgoal is to have `dramatiq` working with multiple brokers.

## Checklist

* [X] Does your title concisely summarize the problem?
* [X] Did you include a minimal, reproducible example?
* [X] What OS are you using?
* [X] What version of Dramatiq are you using?
* [X] What did you do?
* [X] What did you expect would happen?
* [X] What happened?

## What OS are you using?

Docker Example - Debian Stretch

## What version of Dramatiq are you using?

Docker Example - Latest release on pypi (1.6.1)
But I'm sure this can be replicated since at least `1.3`

## What did you do?

I've created a new broker and passed it along to both the `actor` decorator and to a `genericActor` that represent the `count_words` example.

## What did you expect would happen?

For `count_words` actors to receive the initial messages.

## What happened?

Nothing. (the actor isn't really binded to the broker)

**Comment by Qu4tro** [comment]
I forgot the actual repo link. Apologies, must be Monday somewhere:
https://github.com/qu4tro/dramatiq_bug_report

Will edit parent to include it as well.

**Comment by Bogdanp** [comment]
@Qu4tro the repo seems to be gone.  Did you figure this out?

**Comment by Qu4tro** [comment]
Apologies @Bogdanp . It was set as private. It's public now.

**Comment by Bogdanp** [comment]
I sent you a pull request that fixes the issue: https://github.com/Qu4tro/dramatiq_bug_report/pull/1 .

Quoting the fix here for posterity:

> Unless you tell dramatiq which broker to use, it'll try to load the global broker (which is why calling set_broker(broker1) works just fine). The fix is to explicitly tell dramatiq which broker you want to use for a particular set of workers.

```diff
- ENTRYPOINT ["/usr/local/bin/dramatiq", "actor"]
+ ENTRYPOINT ["/usr/local/bin/dramatiq", "actor:broker1"]
```

**Comment by Qu4tro** [comment]
Hey, yes - that works.

I've realized that my use-case is more akin to #214. I was implementing different actors with different queues.

Thanks for the help.
