### ISSUE TITLE
Feature: Health check

### ISSUE THREAD

**Issue by douglasmiranda** [Bogdanp/dramatiq#229]
What would be the appropriate way of checking a Dramatiq worker health?

I see no cli option like that, so I tried to look at the code in order to understand how that would be for Dramatiq.

- `dramatiq.workers.Worker` as far as I can see we don't have something to gather info of a running container, right?

- Looking in middlewares, I can see we have [after_worker_boot](https://dramatiq.io/reference.html#dramatiq.Middleware.after_worker_boot), which is nice, we can do something if a worker booted successfully.

I went further and found `dramatiq.middleware.prometheus.Prometheus`, and since the metrics are available at localhost:9191 `after_process_boot`, I think I can safely use that endpoint as a health check because it won't be up if the worker didn't finish booting right?

---

Now I'm thinking, for **dramatiq** itself it would be nice to check that with a cli option, (maybe an HTTP endpoint too?). But for **django_dramatic** definitely an HTTP endpoint.

---

For Celery I was doing like this: `celery inspect ping -A my.app -d celery@$HOSTNAME`.
For Redis: `test $(redis-cli ping) || exit 1`
For Postgres: `pg_isready -U postgres`

I'm deploying in Docker Swarm with `docker stack`.

**Comment by Bogdanp** [comment]
> I went further and found dramatiq.middleware.prometheus.Prometheus, and since the metrics are available at localhost:9191 after_process_boot, I think I can safely use that endpoint as a health check because it won't be up if the worker didn't finish booting right?

Either that or a custom middleware that does roughly the same kind of thing would be appropriate.

I don't think this deserves its own command line flag since adding the exact functionality you need yourself is fairly easy with middleware and will become even easier once the functionality described in #127 is in place.
