### ISSUE TITLE
Any suggestion to separate client and server code 

### ISSUE THREAD

**Issue by yyscamper** [Bogdanp/dramatiq#231]
We have a repo hosted the source code of a lot of workers, these workers are deployed onto server and ready to receive message and process it. For example:

- send_sms: the worker to send text message to user's phone
- send_slack:  the worker to send message to developer's slack channel
- clear_cache: clear all cache after a data table is changed

On the other hand, we have a lot of services which relay on  these workers. For example, the Login service may relay on send_sms worker to send the password reset link to user.

Below is the sample code of send_sms worker, it depends on a 3rd library

```python
import some_sms_lib

@dramatiq.actor
def send_sms(msg):
    some_sms_lib.send(msg)
```

The Login service trigger the worker by following code:

```python
from my_workers import send_sms

send_sms.send('some text')
```

Since Login service doesn't do the actually job of sending text message, so the 3rd library `some_sms_lib` is not required, but if I want to share the code, I have to install it for Login service, otherwise ImportError is raised.

I wonder if there is any best practice to separate this kind of client and server code. My expectation is to remove all unnecessary 3rd library in client side, keep the client side as simple as possible.

Thanks.

**Comment by Bogdanp** [comment]
The only way around this currently is to create and enqueue your [messages](https://dramatiq.io/reference.html#dramatiq.Message) manually.

So, from the client end, you would do

```python
broker.send(Message(
  queue_name="default",
  actor_name="send_sms",
  args=("hello",), 
  kwargs={}, 
  options={},
))
```

instead of 

```python
send_sms.send("hello")
```

**Comment by CapedHero** [comment]
Today I encountered the very same challenge of avoiding unnecessary dependencies in callers of my Dramatiq actors.

My solution to this is creating a headers file for the actors:
```python
# src/
# ├── actors.py
# ├── actors_headers.py

#############
# actors.py #
#############

import dramatiq
import x, y, z, tons, of, other, dependencies

from .broker import configure_broker()


logging.config.dictConfig(config.DICT_CONFIG)

configure_broker()


@dramatiq.actor
def test_dramatiq(arg1, kwarg1):
    # Call some business logic.


#####################
# actors_headers.py #
#####################

import dramatiq

from .broker import configure_broker()


configure_broker()


@dramatiq.actor
def test_dramatiq(arg1, kwarg1):
    ...

```

As this issue seems to be fairly common and important, maybe it is worth to add some patterns, ideas or simply recommended solutions in the docs?

**Comment by CapedHero** [comment]
Referring to @Bogdanp solution, I use the snippet below to avoid depending on `dramatiq` in the client code:

```python
import json
from time import time
from typing import NamedTuple
from uuid import uuid4


class DramatiqActorMessage(NamedTuple):
    """
    Helper class that refers to https://dramatiq.io/reference.html#dramatiq.Message.

    The goal is to communicate effectively with Dramatiq actors, while avoiding
    unnecessary dependencies.

    How to use
    ==========
    This class can be simply copied to the target codebase and then be used like
    in the example below:
    >>> dramatiq_actor_message = DramatiqActorMessage.create(
            queue_name=DRAMATIQ_QUEUE,
            actor_name="actor_name",
            args=tuple([arg1, arg2]),
            kwargs={},
            options={},
        )
    >>> rabbit_channel.basic_publish(
            exchange="",
            routing_key=DRAMATIQ_QUEUE,
            body=dramatiq_actor_message.encode()
        )
    """

    queue_name: str
    actor_name: str
    args: tuple
    kwargs: dict
    options: dict
    message_id: str
    message_timestamp: int

    @classmethod
    def create(
        cls, queue_name: str, actor_name: str, args: tuple, kwargs: dict, options: dict,
    ):
        message_id: str = str(uuid4())
        message_timestamp: int = int(time() * 1_000)
        return cls(queue_name, actor_name, args, kwargs, options, message_id, message_timestamp)

    def encode(self):
        data_dict = self._asdict()
        data_json = json.dumps(data_dict, separators=(",", ":"))
        encoded_data_json = data_json.encode("utf-8")
        return encoded_data_json

```
