### ISSUE TITLE
Is actors priority about queue or about workers?

### ISSUE THREAD

**Issue by Sovetnikov** [Bogdanp/dramatiq#232]
From a dramatiq.actor decorator documentation https://dramatiq.io/reference.html#actors-messages
> priority (int) – The actor’s global priority. If two tasks have been pulled on a worker concurrently and one has a higher priority than the other then it will be processed first. Lower numbers represent higher priorities.

It is not clear to me how priority is supposed to work.

Is high priority task will be pulled from queue first or workers will prefetch few tasks from queue and only if high priority task is in prefetched list then priority taken into account?

If queue already has lots of tasks, is new high priority task submitted to queue will be processed first or it will wait until all tasks prefetched by workers?

Most interesting how this works with redis broker.

**Comment by Sovetnikov** [comment]
Just get the answer in source code. In case of redis broker priority only matters when pack of tasks fetched by concrete worker process or thread where tasks are consumed in priority queue.

If 100 low priority tasks passed in redis task queue and then one high priority task passed to same queue then all depends on how tasks are fetched by workers.

In case dramatiq_queue_prefetch set to value more than 100 then high priority task is fetched and executed in priority.
If dramatiq_queue_prefetch is set to some low values, then high priority task will stay in queue unless tasks that enqueued earlier are fetched.

Some clarifications in the documentation about that would help.

**Comment by Sovetnikov** [comment]
Seems there is no reliable solution for redis and tasks prioritization at now with dramatiq.
One may have separate queues per priority and submit high priority tasks to high priority queues.
But order of tasks consumed from queues in single worker is unknown.
Each worker process has one consumer thread per queue and in my tests with single worker and dramatiq_queue_prefetch=1 messages from different queues is fetched almost in same order as they enqueued.

**Comment by Sovetnikov** [comment]
Just made fork with support for priority queues in RedisBroker based on ZSET https://github.com/Sovetnikov/dramatiq
Will test it in production

**Comment by aberres** [comment]
Just stumbled upon the very same issue. While closed, I think it is still relevant.

I have some long running tasks (several minutes) which are automatically triggered. Now it can happen that a user manually enqueues an additional job - obviously this one should have a higher priority.
As not all messages are this high priority message won't be precessed with high priority though.

@Sovetnikov How is your solution performing in practice?

@Bogdanp Would it be feasible to switch to a ZSET based queue implementation? If I am not mistaken, this is @Sovetnikov 's actual commit implementing this: https://github.com/Sovetnikov/dramatiq/commit/1c6b0784a2e141d25410e00ea6ad52bbc7b086ea

**Comment by Sovetnikov** [comment]
@aberres using my fork in production for about an year and have no problems with ZSET

But my fork has a bug that causes workers restart periodically with strange empty messages comes from consumer ... i think it can be fixed easily by checking for None on Message decoding.
But i still cant get time to to find the root cause and fix it, and merge with latest commits in dramatiq into my fork.

btw error stack trace is
```
TypeError: a bytes-like object is required, not 'NoneType'
  File "dramatiq/worker.py", line 258, in run
    for message in self.consumer:
  File "dramatiq/brokers/redis.py", line 324, in __next__
    message = Message.decode(data)
  File "dramatiq/message.py", line 96, in decode
    return cls(**global_encoder.decode(data))
```

**Comment by Sovetnikov** [comment]
@aberres just investigated my error, and i got this situation because bad data (empty message) get into redis storage and cant get out of it because code does not check for it and message flowing to acks storage, then back to queue for fetching, and back to acks ...
Just dropped that empty messages and all working fine

**Comment by aberres** [comment]
@Sovetnikov Great, thanks for the feedback.

I'd love to hear @Bogdanp's feedback regarding the ZSET approach and if it is not feasible to be upstreamed I definitely will test your code 👍🏼
