### ISSUE TITLE
get_result never return

### ISSUE THREAD

**Issue by yinrong** [Bogdanp/dramatiq#234]
I'm sure actor success return which I know from my logging.
But the process hangs at get_result. How do I debug?

Currently, I have to restart the process over and over and hope I can success one time. 

@Bogdanp

**Comment by yyscamper** [comment]
You can check whether `store_results=True` is applied in your actor, otherwise no result is stored, and `get_result` is blocked way will hang.

```python
@actor(store_results=True)
def add(a, b):
  return a + b
```

**Comment by yinrong** [comment]
I have solved this problem. The cause is: 1. actor busy processing other workload 2.  message timed-out 3. this exception happens.

it seems the default config and message is confusing.

**Comment by yinrong** [comment]
Among many logs (a lot of workload is going on), there often some logs like this, which I can NOT trace what is going wrong. I'm very concerned.

```
[2019-10-28 12:27:10,179] [PID 32316] [Thread-3] [dramatiq.worker.ConsumerThread(default)] [CRITICAL] Consumer encountered an unexpected error.
Traceback (most recent call last):
  File "/home/yinrong/.sw/conda/lib/python3.7/site-packages/dramatiq/worker.py", line 253, in run
    for message in self.consumer:
  File "/home/yinrong/.sw/conda/lib/python3.7/site-packages/dramatiq/brokers/redis.py", line 318, in __next__
    message = Message.decode(data)
  File "/home/yinrong/.sw/conda/lib/python3.7/site-packages/dramatiq/message.py", line 96, in decode
    return cls(**global_encoder.decode(data))
  File "/home/yinrong/.sw/conda/lib/python3.7/site-packages/dramatiq/encoder.py", line 52, in decode
    return json.loads(data.decode("utf-8"))
AttributeError: 'NoneType' object has no attribute 'decode'
```

**Comment by yinrong** [comment]
in my main script, I send 35330 messages, get_result success return 35245, but 85 results remain missing. among 200 workers, `it's really hard to find out where is the problem`.

at the top level of the actor, I use try except and save the exception in mongodb but fail to catch any exception..

**Comment by Bogdanp** [comment]
> Among many logs (a lot of workload is going on), there often some logs like this, which I can NOT trace what is going wrong. I'm very concerned.

It seems like this might be related to #224. Try turning on verbose loggging (`-v` flag) and post your logs in that issue when this happens again.
