### ISSUE TITLE
Postgres backend

### ISSUE THREAD

**Issue by skorokithakis** [Bogdanp/dramatiq#237]
Newer postgres versions include some features which make it very attractive as a task broker. Is there any intent on adding a postgres broker backend?

**Comment by Bogdanp** [comment]
Hi @skorokithakis, @bersace has released a custom broker for Postgres called [dramatiq-pg](https://gitlab.com/dalibo/dramatiq-pg/blob/master/docs/index.rst) a while back.

**Comment by skorokithakis** [comment]
Oh fantastic, thanks!
