### ISSUE TITLE
Async/await

### ISSUE THREAD

**Issue by peterdeme** [Bogdanp/dramatiq#238]
Hello guys. Just a question. Is there any reason why there's no async support for actors?

**Comment by Bogdanp** [comment]
Unlikely to ever happen. I'm [not a fan](https://news.ycombinator.com/item?id=18110319) of asyncio as done in Python.

**Comment by peterdeme** [comment]
I’m a bit confused why you are so against it because that can be implemented in a backward compatible way.

```python
if type(actor) is Coroutine:
    loop = asyncio.get_event_loop()
    loop.run_until_finished(actor())
else:
    result = actor()
```

this alone would be a huge improvement to your library for anyone who uses async ORMs or async HTTP libs.

**Comment by rafalp** [comment]
Increasing number of codebases and python libraries adapt asyncio. Currently its possible to use Dramatiq and Celery with those by wrapping one's tasks with asgi_ref's `async_to_sync`, but it would be nice if this boilerplate lived in the task runner instead.

**Comment by levrik** [comment]
I agree. We're using GraphQL subscriptions with Ariadne framework which requires `asyncio` and thus `asyncio`-ready libraries. Now we want to push additional events from our background jobs to a Redis channel so a GraphQL subscription can push this to the user in realtime. This needs the use of an async Redis client which doesn't work in Dramatiq if we don't wrap all our jobs in the workaround posted by @peterdeme above.
The other option is to use the plain sync `redis` client but I don't really want to pull in 2 different libraries into one application.

**Comment by Bogdanp** [comment]
Anybody is welcome to try and contribute this. If it truly ends up not being complicated, it will get merged. On the worker side, I agree that it'll likely be about as simple as @peterdeme points out. On the enqueueing side, it doesn't seem possible except by cooperating with some sort of thread pool (either provided by the user or by bringing our own).

**Comment by giuliotosato** [comment]
any news?

**Comment by levrik** [comment]
@giuliotosato You can just define async actors since `1.15.0` (https://github.com/Bogdanp/dramatiq/releases/tag/v1.15.0) release in October 2023.
