### ISSUE TITLE
StubBroker doesn't clear dead letter queue

### ISSUE THREAD

**Issue by CapedHero** [Bogdanp/dramatiq#243]
## What OS are you using?

macOS 10.15.1 (19B88)

## What version of Dramatiq are you using?

1.7.0

## What did you do?

```python
import pytest

import dramatiq
from dramatiq.brokers.stub import StubBroker
from dramatiq.middleware import Prometheus


broker = StubBroker()

for middleware in broker.middleware:
    if isinstance(middleware, Prometheus):
        broker.middleware.remove(middleware)

dramatiq.set_broker(broker)


##########
# ACTORS #
##########


@dramatiq.actor(max_retries=0)
def actor_foo():
    raise ValueError("foo")


@dramatiq.actor(max_retries=0)
def actor_bar():
    raise AttributeError("bar")


#########
# TESTS #
#########


@pytest.fixture
def stub_broker():
    broker: StubBroker = dramatiq.get_broker()
    broker.flush_all()

    worker = dramatiq.Worker(broker, worker_timeout=1)
    worker.start()

    yield broker

    worker.stop()


def test_actor_foo(stub_broker):
    actor_foo.send()
    with pytest.raises(ValueError):
        stub_broker.join(actor_foo.queue_name, fail_fast=True)


def test_actor_bar(stub_broker):
    actor_bar.send()
    with pytest.raises(AttributeError):
        stub_broker.join(actor_bar.queue_name, fail_fast=True)

```

## What did you expect would happen?

The tests should have passed.

## What happened?

`test_actor_bar` fails, as it raises `ValueError` instead of `AttributeError`.

## Probable Cause

+ `StubBroker` does not clear dead letter queue in `flush_all` method.
+ If `fail_fast=True` is set, `StubBroker` in `join` method re-raises exceptions from all dead letters. And as there is the dead letter from the previous test, the next test sees completely different exception raised than expected.

## Proposed solution

Add `self.dead_letters_by_queue.clear()` to `flush_all` method.

**Comment by Bogdanp** [comment]
Your proposed solution seems sensible. If you make a PR, I'll merge it. Make sure to add a test for this if you do!

**Comment by CapedHero** [comment]
@Bogdanp #247 :)
