### ISSUE TITLE
Explicit prefetch by worker

### ISSUE THREAD

**Issue by evstratbg** [Bogdanp/dramatiq#245]
Now, It's not possible to pass prefetch kwarg in Worker class. It may be necessary for the developer/devops to test or something else.

If so, I can code it @Bogdanp

**Comment by Bogdanp** [comment]
It is possible via an environment variable: https://github.com/Bogdanp/dramatiq/blob/master/dramatiq/worker.py#L40

For the purposes you mentioned, I think that would be enough.

**Comment by evstratbg** [comment]
Don't you think it's more convenient to pass via CLI?

**Comment by Bogdanp** [comment]
I think they're roughly the same as far as convenience goes.  Since it's not something that is commonly asked for, I don't think it's worth the additional complexity to thread a parameter through for this.

**Comment by evstratbg** [comment]
got it, thanks
