### ISSUE TITLE
How to access the task instance?

### ISSUE THREAD

**Issue by saschametz** [Bogdanp/dramatiq#246]
How can I access the task instance in this example?
```
@dramatiq.actor
def count_words():
    print("count_words")
```

For example celery provides the task instance if you pass [`bind=True`](https://docs.celeryproject.org/en/latest/userguide/tasks.html#example)

**Comment by Bogdanp** [comment]
You need to add the `CurrentMessage` middleware to your broker and then user it.

https://github.com/Bogdanp/dramatiq/blob/master/dramatiq/middleware/current_message.py#L23

**Comment by saschametz** [comment]
Ah perfect, I didn't find that. Thank you very much.
