### ISSUE TITLE
Performance comparison with RQ, Celery and redis blpop

### ISSUE THREAD

**Issue by benjaminweb** [Bogdanp/dramatiq#25]
Hi, how does dramatiq compare against RQ, Celery and redis blocking list pop and possibly others?

I implemented some RQ some time ago and got rid of it in favour of a simpler and much more performant solution: redis blocking list pop.

**Comment by Bogdanp** [comment]
Generally speaking, Dramatiq is slightly faster than Celery and much faster than RQ. You can clone this repo and run the code in the `benchmarks` folder yourself if you want to compare it to Celery (and, with a little bit of work, RQ).

As far as throughput goes, it's unlikely that Dramatiq will ever be a bottleneck for whatever you want to do. Re. `blpop`: Dramatiq's Redis broker has to do some extra book-keeping in lua so it can't use `brpoplpush`. Instead it uses the non-blocking version, `rpoplpush`.
