### ISSUE TITLE
TypeError: Object of type function is not JSON serializable

### ISSUE THREAD

**Issue by sauravmahuri2007** [Bogdanp/dramatiq#250]
# Issues

GitHub issues are for bugs.  If you have questions, please ask them on the [discussion board](https://reddit.com/r/dramatiq).

## Checklist

* [*] Does your title concisely summarize the problem?
* [*] Did you include a minimal, reproducible example?
* [*] What OS are you using?
* [*] What version of Dramatiq are you using?
* [*] What did you do?
* [*] What did you expect would happen?
* [*] What happened?

## What OS are you using?
Windows 10 and Ubuntu 18.04 LTS

## What version of Dramatiq are you using?
1.7.0

## What did you do?
I'm trying to implement something like **enqueue** functionality available in **rq** as we're using **rq** but migrating to some Task Queue which is supported for Windows. **Huey** and **dramatiq** was the best option for us but **Huey** had some limitation as per our code so **dramatiq** was a perfect fit. There are many places where we're using following code to execute task asynchronously using **rq**:

```
from django_rq import get_queue
default_queue = get_queue()
job = default_queue.enqueue(my_heavy_func, *args, **kwargs)
```

There are many other places we're using different functions in similar fashion. Instead of moving all existing function to tasks.py and decorating it to as `@dramatiq.actor` we decided to do something like this:

```
import dramatiq
@dramatiq.actor
def dram_queue(func, *args, **kwargs):
     return func(*args, **kwargs)

msg = dram_queue.send(my_heavy_func, *args, **kwargs)
```

But it is raising exception: `TypeError: Object of type function is not JSON serializable`

Though I was able to implement same functionality in **huey** thought it could be possible in **dramatiq**:

```
from huey.contrib.djhuey import task
@task
def huey_queue(func, *args, **kwargs):
    return func(*args, **kwargs)

task = huey_queue(my_heavy_func, *args, **kwargs)
```

**I also tried to use borker.enqueue() function but it always raise ActorNotFound**

```
import dramatiq
broker = dramatiq.get_broker()

def dr_enqueue(func, *args, **kwargs):
    actor = dramatiq.Actor(func,
                           broker=broker, actor_name=func.__name__,
                           queue_name='default', priority=0, options={})
    msg = dramatiq.Message(
        queue_name='default',
        actor_name=func.__name__,
        args=args,
        kwargs=kwargs,
        options={}
    )
    msg = broker.enqueue(msg)
    return msg

msg = dr_enqueue(my_heavy_func, *args, **kwargs)  # Raises ActorNotFound exception
```

**Exception:**
```
[PID 860] [Thread-7] [dramatiq.worker.ConsumerThread(default)] [ERROR] Received message for undefined actor 'my_heavy_func'. Moving it to the DLQ.
Traceback (most recent call last):
  File "c:\users\XXX\venv\lib\site-packages\dramatiq\worker.py", line 314, in handle_message
    actor = self.broker.get_actor(message.actor_name)
  File "c:\users\XXX\venv\lib\site-packages\dramatiq\broker.py", line 214, in get_actor
    raise ActorNotFound(actor_name) from None
dramatiq.errors.ActorNotFound: my_heavy_func
```

## What did you expect would happen?
I may not have followed the correct procedures or might be missing something. I'm not sure how can I achieve this without doing a lot of code changes.

## What happened?
I've mentioned in **What did you do** section.

**Comment by Bogdanp** [comment]
Your first example should work if you switch to the [PickleEncoder](https://dramatiq.io/reference.html#dramatiq.PickleEncoder).
