### ISSUE TITLE
TypeError: Object of type time is not JSON serializable

### ISSUE THREAD

**Issue by baloda** [Bogdanp/dramatiq#251]
# Issues

GitHub issues are for bugs.  If you have questions, please ask them on the [discussion board](https://reddit.com/r/dramatiq).

## Checklist

* [x] Does your title concisely summarize the problem?
Yes,

* [x] Did you include a minimal, reproducible example?
Yes

* [x] What OS are you using?
MAC

* [x] What version of Dramatiq are you using?
latest

* [ ] What did you do?
i have sent named tuple(with time field) as input to actor

* [x] What did you expect would happen?

* [ ] What happened?
It produced a Type error

## What OS are you using?
macOS 10.13.3

## What version of Dramatiq are you using?
1.7.0

## What did you do?

I am passing a namedtuple:

Result(asset_id=1000004, asset_type='MOVIE', attribute_id=1000004, asset_title='*******', asset_pubish_time=None, owner='*****', sub_type='', tags='', content_id=1000004, content_title='1942 A Love Story', content_publish_time=None, mezz_catalog='****', mezz_file_path='******', content_short_description=None, content_release_date=None, duration=datetime.time(2, 37, 57), ctags=None, track_number=1, episode_number=0, seasion_id=None, season_title=None, season_number=None, asset_blocked_location=['BT', 'IN', 'NP'], asset_allowed_location=['WW'])

## What did you expect would happen?
It should take that time field in JSON or named tuple

class JSONEncoder(Encoder):
    """Encodes messages as JSON.  This is the default encoder.
    """

    def encode(self, data: MessageData) -> bytes:
        return json.dumps(data, separators=(",", ":")).encode("utf-8")

    def decode(self, data: bytes) -> MessageData:
        return json.loads(data.decode("utf-8"))

it should be like this:

from django.core.serializers.json import DjangoJSONEncoder

class JSONEncoder(Encoder):
    """Encodes messages as JSON.  This is the default encoder.
    """

    def encode(self, data: MessageData) -> bytes:
        return json.dumps(data, separators=(",", ":"), **cls=DjangoJSONEncoder**).encode("utf-8")

    def decode(self, data: bytes) -> MessageData:
        return json.loads(data.decode("utf-8"))

## What happened?
It is raising Type Error:
"/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type time is not JSON serializable

**Comment by Bogdanp** [comment]
I don't understand the issue. Did you call `set_encoder` with your custom encoder?

**Comment by baloda** [comment]
I don't understand the issue.

Ok, no issue. 
so what I am trying to do is, passing a {'duration': datetime.time(2, 37, 57)} variable in dramtiq actor. 

if i do this. it throws Error similar to this: 
 File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type time is not JSON serializable



For set_encoder,it is my question:
cant we do some change JSONEncoder class of dramatiq/encoder.py 
return json.dumps(data, separators=(",", ":"), **cls=DjangoJSONEncoder**).encode("utf-8")
because i tried it and it solves the problem

**Comment by Bogdanp** [comment]
I wouldn't want to depend on django and I think it'd be surprising if the library did this. These kinds of use cases are why the library lets you plug in your own encoder.
