### ISSUE TITLE
'Prometheus' object has no attribute 'total_retried_messages'

### ISSUE THREAD

**Issue by metheoryt** [Bogdanp/dramatiq#253]
Hi, I've faced exception in Prometheus middleware. It creates `total_retried_messages` attribute in `after_process_boot` handler, and calls it in `after_enqueue` handler. 
Seems that dramatiq can call `after_enqueue` on middleware before `after_process_boot`.

dramatiq 1.7.0
CentOS 7

**Comment by metheoryt** [comment]
By the way it would be great if you supply base middleware class (and/or docs) with information on task workflow - which event comes after which, when it should be executed and when shouldn't. I am personally have problems with understanding of this.

**Comment by Bogdanp** [comment]
>  Seems that dramatiq can call after_enqueue on middleware before after_process_boot.

Are you enqueueing messages from the top level of any of your modules? That's the only what I think that that could happen and it's something I hadn't considered when designing the hooks. 

I'm afraid I don't really have time right now to document the hook flow.  An easy way to find all the hooks is to grep for `emit_` in the codebase.

**Comment by caramdache** [comment]
I'm also having an issue with `total_retried_messages`. I'm trying to use `joeflow` with `dramatiq` and here is the stack trace:

```
2022-08-10 09:32:05,137 CRITICAL Unexpected failure in after_enqueue of <dramatiq.middleware.prometheus.Prometheus object at 0x7f50d3c33a90>.
Traceback (most recent call last):
  File ".../python3.9/site-packages/dramatiq/broker.py", line 98, in emit_after
    getattr(middleware, "after_" + signal)(self, *args, **kwargs)
  File ".../python3.9/site-packages/dramatiq/middleware/prometheus.py", line 127, in after_enqueue
    self.total_retried_messages.labels(*labels).inc()
AttributeError: 'Prometheus' object has no attribute 'total_retried_messages'
```
