### ISSUE TITLE
queue a task from PHP 

### ISSUE THREAD

**Issue by vkatochka** [Bogdanp/dramatiq#256]
Hi
Is there some way to queue a task from PHP directly? Or, over HTTP? Or, in another way?

**Comment by Bogdanp** [comment]
See [this section of the docs](https://dramatiq.io/advanced.html#enqueueing-messages-from-other-languages).

**Comment by vkatochka** [comment]
In addition to queuing, there is a need to wait until the worker's completion, and get the result of his work. Is it possible?

**Comment by Bogdanp** [comment]
See:

* https://dramatiq.io/reference.html#results and the Redis backend implementation
* https://github.com/Bogdanp/dramatiq/blob/master/dramatiq/rate_limits/backends/redis.py

**Comment by vkatochka** [comment]
> HSET "dramatiq:default.msgs" "UIDtest1" '{"queue_name":"default","actor_name":"tsof","args":["5"],"kwargs":{},"options":{},"message_id":"UIDtest1","message_timestamp":1578067301510}'  

> RPUSH dramatiq:default UIDtest1  
~~~
{
	"queue_name":"default",
	"actor_name":"tsof",
	"args":["5"],
	"kwargs":{},
	"options":{},
	"message_id":"UIDtest1",
	"message_timestamp":1578067301510
}
~~~


In documentation says: "options" - Arbitrary options that are used by middleware. Leave this empty. But I got error. In Redis, entries for this message have not been deleted.  
~~~
Worker done. Result: there are 1 chars at '5'.
[2020-01-03 18:23:04,108] [PID 27833] [Thread-5] [dramatiq.worker.ConsumerThread(default)] [ERROR] Unhandled error during post_process_message(tsof('5')).  You've found a bug in Dramatiq.  Please report it!
Although your message has been processed, it will be processed again once this worker is restarted.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/dramatiq/worker.py", line 341, in post_process_message
    self.consumer.ack(message)
  File "/usr/local/lib/python3.6/dist-packages/dramatiq/brokers/redis.py", line 284, in ack
    self.broker.do_ack(self.queue_name, message.options["redis_message_id"])
KeyError: 'redis_message_id'
~~~


demo.py
~~~
import sys
import time
import dramatiq
import dramatiq.brokers.redis

#
broker = dramatiq.brokers.redis.RedisBroker(host="127.0.0.1", port=6379, db=6)
dramatiq.set_broker(broker)

#
@dramatiq.actor
def tsof(text):
    count = len(text)
    time.sleep(3)
    print(f"Worker done. Result: there are {count} chars at {text!r}.")
    return count

#
if __name__ == '__main__':
    tsof.send(sys.argv[1])
~~~

**Comment by Bogdanp** [comment]
Ah, yeah, I suppose the docs are outdated with regards to Redis messages. Each individual redis message has to have a unique id in its `options`.

**Comment by vkatochka** [comment]
Is it enough to add the option “options.redis_message_id” with own generated unique value so that everything works correctly?

**Comment by Bogdanp** [comment]
Yes. See this code for details: https://github.com/Bogdanp/dramatiq/blob/master/dramatiq/brokers/redis.py#L156
