### ISSUE TITLE
How does rate limiting work?

### ISSUE THREAD

**Issue by saschametz** [Bogdanp/dramatiq#257]
I want to use a rate limiter to send a maximum of 10 emails per second because this is the limit I got from my mail provider.

From the docs I can see that I could the following rate limiter to solve this problem:
`BucketRateLimiter(backend, "send-email", limit=10, bucket=1_000)`
(or the alternative `WindowRateLimiter`)

I thought this would be the solution, but there is also this explanation in the docs how the rate limiting works: "This works by raising an exception and relying on the built-in Retries middleware to do the work of re-enqueueing the task."

Does this mean that if a task has a retry limit of 3 and can't aquire a lock three times it will be removed from the queue?

Celery also offers a rate limit for their tasks by using a Token bucket but they don't say something about that a task relies on the maximum retry number.

Does Celery has a different approach to rate limiting than dramatiq has?
I want to make sure that my tasks are executed and if I have set a maximum retries limit of 3 this would mean after failing to aquire a lock three times the task will just be dismissed.

**Comment by Bogdanp** [comment]
> Does this mean that if a task has a retry limit of 3 and can't aquire a lock three times it will be removed from the queue?

Yep, by default that is true. You  can opt out of that functionality and gain more control by adding `raise_on_failure=False` to the `acquire` call. For example:

```python
@dramatiq.actor
def send_email(recipient, body):
  with MY_RATE_LIMITER.acquire(raise_on_failure=False) as acquired:
     if not acquired:
       send_email.send(recipient, body)
       return

  # send the email
```

**Comment by xaero3** [comment]
What exactly happens in this example if the task isn't acquired?
