### ISSUE TITLE
[Redis broker] Error "user_script:90: too many results to unpack" causes worker to sit idle forever

### ISSUE THREAD

**Issue by benekastah** [Bogdanp/dramatiq#258]
## Checklist

* [x] Does your title concisely summarize the problem?
* [ ] Did you include a minimal, reproducible example?
* [x] What OS are you using?
* [x] What version of Dramatiq are you using?
* [x] What did you do?
* [x] What did you expect would happen?
* [x] What happened?

## What OS are you using?

Debian GNU/Linux 9.6 (stretch)

We are using the `python:3.7.1-stretch` Docker image, if that helps.

## What version of Dramatiq are you using?

1.7.0

## What did you do?

No particular action caused this. This seems to happen on its own after a while of running dramatiq in production. We are running 16 dramatiq workers at a time with 1 process and 32 threads each.

## What did you expect would happen?

I expected the dramatiq workers would process tasks indefinitely, or restart as the result of an error

## What happened?

The worker fails to fetch new tasks to run, but does not die, so it sits idle forever (or until I restart it myself). Over the course of a few days, this will eventually happen to enough workers that tasks start backing up in the queue and we experience problems visible to users of our application.

Here is the log line containing the stack trace:

```
[dramatiq] message="Consumer encountered an unexpected error.", exc_info="Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/dramatiq/brokers/redis.py", line 315, in __next__
    data = self.message_cache.pop(0)
IndexError: pop from empty list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/dramatiq/worker.py", line 253, in run
    for message in self.consumer:
  File "/usr/local/lib/python3.7/site-packages/dramatiq/brokers/redis.py", line 328, in __next__
    self.prefetch - self.message_refc,
  File "/usr/local/lib/python3.7/site-packages/dramatiq/brokers/redis.py", line 256, in do_dispatch
    return dispatch(args=args, keys=keys)
  File "/usr/local/lib/python3.7/site-packages/redis/client.py", line 2694, in __call__
    return client.evalsha(self.sha, len(keys), *args)
  File "/usr/local/lib/python3.7/site-packages/redis/client.py", line 1944, in evalsha
    return self.execute_command('EVALSHA', sha, numkeys, *keys_and_args)
  File "/usr/local/lib/python3.7/site-packages/redis/client.py", line 573, in execute_command
    return self.parse_response(connection, command_name, **options)
  File "/usr/local/lib/python3.7/site-packages/redis/client.py", line 585, in parse_response
    response = connection.read_response()
  File "/usr/local/lib/python3.7/site-packages/redis/connection.py", line 582, in read_response
    raise response
redis.exceptions.ResponseError: Error running script (call to f_605aad1746512fb86e8ee6fa6129dccdf32eed59): @user_script:90: user_script:90: too many results to unpack"
```

While it is possible that a different error causes the issue (or that multiple errors can cause the issue), I believe this is causing it because the exception raised is not a subclass of `redis.exceptions.ConnectionError`. Since only `ConnectionError`s trigger restarts in [`dramatiq.brokers.redis`](https://github.com/Bogdanp/dramatiq/blob/v1.7.0/dramatiq/brokers/redis.py#L341), I believe the worker never gets restarted.

I plan to assist in getting this fixed, but I figured I'd post this first to make sure I'm on the right track. I propose doing the following:

1. The function call on line 90 in [dispatch.lua](https://github.com/Bogdanp/dramatiq/blob/v1.7.0/dramatiq/brokers/redis/dispatch.lua#L90) should be fixed to push message ids in batches so we don't fill up lua's stack.
1. Restart the worker on any uncaught exception in `dramatiq.brokers.redis`.

**Comment by benekastah** [comment]
I haven't made a minimal reproduction case, but I'm working on it.

**Comment by Bogdanp** [comment]
Both of your proposals sound good to me.

**Comment by benekastah** [comment]
@Bogdanp I wasn't able to conclusively prove that this causes workers to hang forever (though it might). As I studied the code for workers, consumers and `_RedisConsumer`, I couldn't find any clear reason for the workers to hang. Perhaps since the `do_maintenance` branch always failed that could eventually cause my workers to hang somehow? Or perhaps the two errors were totally unrelated.

**Comment by Bogdanp** [comment]
The PRs related to this are now merged and will be released soon (my goal is by the end of the month). Thanks again for the work you did here. We'll re-open this if the problem persist after 1.8.

**Comment by avlm** [comment]
Hello! I'm using dramatiq 1.10 and I'm having this issue when trying to execute a task by directly posting a message on redis. It's a django project, my task runs on the default queue and what I'm trying to do is:

```python
r = redis.Redis(host='172.24.0.3', port=6379, db=0)
r.rpush("dramatiq:default", json.dumps({
    "queue_name": "default",
    "actor_name": "update_item",
    "args": [1],
    "kwargs": {},
    "options": {},
    "message_id": f'{uuid.uuid4()}',
    "message_timestamp": 0,
}))
```

`update_item` is the name of the task and the `1` argument is the object id in the database which is the only argument that this task receives.

apreciate any help to try to solve this. my plan with this is to call this task from a scrapy pipeline everytime an item is scraped.

thank you.
