### ISSUE TITLE
Add a way to manually requeue a Message without raising an exception

### ISSUE THREAD

**Issue by etienne-napoleone** [Bogdanp/dramatiq#265]
Thanks for making dramatiq!
I'm missing a way to requeue/retry a message without raising an exception. 
It can be handy in some situations where you need to wait on something external to be available.

In our case, we're waiting for a freshly deployed service to be available.

**Comment by Bogdanp** [comment]
You can combine the [`CurrentMessage`](https://dramatiq.io/reference.html#dramatiq.middleware.CurrentMessage) middleware with [`Broker.enqueue`](https://dramatiq.io/reference.html#dramatiq.Broker.enqueue):

```python
@dramatiq.actor
def an_actor(x):
  dramatiq.get_broker().enqueue(CurrentMessage.get_current_message())
```

**Comment by etienne-napoleone** [comment]
Oh thanks, maybe it could be added in the cookbook part of the docs?
(Or maybe I'm the only one who didn't get it ... ups :D)
