### ISSUE TITLE
Feature request: RabbitMQ as result backend (for Windows support)

### ISSUE THREAD

**Issue by lapseofreason** [Bogdanp/dramatiq#267]
It would be nice to use RabbitMQ as a result backend.

I've successfully used redis as a result backend on Linux, but none of the currently supported result backends (redis & memcached) are actively supported on Windows.

Celery has support for using RabbitMQ as a result backend, but it is not maintained on Windows any more since version 4, so dramatiq would be a good replacement for it.

Or maybe there are other ways to fetch results multiple platforms that I am not aware of?

**Comment by Bogdanp** [comment]
I don't intend to add a RMQ-based result backend to the core package. I think the result backend API should be enough for some enterprising person to do it themselves (in a separate package), though I wouldn't recommend it.

Redis should work just fine on Windows and you can install it via `chocolatey`. See our CI setup for Windows:

https://github.com/Bogdanp/dramatiq/blob/6dba9cab3b1eb9ad43166cff9ca7c52bd222ec9e/appveyor.yml#L18

**Comment by lapseofreason** [comment]
Thanks for the response!

redis on Windows is quite outdated (last update in 2016), so I'm not sure if this is a good option.

I guess I'll try dramatiq-pg and see if that works well on all platforms.
