### ISSUE TITLE
UniqueJobsMiddleware suggested in issue 32 fails unless send_with_options is used.

### ISSUE THREAD

**Issue by ScriptingDad** [Bogdanp/dramatiq#272]
# Issues

I have been looking at issue #32 and I like the middleware method you posted there but it fails if you provide the unique_job_key in the actor decorator as the options provided here aren't passed through to the message.  

## Checklist

* [x] Does your title concisely summarize the problem?
* [x] Did you include a minimal, reproducible example?
* [x] What OS are you using?
* [x] What version of Dramatiq are you using?
* [x] What did you do?
* [x] What did you expect would happen?
* [x] What happened?

## What OS are you using?

Windows 10 Enterprise => WSL (Ubuntu 18.04)

## What version of Dramatiq are you using?

1.7.0

## What did you do?

```python

class UniqueJobsMiddleware(dramatiq.Middleware):
    def __init__(self, backend):
        self.backend = backend

    @property
    def actor_options(self):
        return {"unique_job_key"}

    def before_process_message(self, broker, message):
        unique_job_key = message.options.get("unique_job_key")
        if unique_job_key is not None:
            acquired = self.get_rate_limiter(unique_job_key)._acquire()
            if not acquired:
                raise dramatiq.middleware.SkipMessage()

    def after_process_message(self, broker, message, *, result=None, exception=None):
        unique_job_key = message.options.get("unique_job_key")
        if unique_job_key is not None:
            self.get_rate_limiter(unique_job_key)._release()

    def get_rate_limiter(self, key):
        # Rate limiter objects are very cheap to create so this is not a concern.s
        return ConcurrentRateLimiter(self.backend, key, limit=1)


backend = RateLimitedRedis(url=Config.DRAMATIQ_BACKEND_URL)

broker = RabbitmqBroker(url=Config.DRAMATIQ_BROKER_URL)
broker.add_middleware(UniqueJobsMiddleware(backend=backend))

dramatiq.set_broker(broker)


@dramatiq.actor(max_retries=0, unique_job_key="unique")
def test_func(*args, **kwargs):
    print("Start")
    sleep(10)
    print("End")

# This won't use the UniqueJobsMiddleWare because unique_job_key 
# isn't passed on.
test_func.send()   

# This one works because the send_with_options 
# method only passes the options directly assigned to it.
test_func.send_with_options(unique_job_key="unique")
```

## What did you expect would happen?

I expected the UniqueJobMiddleware to drop additional commands till the lock was dropped.

## What happened?

All messages were queued and executed normally as though the middle ware didn't exist.

## Possible fix:

I tweaked the Actor method send_with_options to merge the options provided with the options stored at the class level.  

```python
def send_with_options(self, *, args=None, kwargs=None, delay=None, **options):
    ...
    if self.options:
        options = {**self.options, **options}
    message = self.message_with_options(args=args, kwargs=kwargs, **options)
    return self.broker.enqueue(message, delay=delay)
```

Which works with send or send_with_options to ensure the key is passed through to the message.

**Comment by Bogdanp** [comment]
You should try to get the option from the actor and fall back to the message:

```python

    def before_process_message(self, broker, message):
        actor = broker.get_actor(message.actor_name)
        unique_job_key = actor.options.get("unique_job_key") or \
            message.options.get("unique_job_key")
        ...
```

**Comment by Bogdanp** [comment]
Sorry, you probably want the reverse: get the option from the message and fall back to the actor. Coffee hasn't quite kicked in yet!
