### ISSUE TITLE
how to handle timeout?

### ISSUE THREAD

**Issue by allenling** [Bogdanp/dramatiq#28]
seems that after fn finished, dramatiq would check the timeout.

```
#dramatiq.actor.Actor.__call__
def __call__(self, *args, **kwargs):

    try:
        self.logger.info("Received args=%r kwargs=%r.", args, kwargs)
        start = time.perf_counter()
       # call self.fn
        return self.fn(*args, **kwargs)
    finally:
        # finally, we would wait for self.fn finished
        delta = time.perf_counter() - start
        self.logger.info("Completed after %.02fms.", delta * 1000)
```

but what if i want to kill a task before the task finished when the task timeout? 
could i do that?

**Comment by Bogdanp** [comment]
Time limits are handled by the `TimeLimit` middleware. Check out [this section](https://dramatiq.io/guide.html#message-time-limits) of the docs to find out how to use them. Hope that helps!
