### ISSUE TITLE
Gracefully handling Encoder errors

### ISSUE THREAD

**Issue by bmbove** [Bogdanp/dramatiq#284]
I've written an Encoder that serializes with pickle and appends a signature. On decode, the signature is verified before unpickling. I'm currently just raising an exception if the signature fails, but the message ends up being requeued and I end up with a continuous dump of "ConnectionWrongStateError" exceptions on the CLI.

Is there a recommended way to handle Encoder errors a little more gracefully? In my case, I'd like to do something like `raise SkipMessage("Signature verification failed!")`, and have the message just tossed. If there's no recommendations on this, I'd be up for working on a solution.

Also, if I'm going about this the wrong way (want to verify pickled data is from a legitimate source before unpickling), any advice would be helpful.

**Comment by Bogdanp** [comment]
> Is there a recommended way to handle Encoder errors a little more gracefully?

This isn't a use case I had considered. 

> In my case, I'd like to do something like raise SkipMessage("Signature verification failed!"), and have the message just tossed. If there's no recommendations on this, I'd be up for working on a solution.

I think it would be enough to add an exception handle for `SkipMessage` in `_ConsumerThread.run`. If that's enough to support this and it doesn't complicate things any further, I'd be happy to accept a PR for this.

**Comment by Bogdanp** [comment]
@thomazthz fix for this is now merged and will be released with the next version. Closing this for now.
