### ISSUE TITLE
Option to use fully qualified names for actor_name

### ISSUE THREAD

**Issue by funkybob** [Bogdanp/dramatiq#285]
# Issues
We're looking to switch over to dramatiq from a hand rolled job queue, and just noticed it effectively requires all tasks within a system to have globally unique names.

Ideally we'd like the option for task names to be formed from fully qualified names for their functions, not just the local name.

I guess a short-term work around is to write our own wrapper for the `dramatiq.actor` decorator to determine the actor_name how we want, but it would be nice if such a feature were built in.

## Checklist

* [x] Does your title concisely summarize the problem?
* [ ] Did you include a minimal, reproducible example?
* [ ] What OS are you using?
* [x] What version of Dramatiq are you using?
* [ ] What did you do?
* [ ] What did you expect would happen?
* [ ] What happened?

## What OS are you using?
python:3.8 docker image (Debian based)

## What version of Dramatiq are you using?
dramatiq 1.8.1
dramatiq-pg 0.7.1

**Comment by funkybob** [comment]
Note that as of Py 3.3 PEP-3155 makes it a lot easier to get a fully qualified name for any object:
https://www.python.org/dev/peps/pep-3155/

**Comment by Bogdanp** [comment]
> I guess a short-term work around is to write our own wrapper for the dramatiq.actor decorator to determine the actor_name how we want, but it would be nice if such a feature were built in.

I would say that this is the recommended solution in this case. I don't think the problem warrants adding more flags to dramatiq itself when it's so easy to do in user land, sorry!

**Comment by jarekwg** [comment]
Hej Bogdan,

If you're against flags, would you support changing the default behaviour?
For projects of large-to-moderate size, it's not feasible to have all actor functions defined in a single file. As soon the definitions start being put into multiple files, chance of clash is easy.

Using `__qualname__` sounds like a very sensible way forward, both to protect users from accidental function shadowing confusion, and also to make it super clear where a given queued function lives.

It would also potentially open a way forward to, in future, allowing actors to look up the function from a string, rather than hanging onto the bytecode while queued (if that's not what happens currently, I apologise; still getting familiar with this package).

Cheers,

**Comment by Bogdanp** [comment]
I considered `__qualname__` initially, but it also has its drawbacks. In particular, it means that actors can break when you refactor code by moving it into different modules. In light of that, my thinking was (and still is!) that naming conflicts are going to be less surprising than I-moved-my-code-around-and-now-everything-is-broken conflicts. Plus, naming conflicts are detected at load time (see below).

> It would also potentially open a way forward to, in future, allowing actors to look up the function from a string, rather than hanging onto the bytecode while queued (if that's not what happens currently, I apologise; still getting familiar with this package).

That's not what happens. Actors get registered by name when your code gets loaded. When a message comes in, its associated actor gets looked up in the registry. If two actors share the same name, then your code will blow up *at load time* (i.e. before anything can run).

**Comment by jarekwg** [comment]
> In light of that, my thinking was (and still is!) that naming conflicts are going to be less surprising than I-moved-my-code-around-and-now-everything-is-broken conflicts.

I guess.. depends which demographic you're protecting -- careless users or power users.
On the one hand, they have to be careful when they move actors around, making sure that anything referencing them is updated too.
On the other hand, they have to get inventive with longwinded naming conventions to keep everything afloat.
Perhaps what I don't follow here is how this differs from when _anything_ is moved between files in python -- associated references (ie. imports) _must_ be updated. It's a thing.

But that's fine, I think we'll just roll our own decorator in that case.

Thanks for responding so promptly and taking the time to explain!
