### ISSUE TITLE
Get processing status by message_id

### ISSUE THREAD

**Issue by chriskvik** [Bogdanp/dramatiq#287]
Hi, is there any functionality  to fetch status for messages/pipelines/groups by `message_id` ? I'm doing some background processing for my webpage and the front-end code needs to know when a job is finished by querying the API for status.

My somewhat hacky solution is to serialize and store the JSON representation of all messages in a pipeline and restore the pipeline when the client asks for status in a new request.

Am I misunderstanding something crucial here? How do you handle getting the context or job back if you lost the reference to the instantiated object.

```
EXTERNAL_JOB_STORE = {}

class StoredPipeline(pipeline):
    def __init__(self, children=None, broker=None, job_id=None):
        self.job_id = str(uuid.uuid4())

        if job_id:
            children = self.restore_pipeline(job_id)
            self.job_id = job_id

        super().__init__(children, broker=None)

    def store_pipeline(self):
        job = [msg.asdict() for msg in self.messages]
        EXTERNAL_JOB_STORE[self.job_id] = job
        return self.job_id

    def restore_pipeline(self, job_id):
        messages = []

        for message in EXTERNAL_JOB_STORE[job_id]:
            messages.append(Message(
                queue_name= message['queue_name'],
                actor_name=message['actor_name'],
                args=message['args'],
                kwargs=message['kwargs'],
                options=message['options'],
                message_id=message['message_id'],
                message_timestamp=message['message_timestamp'] 
            ))

        return messages
        
    def get_id(self):
        return self.job_id

# /api/do-job

uri = 'https://google.no'

pipe = StoredPipeline([
    get_site.message(uri),
    count_words.message(),
]).run()

pipe.store_pipeline()

# /api/check_job/<id>
pipe2 = StoredPipeline(job_id=pipe.get_id())
print(pipe2.completed)

# /api/get_results/<id>
print(pipe2.get_result(block=True))
```

**Comment by chriskvik** [comment]
Sorry, looks like something similar is already mentioned in #39. The way I read this is that some form of my solution is the only way to handle this with the current API?

**Comment by Bogdanp** [comment]
> The way I read this is that some form of my solution is the only way to handle this with the current API?

Yep, that's right. There's really not much dramatiq can do here w/o making tons of assumptions about how users' apps work so it seems reasonable to me for the onus to be on users to keep track of their messages if they need to.
