### ISSUE TITLE
Task states

### ISSUE THREAD

**Issue by mjdubell** [Bogdanp/dramatiq#30]
When running multiple tasks you often want to know about the tasks state or show some kind of progress to an end user. I believe it would be beneficial for Dramatiq to include such functionality, just like Celery does, which you can read more about [here](http://docs.celeryproject.org/en/latest/userguide/tasks.html#task-states).

If Dramatiq includes some kind of chain or group functionality, it would be great to get the current state of the chain/group.

**Comment by ericgj** [comment]
Check out current discussion going on now in #29

**Comment by ericgj** [comment]
Bogdan may have plans to integrate this into results storage, but in the meantime you can roll your own using the Callbacks middleware plus a similar middleware that fires on `before_process_message`. 

As for pipeline/groups,  dramatiq doesn't attach any extra state to these - right now you have to attach some kind of pipeline/group id to each message.

What I am doing is prepending a message to the front of my pipelines with the entire rest of the pipeline as the payload (args). This message when executed inserts records for each of the messages in the pipeline with a NOT STARTED status. Then as the messages run they update this status, save results, errors, etc. (You could do it insert-only instead.)  So far it is working well. If you are interested I can share my code in a gist.

**Comment by Bogdanp** [comment]
I'm going to close this as "won't do" since this is easy to implement on top of the existing primitives, like Eric mentioned.

**Comment by albasili** [comment]
@ericgj I would be interested in having a look at your code if that is not much of a trouble.

**Comment by ericgj** [comment]
Well, my approach is a bit "1.0" -- it works for me at the moment but I'm not sure I'd recommend it wider :)  But it may give you some ideas for improvement.

You can see all the code [here][code].  Here is the [results middleware][results_middleware] I use to store results, and customized [pipelines middleware][pipelines_middleware]. Here is how I [construct pipelines][construct] to work with these middlewares, and here is the [message broker setup][broker] showing how success and failure callbacks are specified. Then [here is the actual storage implementation][storage], using SQLite at the moment.

Just to note, you may find a way of building on the results backend primitives built-in to Dramatiq, e.g. through `Message#get_result`. This would no doubt be less workaround-ish. I couldn't quite wrap my mind around how to do it with pipelines and needing to report on individual task status within a pipeline.

[code]: https://bitbucket.org/ericgj/ert-cdp-task-queue/src/
[results_middleware]: https://bitbucket.org/ericgj/ert-cdp-task-queue/src/master/backend/dramatiq_extra/results/middleware.py
[pipelines_middleware]: https://bitbucket.org/ericgj/ert-cdp-task-queue/src/master/backend/dramatiq_extra/middleware/pipelines.py
[construct]: https://bitbucket.org/ericgj/ert-cdp-task-queue/src/a079bd1b83d8d058c867c5aaf4a77f7e6786684c/backend/mq.py?at=master&fileviewer=file-view-default#mq.py-95:108
[broker]: https://bitbucket.org/ericgj/ert-cdp-task-queue/src/a079bd1b83d8d058c867c5aaf4a77f7e6786684c/backend/mq.py?at=master&fileviewer=file-view-default#mq.py-20:34
[storage]: https://bitbucket.org/ericgj/ert-cdp-task-queue/src/master/backend/db/results.py?fileviewer=file-view-default

**Comment by albasili** [comment]
Wow! Thanks a lot! I also am trying to build a system to add data processing tasks to a queue and have workers pull those jobs from the pull and execute them. I'm not directly sure how it will end up but your framework is definitely a starter.
