### ISSUE TITLE
Consumer encountered a connection error

### ISSUE THREAD

**Issue by abhilash29** [Bogdanp/dramatiq#301]
When I try to run dramatiq <myworker> from the command line, it gives me the below error.
I'm currently using RabbitMQ.

    [Thread-2] [dramatiq.worker.ConsumerThread(default)] [CRITICAL] Consumer encountered a connection error: (406, "PRECONDITION_FAILED - inequivalent arg 'x-dead-letter-routing-key'for queue 'default' in vhost '/': received the value 'default.XQ' of type 'longstr' but current is none")

This is what I have done until now.

    import dramatiq
    from dramatiq import get_logger

    logger = get_logger(__name__)

    @dramatiq.actor
        def myfunction():

**Comment by Bogdanp** [comment]
Delete the `default.XQ` using the management interface or reset RMQ (see the RMQ docs on how to do this) and then re-run dramatiq.

**Comment by abhilash29** [comment]
> Delete the `default.XQ` using the management interface or reset RMQ (see the RMQ docs on how to do this) and then re-run dramatiq.

Worked like a charm. Thanks.
