### ISSUE TITLE
Type Hinting?

### ISSUE THREAD

**Issue by davidt99** [Bogdanp/dramatiq#302]
More of a question to @Bogdanp than an issue, is there a reason the codebase doesn't have any type hinting?

**Comment by Bogdanp** [comment]
[I stared into the abyss](https://github.com/python/mypy/pull/5010) and didn't like what I saw. More to the point, I don't find them and especially the tooling around them all that useful for type checking.

I think they're great for dependency injection, though, and use them heavily in [molten](https://moltenframework.com/).

**Comment by davidt99** [comment]
@Bogdanp thanks for the info. As a pycharm user, pycharm doesn't always identify automatically the types, especially in middleware and I don't think adding documentation to every function is what we want.
Would you consider changing your mind? Type hinting is what I miss the most when writing python2 compatible code.
