### ISSUE TITLE
Typing support for the public API

### ISSUE THREAD

**Issue by sobolevn** [Bogdanp/dramatiq#305]
Hi! Thanks a lot for building this awesome tool!

I am wondering if providing `typing` support is on your list?
It would be great to have `mypy` checked code, especially in async code.

This is one of the main reasons I look for better celery alternatives. They don't have types and there's no plan to support them. It would be awesome to have at least user-facing API typed and [pep-0561](https://www.python.org/dev/peps/pep-0561/) compatible.

I can probably help with adding some basic stuff 👍

**Comment by Bogdanp** [comment]
@davidt99 was asking about the same thing in https://github.com/Bogdanp/dramatiq/issues/302 . I wouldn't mind if someone typed the public API, but I'm not likely to use mypy myself. 

Ideally, the typing would be done in .pyi files to impact the library itself as little as possible. Assuming something like that is possible with modern mypy, then I'd accept such an addition.

**Comment by davidt99** [comment]
I'm not using mypy myself, I just wanted better coding experience. I don't mind adding the type annotations to the codebase itself (not in pyi files) but I'll respect what @Bogdanp decides.

**Comment by sobolevn** [comment]
I am going to send a WIP PR with the type stubs I have created using `monkeytype`.
They are generated using type information from examples. And *does* require further manual editing.

**Comment by sobolevn** [comment]
Well, sadly there are some cases that do not type well (decorators mostly) without a custom `mypy` plugin. How do you feel about that? 😄

**Comment by Bogdanp** [comment]
@sobolevn  Would the plugin have to be distributed with dramatiq? Could a user just install dramatiq and the plugin separately?

**Comment by sobolevn** [comment]
There are two possible way to handle it:
1. Two separate packages: `dramatiq` and `dramatiq-stubs`. The first one is going to be completely untouched. Possibly, adding new optional installation group: `pip install dramatiq[types]`. And the `dramatiq-stubs` repo can contain the full stubs information there is. And custom `mypy` plugins that are also optional. The only problem is that one has to sync two versions of code in two repos. It might be hard.
2. Everything is in one repo. Stubs can be located in the source code (if they are simple enough) or in stubs files in complex cases. `mypy` plugin cam still be optional (sometime soon `mypy` team is going to release new types to modify function signature, but there's not estimate: then we can drop this plugin). In this case it is way easier to sync code and type, but the number of files might get bigger up to 2 times. 

I would personally recommend the second option based on my experience with [`django-stubs`](https://github.com/typeddjango/django-stubs) where we use a separate repo for stub files and [`returns`](https://github.com/dry-python/returns) where I write stubs right inside the repo.
