### ISSUE TITLE
Large bytes of messages not removed from RabbitMQ broker

### ISSUE THREAD

**Issue by aldwyn** [Bogdanp/dramatiq#308]
## What OS are you using?

Ubuntu 18.04.4

## What version of Dramatiq are you using?

1.8.1

## What did you do?

I am currently running Dramatiq workers within a 40-vCPU core on-premise server, with 128 GB of RAM and 30 TB of HDD. The purpose of our app is to crawl 60,000 [WARC](https://gist.github.com/Smerity/e750f0ef0ab9aa366558#file-bbc-warc)-formatted files with around 45000-50000 HTML pages in each file. We use Dramatiq to run multiple parsers (i.e. `get_data_from_html` below) for all of the HTML pages once at a time and bulk insert the results to Elasticsearch (i.e. `bulk_process` below).

Our three memory-consuming workers are the following:
```python
from warcio.archiveiterator import ArchiveIterator

@dramatiq.actor
def extract_warc(content, url, es_buffer_len=1500):
    # where `content` is the WARC body in bytes
    data_pool = []
    with io.BytesIO(content) as stream:
        for record in ArchiveIterator(stream):
            data_pool.append({
                'target_uri': record.rec_headers.get_header("WARC-Target-URI"),
                'html': record.content_stream().read(),
                'source': url
            })
            if len(data_pool) >= es_buffer_len:
                bulk_process.send(data_pool)
                data_pool = []
    if data_pool:
        bulk_process.send(data_pool)
    ...

@dramatiq.actor(queue_name='bulk_process')
def bulk_process(data_pool, start_time=None, counter=0, filename=''):
    message_group_list = [get_data_from_html.message(**s) for s in data_pool]
    message_group = dramatiq.group(message_group_list)
    group = message_group.run()
    process_pool = list(group.get_results(block=True, timeout=100_000))
    # stores the list in bulk in Elasticsearch afterwards
   ...

@dramatiq.actor(store_results=True, queue_name='get_data_from_html', result_ttl=105_000)
def get_data_from_html(target_uri, html, source):
    # where `html` is the HTML body
    # returns a dict of scraped metadata from the `html`
    ...
```

## What did you expect would happen?

As it would have been expected, the memory should be freed after the scope (i.e. actor) is finished.

## What happened?

The goal is somewhat achievable with our current implementation, but the memory keeps filling up even though the workers have finished consuming the messages. I have tried manually calling `gc.collect()`, but as expected, it does not decrease the used space in the memory. It seems that the workers are not removing the completed messages from the RabbitMQ's queue index or message store. After some 8 WARC files, the 128 GB RAM is now full, and the server now does not respond while using the swap memory. After being disconnected from the server via SSH, we just remotely restart it, then `rabbitmq-server` is now not runnable, so we have to reinstall it.

**Comment by Bogdanp** [comment]
I doubt dramatiq is retaining the data after the actors are done. The likely problem here is sending such large data to and from RabbitMQ and, possibly, prefetch screwing you over by grabbing more messages/data than you have memory for. 

What I'd suggest is, instead of sending all the data to RMQ, write the data to disk and then send the file path around. Your code already expects a file stream so it wouldn't be a major change from that perspective, but it would make an absolutely massive difference in throughput.
