### ISSUE TITLE
Dramatiq globally opens port 9191 !!!

### ISSUE THREAD

**Issue by tenuki** [Bogdanp/dramatiq#309]
# Issues

Dramatiq worker opens and listen on port 9191 on every interface no matter it wasn't requested. Also this behavior isn't advised anywhere and seems not to be documented.

## What OS are you using?
Debian 10.

## What version of Dramatiq are you using?
$  /home/aweil/.local/bin/dramatiq --version
1.8.1

## What did you do?
run an example.

## What did you expect would happen?
no extra ports should be open.
no process should be listening anywhere.

## What happened?
Dramatiq worker opens and listen on port 9191 on every interface no matter it wasn't requested. Also this behavior isn't advised anywhere and seems not to be documented.
this seems to happen anytime you run the worker ( ../local/bin/dramatiq )

**Comment by Bogdanp** [comment]
https://dramatiq.io/advanced.html?highlight=prometheus#prometheus-metrics

To disable this, pass a custom list of middleware to your broker when you set it up.   The current defaults are [here](https://github.com/Bogdanp/dramatiq/blob/master/dramatiq/middleware/__init__.py#L45-L47).

**Comment by tenuki** [comment]
Thanks. Btw, it looks like search in the docs is broken or at least it
fails to search for 9191 :-( .

**Comment by evgkrsk** [comment]
Search is still broken...
