### ISSUE TITLE
Auto make & call dramatiq functions

### ISSUE THREAD

**Issue by deounix** [Bogdanp/dramatiq#314]
# Issues

GitHub issues are for bugs.  If you have questions, please ask them on the [discussion board](https://reddit.com/r/dramatiq).

## Checklist

* [x] Does your title concisely summarize the problem?
* [x] Did you include a minimal, reproducible example?
* [x] What OS are you using?
* [x] What version of Dramatiq are you using?
* [x] What did you do?
* [x] What did you expect would happen?
* [x] What happened?

## What OS are you using?
MACOS

## What version of Dramatiq are you using?
1.8.1

## What did you do?

I'm trying to make normal functions to be dramatiq functions (also to be auto called!) by adding a decorator

What I did:

```
from functools import wraps

def call_async(func):
    @wraps(func)
    def wrapped(*args, **kwargs):
        return drama.actor()(func.send(*args, **kwargs))

    return wrapped

@call_async
def test(): pass

```

also tried:

```
from functools import wraps

def call_async(func):
    @wraps(func)
    def wrapped(*args, **kwargs):
        return func.send(*args, **kwargs)

    return wrapped

@call_async
@drama.actor
def test(): pass
```

## What did you expect would happen?

So now if I'm called `test()` without using `.send` it should be auto called as a dramatiq function

## What happened?

```
AttributeError: 'function' object has no attribute 'send'
```

**Comment by Bogdanp** [comment]
Please only report actual issues in the future. For these types of questions, forums like Reddit, dev.to, stackoverflow, etc. are better venues.

This achieves what you want to do:

```python
def call_async(f):
  return dramatiq.actor(f).send

@call_async
def foo(x):
  print(x)
```
