### ISSUE TITLE
ConcurrentRateLimiter limit=1, with no retries?

### ISSUE THREAD

**Issue by jmagnusson** [Bogdanp/dramatiq#32]
First of all - Big thanks @Bogdanp for creating a truly pythonic task processor! Celery has always given me a kind of bitter after taste..

I'm working towards a backend system that can't handle concurrent writes to the same database table. On top of that the task writing to this system might fail half-way and then we have no way to know where to resume when the task is retried (unless I keep state in the app which I'd like to avoid to keep things simple), so I've passed `max_retries=0` to `dramatic.actor` and made the task notify me of any failures.

So my thought was that `dramatiq.rate_limits.ConcurrentRateLimiter` would be a perfect fit here. In [the example in the cookbook](https://dramatiq.io/cookbook.html?highlight=locks#rate-limiting-work) though you're using it inside the task function. But I guess this wouldn't work in my scenario as the task will never be retried...  Is there any way to have the mutex apply to the task itself so that it never even starts if another instance of that task is already executing?

In my head an API like this would do it for my scenario:

```python
import dramatiq
import time

from dramatiq.rate_limits import ConcurrentRateLimiter
from dramatiq.rate_limits.backends import RedisBackend

backend = RedisBackend()
DISTRIBUTED_MUTEX = ConcurrentRateLimiter(backend, "distributed-mutex", limit=1)

@dramatiq.actor(rate_limiter=DISTRIBUTED_MUTEX, max_retries=0)
def one_at_a_time():
  print("I'll never run concurrently! And never twice!")
```

Or maybe I'm going all wrong with this?

Any input would be greatly appreciated!

**Comment by Bogdanp** [comment]
Thank you for the kind words! 

Is the goal ultimately to not even enqueue the task if another is running? If not, then you should be able to do this:

```python
backend = RedisBackend()
DISTRIBUTED_MUTEX = ConcurrentRateLimiter(backend, "distributed-mutex", limit=1)

@dramatiq.actor(max_retries=0)
def one_at_a_time():
  with DISTRIBUTED_MUTEX.acquire(raise_on_failure=False) as acquired:
    if not acquired:
      return

    do_stuff_to_database()

# or 

@dramatiq.actor(max_retries=0)
def one_at_a_time():
  try:
    with DISTRIBUTED_MUTEX.acquire():
      do_stuff_to_database()
  except dramatiq.RateLimitExceeded: 
    pass
```

This way, if two of these tasks are enqueued concurrently, only one will `do_stuff_to_database()`, the other will silently exit w/o retrying. Acquiring one of these locks does not block until the lock is available so this is a fairly cheap way to go about things.

If the goal is simply to avoid the `with` block, then you can define a little middleware to do something very similar to what you did in your example:

```python
class UniqueJobsMiddleware(dramatiq.Middleware):
  def __init__(self, backend):
    self.backend = backend

  @property
  def actor_options(self):
    return {"unique_job_key"}

  def before_process_message(self, broker, message):
    unique_job_key = message.options.get("unique_job_key")
    if unique_job_key is not None:
      acquired = self.get_rate_limiter(unique_job_key)._acquire()
      if not acquired:
        raise dramatiq.middleware.SkipMessage

  def after_process_message(self, broker, message, *, result=None, exception=None):
    unique_job_key = message.options.get("unique_job_key")
    if unique_job_key is not None:
      self.get_rate_limiter(unique_job_key)._release()

  def get_rate_limiter(self, key):
    # Rate limiter objects are very cheap to create so this is not a concern.
    return ConcurrentRateLimiter(self.backend, key, limit=1)

broker.add_middleware(UniqueJobsMiddleware(RedisBackend()))


@dramatiq.actor(unique_job_key="inserts-into-slow-db", max_retries=0)
def one_at_a_time():
  print("I'll never run concurrently! And never twice!")
```

This will ensure that the function `one_at_a_time` is never called concurrently by a worker. If the goal is not to enqueue the message in the first place, that should also be doable via a similar middleware:

```python
class UniqueJobsMiddleware(dramatiq.Middleware):
  def __init__(self, backend):
    self.backend = backend

  @property
  def actor_options(self):
    return {"unique_job_key"}

  # I replaced before_process_message with before_enqueue.
  def before_enqueue(self, broker, message, delay):
    unique_job_key = message.options.get("unique_job_key")
    if unique_job_key is not None:
      acquired = self.get_rate_limiter(unique_job_key)._acquire()
      if not acquired:
        raise dramatiq.middleware.SkipMessage

  def after_process_message(self, broker, message, *, result=None, exception=None):
    unique_job_key = message.options.get("unique_job_key")
    if unique_job_key is not None:
      self.get_rate_limiter(unique_job_key)._release()

  def get_rate_limiter(self, key):
    return ConcurrentRateLimiter(self.backend, key, limit=1)
```

However, this won't work with the current version of Dramatiq as `before_enqueue_message` doesn't correctly handle `SkipMessage` right now. 

Hope that helps!

Let me know if I totally missed the mark. :D

**Comment by jmagnusson** [comment]
Thanks for the suggestions @Bogdanp, I appreciate you taking the time and your enthusiasm!

What I want to achieve is to put the task back into the queue if it fails (in same position if possible, but not strictly necessary in my case)

I had already started to write another API idea when your reply popped up, so I'm just gonna let it out before I dig through your response (which might be a bit later - gotta get some food in my stomach 😋).

So it looks something like this:

```python
import dramatiq
import time

from dramatiq.errors import RateLimitExceeded
from dramatiq.rate_limits import ConcurrentRateLimiter
from dramatiq.rate_limits.backends import RedisBackend

backend = RedisBackend()
DISTRIBUTED_MUTEX = ConcurrentRateLimiter(backend, "distributed-mutex", limit=1)

def should_retry(retry_num, raised_exc):
  return isinstance(raised_exc, RateLimitExceeded)

@dramatiq.actor(max_retries=should_retry)
def one_at_a_time():
  with DISTRIBUTED_MUTEX.acquire():
    print("I'll never run this part concurrently! And never twice!")
```

**Comment by Bogdanp** [comment]
Ahhh, yes, I did miss the point of your question the first time around! You can ignore my previous comment.

Right now, there is no easy way to conditionally activate the retries middleware based on some predicate. I like your idea of having an option for a predicate function, though it'd probably be better to call it something like `retry_if`:

```python
def should_retry(retry_num, raised_exc):
  return isinstance(raised_exc, RateLimitExceeded)

@dramatiq.actor(retry_if=should_retry)
def one_at_a_time():
  ...
```

I'll add support for this sometime this week. In the mean time, I would recommend doing something like this:

```python
class RetryMutex(dramatiq.Middleware):
  def after_process_message(self, broker, message, *, result=None, exception=None):
    if isinstance(exception, RateLimitExceeded):
      broker.enqueue(message, delay=10_000)
```

```python
broker = dramatiq.get_broker()
broker.add_middleware(RetryMutex())


@dramatiq.actor(max_retries=0)
def one_at_a_time():
  ...
```

**Comment by jmagnusson** [comment]
Sorry for being unclear 😅

I definitely prefer you naming it `retry_if`! Although maybe it should be called `unconditionally_retry_if` as it's not decrementing the retry count?

Thank you so much for the solution with `RetryMutex`, worked like a charm!

Just a few thoughts though:

* The logs get quite chatty with the tracebacks for all `RateLimitExceeded` that are thrown. Perhaps just a regular log message would do here, OR
* It seems to increase the backoff time for each time that the task is retried this way. Wouldn't it be awesome if we could listen to when the mutex is released instead? If that's possible.

**Comment by Bogdanp** [comment]
> The logs get quite chatty with the tracebacks for all RateLimitExceeded that are thrown. Perhaps just a regular log message would do here, OR

👍 I wanted to avoid coupling retries w/ the worker loop initially so I just let them behave like any other exception, but I can see how this would be annoying/distracting. I'll special-case the exception so it logs a warning.

> It seems to increase the backoff time for each time that the task is retried this way. Wouldn't it be awesome if we could listen to when the mutex is released instead? If that's possible.

There are ways to make that work, but then we'd have to block a worker thread to do the waiting, which is not a good use of resources. The backoff times are easily tweaked so my suggestion would be to observe how your task behaves in general and leverage [those options](https://dramatiq.io/reference.html#dramatiq.middleware.Retries).

**Comment by Bogdanp** [comment]
Alright, I implemented these changes in #33 which I'll merge sometime this week.

**Comment by jmagnusson** [comment]
Awesome, great work. Code in PR looks solid @Bogdanp 👍

**Comment by Bogdanp** [comment]
This is released in version 0.19. Thanks again!

**Comment by jmagnusson** [comment]
Nice, GJ @Bogdanp!

**Comment by slidenerd** [comment]
In addition to the one access at a time, I have a query related to this one since I could not find it in the docs. I am trying to ping an external API which has a rate limit of 300/minute I have a 1000 urls to ping every 15 mins or so as part of scraping

1. How to setup such a rate limit?
2. Does this rate limit apply across processes and threads that dramatiq is using?

Thanks in advance for your answer @Bogdanp
