### ISSUE TITLE
Some AMQP connections are closed due to missed heartbeats after dramatiq boot

### ISSUE THREAD

**Issue by takhs91** [Bogdanp/dramatiq#321]
# Issues
After dramatiq cli boots,some amqp connections are getting closed from rabbitmq couple of seconds after, depending on the heartbeat settings.
```
rabbitmq_1        | 2020-06-24 11:53:50.358 [error] <0.3580.0> closing AMQP connection <0.3580.0> (172.19.0.5:39108 -> 172.19.0.9:5672):
rabbitmq_1        | missed heartbeats from client, timeout: 5s
```
I believe they are as many as the queues declared * number of worker processes

I think they are the connections used by the `RabbitmqBroker` used to declare queues,enqueuing etc. because the connections setup by ` _RabbitmqConsumer` in the consumer threads are kept alive.

I believe the same may also happen later because broker.connection is also used for enqueuing delayed messages, retries etc. given they will stay stale for too long?

## What OS are you using?

Linux Mint 18 64-bit 4.4.0-174-generic

## What did you expect would happen?
What if the the worker was closing the connections that doesn't intend to keep alive to avoid them being closed from the rabbitmq's side if possible? Opening and closing connections would have a performance impact of course but how much would that be?  Otherwise what would be the impact of disabling heartbeats for those connections(or using a much larger value) and keeping them enabled only for consumer connections?

Those messages on the rabbitmq's side are a bit distracting / indicating that something bad happened, especially while troubleshooting other issues.

**Comment by Bogdanp** [comment]
Does adding this middleware solve the issue for you?

```python
class DisconnectMiddleware(Middleware):
    def after_worker_boot(self, broker, worker):
         del broker.connection
```

It is kind of a crappy situation in general because dramatiq needs to set up the connections to declare the queues, like you've said, but at the same time it can't know when your app's **really** done doing that in general so I've avoided making it do the above by default. If your app doesn't do any lazy loading of modules, then doing the above should solve your problem.

**Comment by takhs91** [comment]
Thanks for you reply.
It doesn't seem to do it. Just deleting doesn't seem to close a connection, I think .close() has to be called after experimenting a bit.
 Although I also tried calling `broker.close()` and `broker.connection.close()` in that DisconnectMiddleware but didn't do it either.

That still will only solve the issue for the boot though, any enqueuing done later on the worker will create new connections that will expire too.

> If your app doesn't do any lazy loading of modules, then doing the above should solve your problem.

Can you give me an example of lazy loading in that context? I use django_dramatiq to import some actors from a series of task modules. All the actors are declared on the top level.

**Comment by Bogdanp** [comment]
The middleware should now work (on master) and you should be able to add a hook for `after_enqueue` to close those connections.

> Can you give me an example of lazy loading in that context? I use django_dramatiq to import some actors from a series of task modules. All the actors are declared on the top level.

It's been a long time, but I believe I was referring runtime imports of modules that could cause new actors to be declared (which would fail if you'd closed the connections before import). You shouldn't have this issue with `django_dramatiq`.
