### ISSUE TITLE
Feature request: Kafka support

### ISSUE THREAD

**Issue by antonrh** [Bogdanp/dramatiq#322]
Any plans to add Apache Kafka support ? 

Really love to see Kafka support in Dramatiq using one of python kafka libraries:
* https://github.com/dpkp/kafka-python
* https://github.com/confluentinc/confluent-kafka-python

**Comment by Bogdanp** [comment]
I don't use Kafka so it's unlikely that I will, but making brokers is relatively easy so someone else could do it and publish it as a package. You can take a look at the [sqs](https://github.com/Bogdanp/dramatiq_sqs) broker if you're wondering what that might look like.

**Comment by bartvanandel** [comment]
Someone wrote an package for this 2 years ago (unpublished as far as I can tell, unfortunately): https://github.com/viktorb1/dramatiq_kafka

I have yet to try it, but it would be awesome if this could be bundled to make things easier to get going.
