### ISSUE TITLE
Document that watch is not supported on windows

### ISSUE THREAD

**Issue by CaselIT** [Bogdanp/dramatiq#326]
# Issues

Watch requires the signal `SIGHUP` that is only available on unix type system.
## What OS are you using?
windows
## What version of Dramatiq are you using?
1.9.0
## What did you do?
started dramatiq with the --watch option and modified the files causing a reload
## What did you expect would happen?
The code would reload. Or a meaningful error would be raised.
## What happened?
The excection `AttributeError: module 'signal' has no attribute 'SIGHUP'` is raised.

While it would be nice to have support for reload on windows, I think its would be ok to just document that watch is not supported in `dramatiq --help` and maybe ignore the flag on windows or raise a more meaningful exception than the attribute error

**Comment by Bogdanp** [comment]
This makes sense to me. Would you like to make these changes?

**Comment by CaselIT** [comment]
Ok, I'll have a look at it. I think that documenting that watch on windows is not supported and ignore the flag would be preferred option for now? Alternatively I'm not sure if we could change `SIGHUP` for another signal on windows to make watch work?

**Comment by Bogdanp** [comment]
> I think that documenting that watch on windows is not supported and ignore the flag would be preferred option for now?

Yep. That sounds like the right approach. Maybe raise a specific error when `--watch` is set on Windows instead of ignoring it.
