### ISSUE TITLE
Dramatiq actor hangs after launch with redis backend

### ISSUE THREAD

**Issue by tnachen** [Bogdanp/dramatiq#331]
# Issues

Dramatiq actor can hang with redis backend

## Checklist

* [ ] Does your title concisely summarize the problem?
* [ ] Did you include a minimal, reproducible example?
* [ ] What OS are you using?
* [ ] What version of Dramatiq are you using?
* [ ] What did you do?
* [ ] What did you expect would happen?
* [ ] What happened?

## What OS are you using?

Both mac or ubuntu, as it's running docker

## What version of Dramatiq are you using?

latest 19.0

## What did you do?

dramatiq -t 1 -p 1 --queues xxxxx class

## What did you expect would happen?

It should get tasks from Redis and start processing

## What happened?

It simply hangs after it launches the prometheus server and doesn't pull off any tasks at all. No other messages from the logs.

**Comment by Bogdanp** [comment]
Thanks for the report. Does it eventually time out? Have you verified that it is connecting to the right Redis instance? Have you run it with verbose logging (`dramatiq -v`) to see what it's doing?

**Comment by Bogdanp** [comment]
Closing for now. Feel free to reopen if you have more details or a small reproduction example.
