### ISSUE TITLE
Document the broker_priority parameter

### ISSUE THREAD

**Issue by jhoareau** [Bogdanp/dramatiq#338]
The RabbitMQ broker seems to handle per-message priority : https://github.com/Bogdanp/dramatiq/blob/master/dramatiq/brokers/rabbitmq.py#L312

But this option is not documented anywhere. It should be documented and its effect explained in the documentation.

Thanks.

**Comment by dkgitdev** [comment]
I think this can be related

https://www.rabbitmq.com/priority.html

**Comment by dkgitdev** [comment]
I think it might be documented as a cookbook example, based on the following existing docs

https://dramatiq.io/reference.html?highlight=priority#actors-messages

![изображение](https://user-images.githubusercontent.com/36101416/105411809-ebe33680-5c44-11eb-8f09-d0660464b700.png)
