### ISSUE TITLE
Handling of task broker made unavailable?

### ISSUE THREAD

**Issue by jmagnusson** [Bogdanp/dramatiq#34]
If the task broker becomes unavailable the dramatiq log gets completely flooded with messages like this (about 10 per second or so):

```
[2018-01-16 14:40:24,146] [PID 22] [Thread-4] [dramatiq.worker.ConsumerThread(default)] [ERROR] Consumer encountered a connection error.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/dramatiq/worker.py", line 197, in run
    for message in self.consumer:
  File "/usr/local/lib/python3.6/site-packages/dramatiq/brokers/redis.py", line 330, in __next__
    raise ConnectionClosed(e) from None
dramatiq.errors.ConnectionClosed: Error -2 connecting to redis:6379. Name does not resolve.
```

When sending logs externally this can put quite a strain on the log receiver. Perhaps the retry frequency should be limited, preferably with a delay argument to the Broker instance? 1 second would be a good default I think.

**Comment by Bogdanp** [comment]
Thanks! This is actually a bug as the customer should retry with exponential backoff. I'll take a look tomorrow morning!

**Comment by jmagnusson** [comment]
Awesome 👍

Can one turn off exponential backoff? At least in my case I'd just like it to be a set limit of 1-2 seconds or so, to not have to wait too long for the broker to come back online again.

Perhaps doing a simple error log message instead of spitting out the exception for known exceptions such as "Name does not resolve" (which is very common in a containerized environment) would make it less chatty. What do you think?

**Comment by Bogdanp** [comment]
Thanks! I changed it to a fixed delay of 3 seconds by default, which you can configure via an env var called `dramatiq_restart_delay` (specified in milliseconds).
