### ISSUE TITLE
Updating retry settings from within task?

### ISSUE THREAD

**Issue by docelic** [Bogdanp/dramatiq#344]
Hey,

I am using Dramatiq with Redis backend and `CurrentMessage` middleware.
I am trying to affect the task's values for max_retries, countdown, and kwargs in runtime (from within the task).
But in the current message's details I am not seeing any retry-related settings.

Is it possible to affect these values in runtime, and if yes, how?

Thanks!

**Comment by Bogdanp** [comment]
Take a look at the implementation of the [Retries](https://github.com/Bogdanp/dramatiq/blob/13e8d626c4d0250a92a436324b0039204a3cf706/dramatiq/middleware/retries.py) middleware. If you have access to the current message, you can affect its `options`.

**Comment by docelic** [comment]
Ah indeed. I was expecting to see the defaults there but they were empty. Once I defined some max_retries= etc., there were indeed visible in options. Thanks!
