### ISSUE TITLE
Can't get the results from redis

### ISSUE THREAD

**Issue by simGudim** [Bogdanp/dramatiq#349]
# Issues

GitHub issues are for bugs.  If you have questions, please ask them on the [discussion board](https://reddit.com/r/dramatiq).

## Checklist

* [ ] Does your title concisely summarize the problem?
* [ ] Did you include a minimal, reproducible example?
* [ ] What OS are you using?
* [ ] What version of Dramatiq are you using?
* [ ] What did you do?
* [ ] What did you expect would happen?
* [ ] What happened?

## What OS are you using?

 macOS 10.13.3 

## What version of Dramatiq are you using?

.9.0

## What did you do?

Trying to get the results from a fucntrion

## What did you expect would happen?
Get the result

## What happened?

Thank you for this amazing task queue. I am struggling a bit to get the results from the tats queue. Here is my code:

```
import dramatiq
import requests
from dramatiq.brokers.redis import RedisBroker
from dramatiq.brokers.rabbitmq import RabbitmqBroker
from dramatiq.results import Results
from dramatiq.results.backends import RedisBackend

# # broker = RabbitmqBroker(host="127.0.0.2", port=5672)
result_backend = RedisBackend()
broker = RedisBroker(host='127.0.0.1', port=6379)
broker.declare_queue("default")
broker.add_middleware(Results(backend=result_backend))
dramatiq.set_broker(broker)

@dramatiq.actor(store_results=True)
def example(x, y):
    return x * y

job = example.send(1, 2)
print(job.get_result(backend = result_backend, block  = True))
```
I am expecting the` job.get_result` should give me 2. Instead I get the following error:

```
Traceback (most recent call last):
  File "redis_test.py", line 20, in <module>
    print(job.get_result(backend = result_backend, block  = True))
  File "/usr/local/lib/python3.8/site-packages/dramatiq/message.py", line 147, in get_result
    return backend.get_result(self, block=block, timeout=timeout)
  File "/usr/local/lib/python3.8/site-packages/dramatiq/results/backends/redis.py", line 82, in get_result
    raise ResultTimeout(message)
dramatiq.results.errors.ResultTimeout: example(1, 2)
```

I have started a redis server on mac by calling `redis-server `command and something is happening everytime I run the file. For example the redis-server terminal gives me the followoing message:

```
22561:M 11 Oct 2020 18:08:13.007 * 100 changes in 300 seconds. Saving...
22561:M 11 Oct 2020 18:08:13.008 * Background saving started by pid 40889
40889:C 11 Oct 2020 18:08:13.012 * DB saved on disk
22561:M 11 Oct 2020 18:08:13.110 * Background saving terminated with success
```

**Comment by Bogdanp** [comment]
What might be happening here is that because you're enqueueing the message at the module top level and then immediately waiting for it, this ends up blocking the worker code, so the task doesn't get processed before the wait times out. What happens if you guard the last two lines behind a `if __name__ == '__main__':` block?

**Comment by simGudim** [comment]
Hi Bogdan, 

Thank you for your reply. Exactly the same issue seems to persist when I put the last two lines behind the if statement. I am currently a bit busy with other things but I will investigate this a bit more and let you know if I found something.
