### ISSUE TITLE
Comparison table with Huey is outdated

### ISSUE THREAD

**Issue by hmoravec** [Bogdanp/dramatiq#352]
The [comparison with Huey](https://dramatiq.io/motivation.html#compared-to) seems to be outdated.

The table states that:

- Huey does not support reliable delivery but [it supports retrying failed tasks](https://huey.readthedocs.io/en/latest/guide.html#retrying-tasks-that-fail).
- Huey does not support task prioritization but [it supports task priority](https://huey.readthedocs.io/en/latest/guide.html#task-priority).
- Huey does not support code auto reload but [it supports immediate mode](https://huey.readthedocs.io/en/latest/guide.html#immediate-mode) which serves the same purpose as code auto reload to make the development and testing easy.

**Comment by Bogdanp** [comment]
Thanks! Reliable delivery refers to the library's ability to ensure that a message has been persisted on the broker before succeeding a call to enqueue and it has nothing to do with retries. Likewise, immediate mode is orthogonal (and, imo, an anti-pattern) to being able to run actual workers and get them to automatically restart as you change code. 

I'd be happy to take a PR updating the information about priorities, though. If you don't feel like doing it, I'll do it myself when I have some time.

**Comment by hmoravec** [comment]
Right, I mislooked the reliability part. Huey docs about reliability [is not particularly clear](https://github.com/coleifer/huey/issues/559). Perhaps the exact meaning of reliability could be mentioned in a note under the table. 

Also I think that the reliability for Celery should be changed to "yes"  because, as already mentioned in the note, it supports it, although not as default choice. [The explanation for this default](https://github.com/coleifer/huey/issues/559) is IMO also quite reasonable.
