### ISSUE TITLE
Can't send email even if dramatiq is down

### ISSUE THREAD

**Issue by tiagoarasilva** [Bogdanp/dramatiq#360]
Like celery has an option to send messages even if the app is down I can't find the same for dramatiq, meaning, the send() doesn't actually send unless dramatiq is on. Is there any option to make sure it sends in a sync way if this happens?

**Comment by Bogdanp** [comment]
No, there's no such thing for Dramatiq. You can wrap your send in a try-catch block and call the function synchronously if the broker fails, but that's the extent of it. 

Also, please post questions like these on the discussion board instead in the future. GH issues are for actual issues.
