### ISSUE TITLE
type object 'Actor' has no attribute 'actor_name'

### ISSUE THREAD

**Issue by cwpurdy** [Bogdanp/dramatiq#362]
## What OS are you using?
Mac Catalina

## What version of Dramatiq are you using?
dramatiq v1.9.0

## What did you do?

Flask API with APScheduler and Python

Adding Job to APScheduler via Flask

```
@dramatiq.actor
def my_func():
    print("MY FUNC")

schedule.add_job(my_func, id=job_id, trigger=CronTrigger.from_crontab("* * * * *"), jobstore='jobstore')
```

And using something similar to [apcsheduler-dramatiq-executor](https://github.com/cthtuf/apcsheduler-dramatiq-executor) to have APScheduler send job to Dramatiq

`get_broker().get_actor(job.func.actor_name).send(*job.args, **job.kwargs)
`

## What happened?
This throws an error telling me 

`AttributeError: type object 'Actor' has no attribute 'actor_name'
`

Looking at the dramatiq docs, there definitely is an actor_name attribute in the Actor class, any suggestions as to what I can do?

**Comment by Bogdanp** [comment]
Hard to say exactly without seeing your code, but the error message suggests that `job.func` is the `Actor` class rather than an instance of it. If you can set up a small example that reproduces the issue, I'll take a look.

**Comment by cwpurdy** [comment]
@Bogdanp 

Thanks for the reply, 

[Here](https://gist.github.com/cwpurdy/c7ca82531fb5590228c51d40e6abf5fe) is a basic example that I got to reproduce the error. For what its worth, I think it has something to do with storing APScheduler jobs in a job store (in this example Postgres) but I am not sure what that changes

**Comment by gdvalle** [comment]
Bogdan's guess was correct here.  In your example `job.func` ends up being a class, and I'm guessing this is due to APScheduler's (re)construction of a reference to the callable.

In your example, using the string `tasks:add` instead works.

**Comment by cwpurdy** [comment]
Thanks for the info, that seems to have done the trick. It seems to be more of a APScheduler problem rather than Dramatiq, considering that it works with `tasks:add` and not `scheduler.add_job`. I appreciate the pointers!

**Comment by cwpurdy** [comment]
@gdvalle 

Do you mean inside the executor use the string `tasks:add` ? or when the job is added?

**Comment by gdvalle** [comment]
> Do you mean inside the executor use the string `tasks:add` ? or when the job is added?

@cwpurdy When the job is added:
`scheduler.add_job('tasks:add', 'interval', minutes=1)`

**Comment by cwpurdy** [comment]
gdvalles solution works
