### ISSUE TITLE
dramatiq-gevent error: BlockingIOError: [WinError 10035] A non-blocking socket operation could not be completed immediately

### ISSUE THREAD

**Issue by guzuomuse** [Bogdanp/dramatiq#363]
## What OS are you using?

win10

## What version of Dramatiq are you using?
1.9.0

when using dramatiq-gevent from cli

`venv/.../python.exe dramatiq-gevent count_words -p 8 -t 250`

give this error:

**BlockingIOError: [WinError 10035] A non-blocking socket operation could not be completed immediately**

**Comment by Bogdanp** [comment]
This seems like an issue with gevent on Windows. Please try opening an issue on their end.
