### ISSUE TITLE
CLI -p parameter description differs from docs description

### ISSUE THREAD

**Issue by thclark** [Bogdanp/dramatiq#365]
# Issues

GitHub issues are for bugs.  If you have questions, please ask them on the [discussion board](https://reddit.com/r/dramatiq).

## Checklist

* [x] Does your title concisely summarize the problem?
* [x] Did you include a minimal, reproducible example?
* [x] What OS are you using?
* [x] What version of Dramatiq are you using?
* [x] What did you do?
* [x] What did you expect would happen?
* [x] What happened?

## ~~What OS are you using~~ What OS and hardware are you using?

**Dual core** intel i5 2013 macbook pro with OSX Mojave 10.14.6 (18G6042)

## What version of Dramatiq are you using?
1.9.0

## What did you do?

I did:
```
dramatiq -h
```

I also read docs in the [workers section](https://dramatiq.io/guide.html#workers) which says:
> ...This will spin up as many processes as there are CPU cores on your machine...

## What did you expect would happen?

I expected `dramatiq -h` to return either:
```
...
optional arguments:
  ...
  --processes PROCESSES, -p PROCESSES
                        the number of worker processes to run (default: number of CPUs on your machine)
 ...
```
OR (if it looks up the default based on the machine it's running on)
```
...
optional arguments:
  ...
  --processes PROCESSES, -p PROCESSES
                        the number of worker processes to run (default: 2)
 ...
```

## What happened?

The CLI help displays a fixed number of cores.
```
...
optional arguments:
  ...
  --processes PROCESSES, -p PROCESSES
                        the number of worker processes to run (default: 4)
 ...
```

So, I'd like to know which is correct, the CLI or the docs?

**Comment by thclark** [comment]
OK, so I dug into the source code [here](https://github.com/Bogdanp/dramatiq/blob/4baf93120457790f36296dc6b955ac6331ee952d/dramatiq/cli.py#L57) to find that the CLI does in fact work as expected.


```
me$ python
Python 3.6.9 (default, Dec  3 2019, 08:23:19)
>>> import multiprocessing
>>> print(multiprocessing.cpu_count())
4
```

How my i'm-100%-sure-I-paid-for-a-dual-core-machine-because-i-have-the-receipt-right-in-front-of-me registers as quad core, I don't know, but either there's some problem with `multiprocessing` or (more likely) with my understanding of what constitutes a "core" on the i5 architecture.

What's more of a mystery is that I haven't come across this before, in the last 6 years of developing daily on this computer.

But at any rate this clearly isn't a problem with `dramatiq` so closing as a non-issue. If you read this far, thanks for your time.

**Comment by Bogdanp** [comment]
Your dual core processor likely has two hardware threads per core, hence 4 processing units.

**Comment by thclark** [comment]
Close. Just chatting to another developer (housemates are useful!) who says that the extras are vCPUs, and we used psutil to check:
```
>>> import psutil
>>> psutil.cpu_count(logical=False)
2
>>> psutil.cpu_count(logical=True)
4
```

Anyway, no action required, thanks for your time @Bogdanp - also thanks for the dramatiq library in general, I'm loving this after years of celery agony.
