### ISSUE TITLE
Best practice to setup some process-level global context

### ISSUE THREAD

**Issue by liuzqt** [Bogdanp/dramatiq#367]
I'm trying to use `dramatiq` for some IO tasks that need to run asynchronously. Those IO tasks are heavily involved with some global context, such as connection pool for database. 

What might be the best practice to explicitly tell the worker to share things like connection pool, or re-setup some global context if necessary? I've quickly looked through the official document and guide, but didn't find much about this topic, not sure if I've missed something. Would like to hear some advice, thanks!

**Comment by Sovetnikov** [comment]
Dramatiq worker just calls task as regular function and do nothing special after it finishes, seems you can store global variable in some module and reuse it in next task run.

**Comment by Bogdanp** [comment]
Either you can do this at the module level or write a custom middleware, which'll allow you to hook in at various points in the worker lifecycle to manage your pools: https://dramatiq.io/reference.html#middleware

Also, next time please ask your question on the discussion board as the [issue template](https://github.com/Bogdanp/dramatiq/issues/new) suggests.
