### ISSUE TITLE
License

### ISSUE THREAD

**Issue by CSharpDummy** [Bogdanp/dramatiq#373]
Project is great and would be a good fit, but the license is a big NO for industrial applications. Would you consider changing it to 'MIT'?

# Issues

GitHub issues are for bugs.  If you have questions, please ask them on the [discussion board](https://reddit.com/r/dramatiq).

## Checklist

* [ ] Does your title concisely summarize the problem?
* [ ] Did you include a minimal, reproducible example?
* [ ] What OS are you using?
* [ ] What version of Dramatiq are you using?
* [ ] What did you do?
* [ ] What did you expect would happen?
* [ ] What happened?

**Comment by Bogdanp** [comment]
Sorry, no, my preference is to keep the project under the LGPL. If you'd like me to grant you a commercial license, though, you can send me an e-mail.
