### ISSUE TITLE
PyCharm fails to type-check retry_when

### ISSUE THREAD

**Issue by denizdogan** [Bogdanp/dramatiq#377]
This is *kind of* related to #302 and #305 but of a different nature.

PyCharm fails to recognize the parameter types of `dramatiq.actor` properly:

![image](https://user-images.githubusercontent.com/50928/105999502-12bec400-60ae-11eb-9299-1432e3682340.png)

As you can see, for some reason, PyCharm expected a `dict` as the argument to `retry_when`.

I'm not sure if this is a proper fix, but if we modify [L194 in actor.py](https://github.com/Bogdanp/dramatiq/blob/591a54e88a438163ba51c61b921838f91a44384b/dramatiq/actor.py#L194) to say `**options:`, the warning goes away.

**Comment by Bogdanp** [comment]
I'd be OK with the proposed change. Let me know if you want to do it.

**Comment by denizdogan** [comment]
I wouldn't mind having it changed, it would get rid of the problem and I don't think it's a very meaningful type declaration. But I should mention that the same issue seems to exist in 11 places in 7 files elsewhere in the code (not that I use the others myself, at least for now).
