### ISSUE TITLE
dramatiq.Retry is still raising an error in Sentry

### ISSUE THREAD

**Issue by ramonsaraiva** [Bogdanp/dramatiq#378]
## What OS are you using?

Debian buster

## What version of Dramatiq are you using?

Latest (1.10.0)

## What did you do?

Swapped an internal exception to `dramatiq.Retry`.

## What did you expect would happen?

No errors on Sentry caused by `dramatiq.Retry` exception.

## What happened?

Errors on Sentry.

![image](https://user-images.githubusercontent.com/5559120/106038487-c2982f80-60b6-11eb-9062-2693a111615e.png)

**Comment by Bogdanp** [comment]
At a glance, it doesn't look like Dramatiq would log these so it depends on how you're integrating with Sentry. Do you need to update your Sentry middleware to ignore `Retry` exceptions?

**Comment by ramonsaraiva** [comment]
Yep, that might be the case, but we're using `sentry_sdk` with `sentry_dramatiq.DramatiqIntegration`. I'll try adding this exception to `ignore_errors` in its initialization and give it a try.

**Comment by Bogdanp** [comment]
Sounds like that should be fixed in the sentry integration then. It's not clear to me which one you're using. Maybe [sentry-dramatiq](https://pypi.org/project/sentry-dramatiq/) ? Either way, I'm going to close this since it's not an issue w/ dramatiq itself.
