### ISSUE TITLE
Documentation: update time_limit docs.

### ISSUE THREAD

**Issue by jenstroeger** [Bogdanp/dramatiq#379]
I think this docstring:

https://github.com/Bogdanp/dramatiq/blob/591a54e88a438163ba51c61b921838f91a44384b/dramatiq/middleware/time_limit.py#L44-L46

may need to be updated to
```
time_limit(int, float): The maximum number of milliseconds actors may
        run for. Use `float("inf")` to avoid setting a timeout for the actor.
```

**Comment by Bogdanp** [comment]
I would change the type to just `float`, but otherwise this seems like a good change. Would you like to make a PR?
