### ISSUE TITLE
Distributed task processing in order

### ISSUE THREAD

**Issue by denizdogan** [Bogdanp/dramatiq#385]
Suppose you have roughly one million alphanumerical string values that you want to be processed by the actor `foo`:

```py
@dramatiq.actor
def foo(value):
    print(value)
```

Each value has the format `ABCDEF_123456` where we consider `ABCDEF` the prefix and `123456` the suffix. Each value is queued in order by a single process, so if the value `AAAAAA_000000` exists, it would be queued first and if `ZZZZZZ_999999` exists, it would be queued last.

Now suppose that some of these values have the same prefix, so e.g. two values are `ABBABB_001001` and `ABBABB_001002`. In my system, I need `ABBABB_001001` to be processed before `ABBABB_001002`, but `ABCABC_371873` can be processed before or after, I don't really care, because it has a different prefix.

What is the best way to ensure that values with matching "prefixes" are processed in the order in which they are queued?

(I apologize for the undescriptive title, I couldn't come up with something good.)

**Comment by Bogdanp** [comment]
This is a super late reply, but I'd say dramatiq really isn't well suited for something like this. You could use separate queues for every prefix (though it sounds like that's infeasible if you have so many prefixes) and a single worker per queue, without prefetch. At that point, though, you might as well roll your own thing.
