### ISSUE TITLE
Retries middleware doesn't set the last traceback

### ISSUE THREAD

**Issue by liveFreeOrCode** [Bogdanp/dramatiq#387]
https://github.com/Bogdanp/dramatiq/blob/5e93e156b7e331bdb423ce86d3b3a711812020dd/dramatiq/middleware/retries.py#L104

This doesn't feel right.  The last traceback is never recorded if a message is thrown, or exceeds it's retry policy.  This feels like it should be moved up to the top of this hook?

**Comment by oddfellow** [comment]
In my case this is problematic because with "max_retries=0" in the actor, I don't get a traceback at all saved in the middleware, it's only logged in the worker output.

**Comment by Bogdanp** [comment]
This is fixed as of d5737fb77a2efc2ebfed216a24d932800d9635f9 .
