### ISSUE TITLE
How to disable prefetching

### ISSUE THREAD

**Issue by hmoravec** [Bogdanp/dramatiq#392]
There [is implemented](https://github.com/Bogdanp/dramatiq/commit/8a103e087d88835f4b256134036ce5149c230db9#diff-7bc0fe5a9d87fcca70f02f7a623d50329ca9047b0bafd4d40139d40ceb8886fd) possibility to set number of prefetched messages using `dramatiq_queue_prefetch` env var (see #183), however it is not documented anywhere and when it is set to zero, it is ignored because `self.queue_prefetch = QUEUE_PREFETCH or min(worker_threads * 2, 65535)` evaluates the first condition as false. Not sure if this is a bug or a feature. Is it possible to disable prefetching so it does no happen that one worker prefetches a message and the other workers cannot work on it even when they are idle?

**Comment by Bogdanp** [comment]
See the note above the constant's definition:

https://github.com/Bogdanp/dramatiq/blob/cdb5035f4a1ed8ae8159589eee441f06a765983a/dramatiq/worker.py#L41-L45

The value includes in-progress messages so to only fetch a single message at a time, you should set `dramatiq_queue_prefetch` to the number of worker threads you run. If you only have a single worker thread, then setting it to 1 should do what you want.

**Comment by hmoravec** [comment]
I see, in the mentioned PR there was not this comment. 
It would be worth to document this (and other settings via env vars) in the documentation.

**Comment by OlegWock** [comment]
@Bogdanp sorry to raise old issue, but I still can't wrap this around my head. I have 8 processes with 50 (gevent) workers in each of them. If I set `dramatiq_queue_prefetch` to one, will this result in 'handling one message per process at same time' or 'handling 50 messages per process at same time (1 per thread)'?

Thanks
