### ISSUE TITLE
in memory broker: how to use?

### ISSUE THREAD

**Issue by bitsofinfo** [Bogdanp/dramatiq#399]
Hi, reading the getting started guide under `comparisons` I see `In-memory broker support` listed

I'm trying to figure out how to use this for my use case where I simply want the caller, broker and workers all in memory on the same python program. Any examples of this out side of that `StubBroker` in a unit test?

**Comment by Bogdanp** [comment]
You'd use it like any of the other brokers. Just call `dramatiq.set_broker(StubBroker())` before defining your actors. For example, in the [basic example](https://github.com/Bogdanp/dramatiq/blob/4a6a803bdd66642b4783244716d62518b28b5aee/examples/basic/example.py#L8-L11) you'd change the highlighted lines to 

```python
from dramatiq.brokers.stub import StubBroker
dramatiq.set_broker(StubBroker())
```

**Comment by carlosporta** [comment]
Hello, @Bogdanp, can you help me?

I am trying to use an in-memory broker, but it does not act as I thought. Can you explain what is happening to me? This is my code:

```
from random import randint
import dramatiq
from dramatiq.brokers.stub import StubBroker

broker = StubBroker()
#Tried this but gives a runtime error on each error - RuntimeError: threads can only be started once
#broker.emit_after("process_boot") 
dramatiq.set_broker(broker)


@dramatiq.actor
def sum_numbers(a, b):
    print(f"{a} - {b} = {a + b}")
    return a - b


if __name__ == "__main__":
    sum_numbers.send(randint(0, 100), randint(0, 100))
```

I am executing this project on two different cmd (a producer and a consumer). 

Code for running the producer:
`python .\actors.py`

Code for running the consumer:
`dramatiq.exe actors:broker`
or 
`dramatiq.exe actors`

But the consumer does not read the tasks. Using a RabbitMQ broker work perfectly. What I am doing wrong? Does it have something related to RunTime error?

Thanks.

**Comment by nofalx** [comment]
Currently facing the same issue. When using StubBroker the consumer does not read the tasks and RabbitMQ broker work perfectly.  
Are there any other requirements to use  StubBroker?
