### ISSUE TITLE
[Class based actor]:  options defined in `Meta` does not work as expected 

### ISSUE THREAD

**Issue by lnever** [Bogdanp/dramatiq#400]
## What OS are you using?

macOs 11.2

## What version of Dramatiq are you using?

1.10.0

## What did you do?

I defined a `BaseActor` which has some options in its `Meta` class.

Then, I defined a `MyActor` inherit `BaseActor` which has its own `Meta` class

## What did you expect would happen?

`Actor` generated by `MyActor` will have all options defined in `MyActor` and `BaseActor`

## What happened?

`Actor` generated by `MyActor` has only options defined in `MyActor`

My test code:

```
from dramatiq import GenericActor


class BaseActor(GenericActor):
    class Meta:
        abstract = True
        on_failure = "failure_callback"
        queue_name = "base"


class MyActor(BaseActor):
    class Meta:
        priority = 100


if __name__ == '__main__':
    print("---------")
    print(MyActor.__actor__.options)
    print(MyActor.__actor__.priority)
    print(MyActor.__actor__.queue_name)

```

Test output:

```
---------
{}
100
default
```

**Comment by lnever** [comment]
I looked at the source code of `generic_actor` and found it will only get options with own `Meta`
```
    def __new__(metacls, name, bases, attrs):
        clazz = super().__new__(metacls, name, bases, attrs)
        meta = getattr(clazz, "Meta", object())
        if not getattr(meta, "abstract", False):
            options = {name: getattr(meta, name) for name in vars(meta) if not name.startswith("_")}
            options.pop("abstract", False)

            clazz_instance = clazz()
            actor_registry = options.pop("actor", actor)
            actor_instance = actor_registry(clazz_instance, **options)
            setattr(clazz, "__getattr__", generic_actor.__getattr__)
            setattr(clazz_instance, "__actor__", actor_instance)
            return clazz_instance

        setattr(meta, "abstract", False)
        return clazz
```

Maybe we can get options from its `bases` together?

**Comment by mjpieters** [comment]
I came here to report the same; the code looks like it should, **at the very least**, use `dir()` instead of `vars()`:

```python
            options = {name: getattr(meta, name) for name in dir(meta) if not name.startswith("_")}
```

Iterating over `vars(meta)` only gives you the names of the direct attributes, `dir(Meta)` gives you names of all attributes for the class and all base classes **and in the default implementation already skips attributes that start with `_`**:

```pycon
>>> class Base:
...     foo = "attribute of Base"
...     _spam = "attribute of Base with an underscore"
...
>>> class SubClass(Base):
...    bar = "attribute of SubClass"
...
>>> [name for name in vars(SubClass) if not name.startswith("_")]
['bar']
>>> dir(SubClass)
['bar', 'foo']
```

Using `dir()` at least lets you expilictly set your`Meta` class to inherit:

```python
class BaseActor(GenericActor):
    class Meta:
        abstract = True
        on_failure = "failure_callback"
        queue_name = "base"


class MyActor(BaseActor):
    class Meta(BaseActor.Meta):
        priority = 100
```

The next choice would be to walk the `clazz.__mro__` to collect attributes from all bases:

```python
            options = {}
            options = {
                name: getattr(cls.Meta, name)
                for cls in reversed(clazz.__mro__)
                for name in vars(getattr(cls, "Meta", object()))
                if not name.startswith("_")
            }
```

**Comment by Bogdanp** [comment]
I think this was a design mistake that I would be reluctant to change at this point b/c of the backwards-compatibility implications.
