### ISSUE TITLE
Worker list left in RedisDB after shutdown

### ISSUE THREAD

**Issue by rozahp** [Bogdanp/dramatiq#401]
Hi!

I am new to this fine library. Started testing this today with RedisBroker on Ubuntu 20.04.

During my testing the list of workers in Redis are updated fine (ttl=1000ms), but after shutdown the last worker-ids are still left. Is this normal behaviour or should I create some teardown code to clear the list in redis?

Running dramatiq under Python 3.x in a virtualenv. To view to workers and queues I use dramatiq_dashbord in a Flask app.

I run in the same Python environment:

dramatiq application.tasks

It works great, and then I hit CTRL-C and it shutdown the workers, but the worker list in Redis is not cleared. Starting dramatiq again adds new workers to the list. 

I can bring more details to the table if this is not a normal behaviour.

FLUSHDB clears the list.

Regards.

**Comment by Bogdanp** [comment]
Yes, this is normal. The list is only cleaned up when maintenance runs and maintenance only runs when there are live workers.
