### ISSUE TITLE
Question about intentional retries/rescheduling

### ISSUE THREAD

**Issue by docelic** [Bogdanp/dramatiq#402]
Hello,

I have a case where, when a task runs, in certain cases I would want it to run again at some later time.
This would be a programmed re-run/re-schedule at a specific time, and not something like a retry.
It doesn't matter if this same task would run again, or if a new/copy of the task would be created (although I would prefer the exact same task to be re-scheduled).

Is there a way to do it? Or what would be the best way to approach this?

Thanks!

**Comment by Bogdanp** [comment]
I would suggest using the [`CurrentMessage`](https://dramatiq.io/reference.html#dramatiq.middleware.CurrentMessage) middleware to grab the underlying message, then pass it to `get_broker().enqueue(message, delay=1234)` to schedule a new task with the exact same options and arguments.

**Comment by docelic** [comment]
Fabulous, thanks!
