### ISSUE TITLE
dramatiq-gevent TimeLimitExceeded exception fails to set

### ISSUE THREAD

**Issue by FinnLidbetter** [Bogdanp/dramatiq#403]
Raising thread exceptions fails when running workers with dramatiq-gevent. This affects the TimeLimitExceeded middleware (and anything using dramatiq.middleware.threading.raise_thread_exception). CRITICAL log lines are logged when the time limit is exceeded and the exception fails to set. Is this expected behaviour for running workers with gevent?

## Checklist

* [x] Does your title concisely summarize the problem?
* [x] Did you include a minimal, reproducible example?
* [x] What OS are you using?
* [x] What version of Dramatiq are you using?
* [x] What did you do?
* [x] What did you expect would happen?
* [x] What happened?

## What OS are you using?
Ubuntu 18.04

## What version of Dramatiq are you using?
1.11.0

## What did you do?
Run workers with dramatiq-gevent and TimeLimitExceeded middleware on a task that may take longer than the time limit. 

## What did you expect would happen?
If the task takes longer than the time limit, the task should timeout and the TimeLimitExceeded exception should be raised in the worker thread the next time that the thread acquires the GIL.

## What happened?
The exception fails to set.
```
[2021-06-01 11:16:26,234] [PID 11500] [Thread-1] [dramatiq.middleware.time_limit.TimeLimit] [WARNING] Time limit exceeded. Raising exception in worker thread 140492336214088.
[2021-06-01 11:16:26,235] [PID 11500] [Thread-1] [dramatiq.middleware.threading] [CRITICAL] Failed to set exception (TimeLimitExceeded) in thread 140492336214088.
```

## What gevent version are you using?
I am using the latest version, 21.1.2, but the issue also happens with older versions of gevent. 

## Reproducible example
Here is a minimal example to reproduce the issue if this code is copied into a file called `example_actor.py`:
```
"""
Run a rabbitmq broker.

Startup workers with
    dramatiq-gevent example_actor --processes 1 --threads 2
or
    dramatiq example_actor --processes 1 --threads 2

Run
    python example_actor.py
observe logs when running workers with dramatiq vs. dramatiq-gevent.

With dramatiq, the TimeLimitExceeded exception is raised in the thread
successfully.
With dramatiq-gevent, the TimeLimitExceeded exception fails to be raised and a
CRITICAL log line is logged.

The behaviour is identical if a redis broker is used instead.
"""

import time

import dramatiq
from dramatiq.brokers.rabbitmq import RabbitmqBroker


rabbitmq_broker = RabbitmqBroker(url='amqp://guest:guest@localhost')
dramatiq.set_broker(rabbitmq_broker)


@dramatiq.actor(time_limit=1000, max_retries=0)
def sample_actor(sleep_seconds):
    print('In actor. Sleeping for %d seconds' % sleep_seconds)
    # If sleep_seconds is more than time_limit, then the exception should be
    # set in the thread while it is sleeping.
    time.sleep(sleep_seconds)
    # If the exception was set, the remainder of the function should not
    # execute after sleeping is done (once the thread reacquires the GIL).
    some_list = []
    for i in range(1000000):
        some_list.append(i)
    # This line should not be printed if the time limit was exceeded.
    print(sum(some_list))


if __name__ == '__main__':
    sample_actor.send(10)
```

**Comment by Bogdanp** [comment]
Yes, I wouldn't expect the `TimeLimit` implementation to work under gevent as-is. Instead, you can use gevent's built-in [timeouts](https://www.gevent.org/api/gevent.timeout.html). I'd also happily accept a PR to add support for this in the `TimeLimit` middleware.

**Comment by FinnLidbetter** [comment]
Ok, thanks very much for the quick response! I will look into that and put up a PR if I get something working.

**Comment by Bogdanp** [comment]
Closing since the related PR has been merged.
