### ISSUE TITLE
message priority in queue.

### ISSUE THREAD

**Issue by newfriend1** [Bogdanp/dramatiq#41]
sometimes, we want to handle some messages as soon as possible.
but in dramatiq, priority is for actor, not for messages.

so I modify some code in `enqueue.lua` and `fetch.lua` for redis.

**enqueue.lua** 
 ```
-- enqueue(args=[queue_name, message_id, message_data])
-- This function stores a message in Redis and appends its id to a list.
--
-- ${queue_name} is a Redis list of message ids [message_1, message_2, message_3]
-- ${queue_name}.msgs is a hash of message ids to message payloads
-- ${queue_name}.acks is a zset of message ids scored by the timestamp
-- each message was pulled off the queue.
local queue_name = ARGV[1]
local message_id = ARGV[2]
local message_data = ARGV[3]
local priority = ARGV[4] or 0;

local queue_messages = queue_name .. ".msgs"

redis.call("zadd", queue_name, "NX", priority, message_id)
redis.call("hset", queue_messages, message_id, message_data)
```

**fetch.lua**

```
-- fetch(args=[queue_name, prefetch, timestamp])
-- This function fetches up to $prefetch number of messages for a
-- given queue.  All fetched messages are moved to the ack set.  The
-- timestamp is used to "score" each ack such that an external watcher
-- can efficiently move messages unacked some time prior to when it
-- runs back to their respective queues.
local queue_name = ARGV[1]
local prefetch = ARGV[2]
local timestamp = ARGV[3]

local queue_acks = queue_name .. ".acks"
local queue_messages = queue_name .. ".msgs"

local messages = {}
local message_ids = redis.call('ZREVRANGEBYSCORE', queue_name, '+inf', '-inf', 'LIMIT', 0, prefetch)

-- If items are popped from the list
if message_ids then
    for i, message_id in ipairs(message_ids) do
        redis.call("zadd", queue_acks, timestamp, message_id)
        redis.call('ZREM', queue_name, message_id)
        messages[i] = message_id
    end
end

if next(messages) == nil then
   return {}
else
   return redis.call("hmget", queue_messages, unpack(messages))
end
```

and it also needs to add a parameter in `broker.enqueue`.
so, let's me known what you think. will it be in your future plan?

**Comment by newfriend1** [comment]
this is a important feature in celery.
http://docs.celeryproject.org/en/latest/faq.html#does-celery-support-task-priorities

**Comment by Bogdanp** [comment]
I don't plan on supporting individual message priorities, atm, sorry!

You can emulate this with actors:


```python
LO = 10
HI = 0

@actor(priority=LO)
def normal(x):
  ...

@actor(priority=HI)
def vip(x):
  normal(x)
```

Call the VIP actor when you have a high priority message and call the other one otherwise.

**Comment by newfriend1** [comment]
@Bogdanp 
thanks for quick response.
but in your way, when lots messages not be processed in queue, the high priority message will not be delivered to worker as soon as possible.

**Comment by Bogdanp** [comment]
Apologies, you're right! I made a mistake in my example. It should have been:

```python
LO = 10
HI = 0

@actor(priority=LO)
def normal(x):
  ...

@actor(priority=HI, queue_name="VIP")
def vip(x):
  normal(x)
```

Note the separate queue on `vip`. This way, vip messages will be processed separately from normal messages and once they are pulled into memory, they will be processed before others because of the actor's priority. I'll make a note for myself to add this as an example to the cookbook, but this is the approach I would recommend.

**Comment by newfriend1** [comment]
ok, thanks, 
and this way is something like #35, and I will waiting for #35.

**Comment by newfriend1** [comment]
YES !
this is a way.
