### ISSUE TITLE
Declare actor on instance method

### ISSUE THREAD

**Issue by bsuhagia** [Bogdanp/dramatiq#413]
This is not an issue. I have an instance method that I want to run concurrently as an actor/worker. When running `process_request.send(service, url)`, I get `TypeError: Object of type 'Foo' is not JSON serializable`

`services.py`
```python
class Foo:
    def __init__(self, name):
        self.name = name
    
    def get_data(self, url):
        return requests.get(url)

class Bar:
    def __init__(self, name):
        self.name = name
    
    def get_data(self, url):
        return requests.get(url)
```

`tasks.py`
```python
import dramatiq

@dramatiq.actor
def process_request(cls_instance, url):
    data = cls_instance(url)
    save_data(data, cls_instance.name) 
```

`main.py`
```python
import services
from tasks import process_request

if __name__ == '__main__':
    if args[0] == 'foo':
        service = services.Foo('foo')
    else:
        service = services.Bar('bar')

    urls = [...]
    for url in urls:
        process_request.send(service, url)
```

**Comment by Bogdanp** [comment]
Right, as you say, this is expected. You shouldn't be sending instances over the wire. You can do it if you use the [`PickleEncoder`](https://dramatiq.io/reference.html#dramatiq.PickleEncoder) but I wouldn't recommend it.
