### ISSUE TITLE
No stacktrace with critical logs from worker

### ISSUE THREAD

**Issue by benekastah** [Bogdanp/dramatiq#42]
I'm getting the error message "Consumer encountered an error: 'NoneType' object has no attribute 'decode'", but there's no stack trace. How do you feel about adding `exc_info=True` into the `logger.critical` call in [`dramatiq.worker` line 217](https://github.com/Bogdanp/dramatiq/blob/84420dd11c0e4f45347e23e75e792756c884de1a/dramatiq/worker.py#L217)?

As to why the error is happening, I deleted some jobs from the delayed queue and I'm guessing there's still something in redis that knows about them, but I don't know what.

**Comment by Bogdanp** [comment]
> As to why the error is happening, I deleted some jobs from the delayed queue and I'm guessing there's still something in redis that knows about them, but I don't know what.

In addition to deleting the hashes, you need to remove the messages from the message list (the queue) and from the acks zset if any of them were in memory. You might've skipped the latter two. Take a look at https://github.com/Bogdanp/dramatiq/blob/master/dramatiq/brokers/redis/ack.lua I assume that's where stuff blows up.

I'll make this change tonight! Thanks for the suggestion.
