### ISSUE TITLE
Gevent support for Shutdown Notifications

### ISSUE THREAD

**Issue by FinnLidbetter** [Bogdanp/dramatiq#423]
The Shutdown Notifications middleware does not support gevent for the same reason as #403.
PR #408 has been merged and further commits have been added on top to tidy up that implementation introducing gevent support for the TimeLimit middleware (thanks Bogdan!).

It would be great to have gevent support for the Shutdown Notifications middleware too, and to be able to remove the xfail markers on the shutdown notifications tests with gevent.

I should have time in the next few weeks to try to put something together for this if you would like and accept a PR. I can try to emulate the _CtypesTimeoutManager, _GeventTimeoutManager structure used in the TimeLimit middleware.

**Comment by Bogdanp** [comment]
> I should have time in the next few weeks to try to put something together for this if you would like and accept a PR. I can try to emulate the _CtypesTimeoutManager, _GeventTimeoutManager structure used in the TimeLimit middleware.

That would be great!
