### ISSUE TITLE
`retries` counter does not increment on last retry

### ISSUE THREAD

**Issue by giuppep** [Bogdanp/dramatiq#425]
# Issues

GitHub issues are for bugs.  If you have questions, please ask them on the [discussion board](https://reddit.com/r/dramatiq).

## Checklist

* [x] Does your title concisely summarize the problem?
* [x] Did you include a minimal, reproducible example?
* [x] What OS are you using?
* [x] What version of Dramatiq are you using?
* [x] What did you do?
* [x] What did you expect would happen?
* [x] What happened?

## What OS are you using?

OS X 11.5.2

## What version of Dramatiq are you using?

1.11.0

## What did you do?

I'm trying to run a `on_failure` callback in combination with `retry`. As stated in the documentation, the `on_failure` callback will run after every retry. Therefore I added a check in the callback to only run after a certain number of retries:

```python
MAX_RETRIES = 3

@dramatiq.actor
def my_callback(message_data, exception_data):
    retries = message_data["options"]["retries"]
    if retries > MAX_RETRIES:
        print("handling the error")

@dramatiq.actor(max_retries=MAX_RETRIES, on_failure="my_callback")
def my_actor(*args, **kwargs):
    x = 1/0
```

## What did you expect would happen?

That the `my_callback` function would run exactly once.

## What happened?

`retries` never exceeds `MAX_RETRIES` and therefore the callback doesn't execute the actual handling code.
On the other hand, if I set `retries >= MAX_RETRIES` the callback gets executed *twice*.

## Proposal

I think this would be fixed by moving [this increment](https://github.com/Bogdanp/dramatiq/blob/master/dramatiq/middleware/retries.py#L103) before [this if block](https://github.com/Bogdanp/dramatiq/blob/master/dramatiq/middleware/retries.py#L97-L101). 

Happy to make a PR if you think that (a) this is in fact an issue and (b) the proposed solution makes sense.

PS. Thanks for the great library ;)

**Comment by Bogdanp** [comment]
I think your proposed solution sounds fine so feel free to open a PR!

**Comment by giuppep** [comment]
> I think your proposed solution sounds fine so feel free to open a PR!

Cool, submitted PR https://github.com/Bogdanp/dramatiq/pull/429 :)
