### ISSUE TITLE
SIGHUP on main process startup can result in orphaned workers

### ISSUE THREAD

**Issue by FinnLidbetter** [Bogdanp/dramatiq#441]
If a SIGHUP is received on the main process after the worker processes have started up, but before the signal handler is defined, then a SIGHUP (or SIGTERM, I think) can cause the worker processes to be left behind, still running, but without a main process monitoring them.

This is more of an edge case that is not a big deal to me, but I thought I would flag it anyway. It came about from testing a custom middleware similar to the example MaxTasksPerChild middleware that signals the main process with SIGHUP. This shouldn't be an issue for anyone writing their own middleware that signals the main process, since I think it would be impossible to have a middleware trigger a SIGHUP before the signal handler is defined on the main process. But it could be an issue for anyone with an external process that SIGHUPs dramatiq based on some condition---although perhaps the onus should be on them to not send the Dramatiq main process a SIGHUP too close to a startup/restart?

## What OS are you using?

Ubuntu 20.04

## What version of Dramatiq are you using?

1.11.0

## What did you do?

1. Start a Dramatiq main process
2. Send several SIGHUP signals to the Dramatiq main process in quick succession (can be done manually with a terminal---it doesn't need to be so fast that the SIGHUPs need to be triggered programmatically in a tight loop)

## What did you expect would happen?

Dramatiq would either restart gracefully, ignore signals, or terminate gracefully.

## What happened?

The Dramatiq main process exited and new Dramatiq workers were left behind without a main process managing them. These workers were still able to pick up work from the queues.

**Comment by Bogdanp** [comment]
There is code in the `cli` module to block signals (see the calls to `pthread_sigmask`) until the handlers get set up, but maybe it needs to be moved up higher. Let me know if you want to take a stab at it. If not, I'll take a look eventually.

**Comment by FinnLidbetter** [comment]
Ok sure, I'd be happy to try to fix it as you suggest. Thanks
