### ISSUE TITLE
Environmental Variables and Worker Relay Race Problem

### ISSUE THREAD

**Issue by bai-yi-bai** [Bogdanp/dramatiq#454]
I'm a new user who is suffering from what I can describe as a relay race baton problem. Despite adding multiple workers to a queue, all the tasks are being assigned to only worker at a time. I cannot get tasks to run in parallel.

These tasks take a long time to complete and can only be run one at a time on a system. My intention was to distribute the tasks so that I could leverage multiple computers. Luckily, each task is independent and can be performed in any order. 

my_task relevant code:
`redis_broker_address = "{ip}"
broker = RedisBroker(host=redis_broker_address) 
result_backend = RedisBackend(url=f"redis://{redis_broker_address}:6379")
broker.add_middleware(Results(backend=result_backend))
dramatiq.set_broker(broker)`

I execute the dramatiq command from multiple Windows machines to get workers to join (no queue specified): 
`dramatiq my_task --processes 1 --threads 1` 
All the machines are operating off the same shared folder and there is effectively one actor in the my_task script.

Finally, I use a separate my_task_controller script to send task messages.

Initially, I fill the queue with as many messages as there are machines (this is manually entered). Then, I use the results() library with a _while_ loop. Once a task is completed and returned, it sends a new message. This keeps the queue full (one task per machine).

I observe two types of behavior:

1. All the tasks are assigned to one worker. This fails since the first part of my task is to set up the system and report back the machine's parameters. This also baffles me, if there are 6 workers and 6 tasks, each worker should get 1 task, right?
2. If I reduce the number of workers (for example 2), or send fewer messages, the tasks are still only assigned to one machine at a time, but will jump from one machine to a different machine and then back.
3. Also - nothing happens if I try to run an additional instance of my_task_controller. The messages don't seem to get picked up by the workers.

Questions:

- Am I somehow resetting the redis broker each time I call launch the dramatiq command or when I send a message using my_controller_script? Is this why the 'baton' is passed from machine to machine?
- How/where do I set environmental variables? I think I have to set the dramatiq_queue_prefetch to 1 (or better yet .5) so that each worker only takes one message at a time.

https://github.com/Bogdanp/dramatiq/blob/a588753d54a41fe12fd2af3dd103978bb0e6a171/dramatiq/worker.py#L46

- Is there a way to query the Redis broker to see how many workers are registered? I would like to dynamically add tasks (one per worker) as they are brought online or offline, rather than statically setting the number at the beginning.

**Comment by Bogdanp** [comment]
For high throughput, workers prefetch messages by default. That works out fine if your actors are fast, but is not ideal in cases like yours. In your case, you should set the `dramatiq_queue_prefetch` env var to `1` so that each worker prefetches a single message at a time per queue. As far as how to set environment variables, that'll depend on your platform, but search engines are your friend here!

> Is there a way to query the Redis broker to see how many workers are registered? I would like to dynamically add tasks (one per worker) as they are brought online or offline, rather than statically setting the number at the beginning.

See [dispatch.lua](https://github.com/Bogdanp/dramatiq/blob/a588753d54a41fe12fd2af3dd103978bb0e6a171/dramatiq/brokers/redis/dispatch.lua#L24-L43), though note that this structure can change with new releases.

**Comment by bai-yi-bai** [comment]
Wow, setting the environmental variables did the trick! 

I'm really glad I came and asked the question, otherwise I would not have been able to figure out that the problem was that up to 1000-2000 jobs were being fetched by the first worker which could get to them. This is really bad when I was only putting 2-6 jobs on the queue.

It might help to write out "1000" instead of "one-thousand" in this line:
https://github.com/Bogdanp/dramatiq/blob/a588753d54a41fe12fd2af3dd103978bb0e6a171/dramatiq/worker.py#L49

It would also be very helpful to know in the getting started portion of the  documentation that a worker will prefetch a lot of jobs.

### Windows Environment Variable Fix

I didn't realize this was a OS setting, I thought it was something that had to be declared another way. My workers run in Microsoft Windows. I encountered problems documented in many places on the Internet.

- I couldn't set them from the .bat file I use to launch dramatiq. (cmd.exe needs to be restarted after setting environment variables, after that it seemed to work correctly).
- I couldn't set them from the my_task os.getenv['dramatiq_queue_prefetch '] = 1 due to permissions.
- I also couldn't get PyCharm venv terminal to pick up these settings.

### Dead end - named queues per worker
I also wanted to share the first idea I had which got a test script working, but turned out to be a dead end. This will be clear to you, but it also might help people who encounter this problem in the future. I thought about declaring a queue_name for each machine based upon the machine's IP addresses. For example "_192.168.1.20".  However, I realized that this wouldn't work because I'd need to duplicate each actor function and modify the decorator for each machine's IP address. However, this showed me that concurrent, parallel code execution was working.
