### ISSUE TITLE
Add compatibility with redis-py 4.x

### ISSUE THREAD

**Issue by tonycosentini** [Bogdanp/dramatiq#457]
# Issues

GitHub issues are for bugs.  If you have questions, please ask them on the [discussion board](https://reddit.com/r/dramatiq).

## What OS are you using?

macOS

## What version of Dramatiq are you using?

v1.12.0

## What did you do?

I'd like to use redis-py version 4.0.2 in a project that also uses Dramatiq.

## What did you expect would happen?

The two dependencies can be installed in the same project.

## What happened?

Dramatiq only supports redis-py 2.x and 3.x.

**Comment by tonycosentini** [comment]
Just opening this issue in case anyone else comes looking.

I opened a PR for this here - https://github.com/Bogdanp/dramatiq/pull/456

**Comment by Bogdanp** [comment]
Merged. Thanks!
