### ISSUE TITLE
Dramatiq probably doesn't do at-least-once delivery

### ISSUE THREAD

**Issue by aphyr** [Bogdanp/dramatiq#46]
Hi there!

It looks like there are two backend stores for Dramatiq: Redis and RabbitMQ. Neither of these systems provides at-least-once delivery; both can lose committed updates when the network fails, nodes pause, or, in some cases, when processes crash. If you're relying on these systems to provide durable queuing (instead of, say, implementing your own replication mechanism across independent RabbitMQs or Redices), it might be a bit optimistic to claim that Dramatiq delivers messages at least once.

**Comment by Bogdanp** [comment]
Thanks! I've updated the docs to clarify/relax those claims and will deploy the changes later today. 

RMQ does [claim](https://www.rabbitmq.com/reliability.html) to guarantee at-least-once delivery if acknowledgements are turned on, though. Any chance we'll see another Jepsen post on RMQ in the future? :)

**Comment by aphyr** [comment]
Ah, yeah, the docs have gotten... less clear about this, haven't they? https://www.rabbitmq.com/partitions.html hints at the problem:

> While a network partition is in place, the two (or more!) sides of the cluster can evolve independently, with both sides thinking the other has crashed. Queues, bindings, exchanges can be created or deleted separately. Mirrored queues which are split across the partition will end up with one master on each side of the partition, again with both sides acting independently. Other undefined and weird behaviour may occur.

but doesn't explicitly acknowledge message loss. I know they're working on adding a Raft implementation to provide better guarantees.

**Comment by eddified** [comment]
So, is it correct to say that Dramatiq still doesn't guarantee at-least-once delivery?
