### ISSUE TITLE
Version 1.12.3 not released on PyPI

### ISSUE THREAD

**Issue by jsmitka** [Bogdanp/dramatiq#467]
According to GitHub releases and changelog (https://dramatiq.io/changelog.html), 1.12.3 should be the latest version. However, PyPI lists 1.12.2 as the latest version and version history does not show 1.12.3: https://pypi.org/project/dramatiq/#history

Could you please upload the latest version?

**Comment by Bogdanp** [comment]
Done! Sorry about that, I must've accidentally re-uploaded 1.12.2 last time.
