### ISSUE TITLE
Don't configure logging

### ISSUE THREAD

**Issue by roganov** [Bogdanp/dramatiq#48]
Please provide an option to disable all logging configuration (or better detect if users configured logging themselves as flask does http://flask.pocoo.org/docs/dev/logging/).

**Comment by LasseGravesen** [comment]
Also interested in this, as the workers are really noisy.

**Comment by bersace** [comment]
To detect logging setup, i usually do `if logging.getLogger().handlers`.

**Comment by davidt99** [comment]
I was able to setup the workers logging but not the main process and after looking at the code, it doesn't seem possible since there no user code that runs on the main process.
I was thinking to add an option to provide the logging module, and load it using `importlib`. @Bogdanp what do you think?

**Comment by Bogdanp** [comment]
The new `--skip-logging` flag added in #263 should be useful here.
