### ISSUE TITLE
Video intro on frontpage cannot be followed using [redis]

### ISSUE THREAD

**Issue by kurtmckee** [Bogdanp/dramatiq#483]
# Issues

GitHub issues are for bugs.  If you have questions, please ask them on the [discussion board](https://reddit.com/r/dramatiq).

## Checklist

* [x] Does your title concisely summarize the problem?
* [x] Did you include a minimal, reproducible example?
* [x] What OS are you using?
* [x] What version of Dramatiq are you using?
* [x] What did you do?
* [x] What did you expect would happen?
* [x] What happened?

## What OS are you using?

Ubuntu 21.04

## What version of Dramatiq are you using?

1.12.3

## What did you do?

I installed dramatiq using the `[redis]` extras:

```
pip install dramatiq[redis,watch]
```

I then used the same `count_to()` code as presented at the beginning of the video.

## What did you expect would happen?

I expected that dramatiq would connect to redis based on these assumptions:

* I installed the [redis] extras, not [rabbitmq]
* No configuration is shown to be required in the video

## What happened?

Python displayed a traceback showing that the `pika` library could not be imported.

This is happening because `dramatiq.broker.get_broker()` assumes that if no broker has been configured, RabbitMQ should be used. However, it does not guard against import errors.

This type of situation is also not caught by the unit tests because tox does not have different environments configured for different extras dependencies.

I installed pika, which prevented the traceback, but I got frequent screen output showing that there were connection failures every few seconds.

## Suggested solution

I'd like to submit a PR that introduces redis as a fallback if `pika` is not installed. If that seems reasonable I'll work to get that done and submitted for review.

This is entirely for making it possible to follow the tutorial using redis instead of RabbitMQ! I learned how to configure the broker to prevent the automatic fallback to RabbitMQ, so I'm not blocked. I just want to improve others' first experience with the library.

Thanks for all of your work on dramatiq!

**Comment by Bogdanp** [comment]
Your suggestion sounds good to me, so feel free to go ahead and make a PR!

**Comment by kurtmckee** [comment]
Okay, great! I'll give it a shot! :grinning: :+1:
