### ISSUE TITLE
Seems like dramatiq works as LIFO or with random instead of broker FIFO principle

### ISSUE THREAD

**Issue by rive-n** [Bogdanp/dramatiq#489]
# Issues

Seems like dramatiq not working as FIFO.

## Checklist

* [+] Does your title concisely summarize the problem?
* [+] Did you include a minimal, reproducible example?
* [+] What OS are you using?
* [+] What version of Dramatiq are you using?
* [+] What did you do?
* [+] What did you expect would happen?

## What OS are you using?

```
ProductName:	macOS
ProductVersion:	12.1
BuildVersion:	21C52
```

## What version of Dramatiq are you using?

1.13.0

## What did you do?

Let's say we got 2 files. 
`worker_logic.py`:
```python
from dramatiq import actor
from time import sleep
import requests

from dramatiq.brokers.rabbitmq import RabbitmqBroker
from pika import PlainCredentials
creds = PlainCredentials('guest', 'guest')
rabbitmq_broker = RabbitmqBroker(host="127.0.0.1", credentials=creds)


@actor()
def test_actor(*args, **kwargs):
    que = kwargs['iteration']
    print(que)
    requests.get(f"http://somehost/?sec={que}")

```

and `main.py`
```
from worker_logic import test_actor

test_actor.send(iteration=1)
test_actor.send(iteration=2)
```

I want dramatiq to shedule task in FIFO order, like queue always presents. By default dramatiq uses a lot of thread, so it's basically unreal. But with this command for worker: ` dramatiq --processes 1 --threads 1 worker_logic` this could work. Insted of FIFO i get LIFO: 
![image](https://user-images.githubusercontent.com/45512613/169820606-67e027b5-24d6-42ff-a376-9f7bcda63357.png)

## What did you expect would happen?

I expect FIFO order for FIFO Queue. 
Like, for example: 1 and after 2.

**Comment by Bogdanp** [comment]
See https://github.com/Bogdanp/dramatiq/blob/38099905a12811ccb349449d68dd9a501f64a900/dramatiq/worker.py#L46 . Setting the prefetch value to `1` should help with this, beyond that it'll depend on the broker.

**Comment by rive-n** [comment]
> See
> 
> https://github.com/Bogdanp/dramatiq/blob/38099905a12811ccb349449d68dd9a501f64a900/dramatiq/worker.py#L46
> 
> . Setting the prefetch value to `1` should help with this, though it'll be bad for throughput. Beyond that, it'll depend on the broker.

Wow, I've never seen such a quick response to an issue. Thank you very much, I tried it - it works :)
Is it possible to add information about these subtleties in the documentation, so that I don't have to read a lot of code later?
