### ISSUE TITLE
Message metadata

### ISSUE THREAD

**Issue by roganov** [Bogdanp/dramatiq#49]
For tracing purposes I would like to pass some additional metadata with each message.

**Comment by Bogdanp** [comment]
You can do this by defining your own [middleware]:

```python
from dramatiq import Middleware

class MetadataMiddleware(Middleware):
  @property
  def actor_options(self):
    return {"metadata"}

  # implement one of the lifecycle methods
```

Then when you enqueue messages you can pass `metadata`:

```python
some_actor.send_with_options(metadata={"foo": 42})
```

[middleware]: https://dramatiq.io/reference.html#middleware
