### ISSUE TITLE
Changelog missing for latest version

### ISSUE THREAD

**Issue by kviktor** [Bogdanp/dramatiq#493]
There seems to be a new release on PyPi https://pypi.org/project/dramatiq/#history but no info about it in the changelog https://dramatiq.io/changelog.html (and Github releases https://github.com/Bogdanp/dramatiq/releases).

It seems like the changelog is there in the repo just not generated on the website https://github.com/Bogdanp/dramatiq/blob/master/docs/source/changelog.rst

**Comment by Bogdanp** [comment]
Both are now updated. Thanks!
