### ISSUE TITLE
How-to specify actors default options

### ISSUE THREAD

**Issue by academe-01** [Bogdanp/dramatiq#494]
Hi!
Does anyone have any ideas how to specify default actor options that apply to all actors?

**Comment by Bogdanp** [comment]
You can create a partially-applied decorator with [`functools.partial`](https://docs.python.org/3/library/functools.html#functools.partial) and use that everywhere:

```python
>>> from dramatiq import actor
>>> from functools import partial
>>> my_actor = partial(actor, max_retries=5)
>>> my_actor
functools.partial(<function actor at 0x1065f5e50>, max_retries=5)
>>> @my_actor
... def foo():
...  pass
...
```

Please use the mailing list for questions in the future.

**Comment by academe-01** [comment]
@Bogdanp 
Much appreciated Bogdan !
