### ISSUE TITLE
Actors with at-most-once delivery

### ISSUE THREAD

**Issue by dp-alvarez** [Bogdanp/dramatiq#497]
I need at-most-once delivery for my project, which is not supported by Dramatiq by default. Even with retries set to zero, a message will be retried if a worker goes offline before acking/nacking it.

I implemented this simple Middleware to ack messages before work on them starts.
In the shape it is now it causes a double ack/nack on finished messages which is harmless (apart from a warning when using RabbitMQ) and doesn't generate dead-letters.

I'm posting it here in case you want to add it to the cookbook docs, should someone else need at-most-once delivery,
If you are interested in merging something similar I could work on a more robust solution.

```python
from contextlib import suppress
from time import sleep
from dramatiq import Middleware, ActorNotFound, get_broker, actor
from dramatiq.worker import _WorkerMiddleware

class AtMostOnce(Middleware):
    def __init__(self):
        self.worker = None

    @property
    def actor_options(self):
        return {"at_most_once"}

    def before_process_message(self, broker, message):
        with suppress(ActorNotFound):
            actor = broker.get_actor(message.actor_name)
            if actor.options.get("at_most_once", False):
                self.worker.consumers[message.queue_name].post_process_message(message)

    def before_worker_boot(self, broker, worker):
        self.worker = worker


get_broker().add_middleware(AtMostOnce())

@actor(max_retries=0, at_most_once=True)
def stall():
    print(f"stalling...")
    sleep(30)
    print(f"done stalling")

stall.send()
```

**Comment by Ridder90** [comment]
How/Why does this work? It is probably me, but I don't see how this prevents double posting? If `at_most_once=True` It will directly go to post_process_message. Doesn't that happen in the default setup?

**Comment by dp-alvarez** [comment]
Honestly I don't quite remember why I'm was suppressing ActorNotFound. Would have to walk thru the code again to see if this exception could actually be raised there.

This acks the message, but it causes a double ack or ack followed by nack, both are harmless last I checked.

**Comment by Ridder90** [comment]
Is the warning you are talking about `[dramatiq.brokers.rabbitmq._RabbitmqConsumer] [WARNING] Failed to ack message: not in known tags.` ?

**Comment by dp-alvarez** [comment]
Yes, that one. No other side effects as far as I can tell (other than not generating dead letters), but I haven't tested it extensively or with other middlewares.
