### ISSUE TITLE
actor declare on a method or classmethod

### ISSUE THREAD

**Issue by jssuzanne** [Bogdanp/dramatiq#5]
Hi,

This is not a bug but a wish, I would use the decorator actor on a method or a classmethod have you a solution ?

exemple:
```

class foo:
    @dramatiq.actor()
    def count_worlds(url):
          pass

```

**Comment by Bogdanp** [comment]
`staticmethod`s ought to work:

```python
class Foo:
  @staticmethod
  @dramatiq.actor
  def count_words(url):
     pass
```
 
Can you tell me a little bit about what your use case is/why you need this? I can probably support classmethods (there's no way to support instance methods), but I'm not convinced this is necessary.

**Comment by jssuzanne** [comment]
I prefere classmethod: because some properties come from the class. 

My use case is to integrate dramatiq with [AnyBlok](https://pypi.python.org/pypi/AnyBlok). 

The goal of AnyBlok is to defined Models and / or overload existing Models. Put the actor on the method allow to overload them in the spirit of AnyBlok.

I know, I have a particular use case.

**Comment by franckbret** [comment]
Hi,
Looks like class method would be a nice step. Will give code separation per class and easy overloading / inheritance if needed.

**Comment by Bogdanp** [comment]
I've thought about this and I came to the conclusion that the downsides of supporting something like (extra complexity, obfuscation of which actor might process which message) this outweigh the benefits (polymorphism). That said, here's what you can do:

1. declare your tasks as normal classmethods

`tasks.py`:

```python
class Foo:
    @classmethod
    def do_work(cls, url):
      print(cls, url)


class Bar(Foo):
    pass
```

2. have a generic actor that knows how to call classmethods

`deferred.py`:

```python
import dramatiq
import importlib


@dramatiq.actor
def process_deferred_method(method_path, *args, **kwargs):
    class_path, _, method_name = method_path.rpartition(".")
    module_path, _, class_name = class_path.rpartition(".")
    module = importlib.import_module(module_path)
    method = getattr(getattr(module, class_name), method_name)
    return method(*args, **kwargs)


def defer(method, *args, **kwargs):
    assert method.__self__.__module__ != "__main__
    method_path = ".".join([
        method.__self__.__module__,
        method.__self__.__name__,
        method.__name__,
    ])
    return process_deferred_method.send(method_path, *args, **kwargs)
```

3. use that actor to run your classmethods

`main.py`:

```python
from .deferred import defer
from .tasks import Foo, Bar

defer(Foo.do_work, "https://example.com")
defer(Bar.do_work, "https://google.com")
```

You could expand on this pattern and create a `@classmethod_actor` decorator if you prefer

**Comment by jssuzanne** [comment]
Hi, I solved my issue. I replace the classmethod by an Actor after the declaration of the class. It is not the wonderful solution but it is enough.

Thank for your quick answer. your idea help me to found my solution.

For other use case, I think that the classmethod_actor could be a good feature. I let open this question, but you can close it.

**Comment by Bogdanp** [comment]
Sounds good. Glad you worked it out!

**Comment by Bogdanp** [comment]
@jssuzanne would the solution I proposed [here](https://github.com/Bogdanp/dramatiq/issues/9#issuecomment-344397842) also solve your issue?

**Comment by jssuzanne** [comment]
No, I reallly need a classmethod. But I solved my issue.

**Comment by jssuzanne** [comment]
This an exemple
i```
mport re
from dramatiq import get_broker, Actor

_queue_name_re = re.compile(r"[a-zA-Z_][a-zA-Z0-9_-]*")


def actor(fn=None, *, actor_name=None, queue_name="default", priority=0, broker=None, **options):
    actor_name = actor_name or fn.__name__
    if not _queue_name_re.fullmatch(queue_name):
        raise ValueError(
            "Queue names must start with a letter or an underscore followed "
            "by any number of letters, digits, dashes or underscores."
        )

    broker = broker or get_broker()
    invalid_options = set(options) - broker.actor_options
    if invalid_options:
        raise ValueError(
            f"The following actor options are undefined: {', '.join(invalid_options)}. "
           "Did you forget to add a middleware to your Broker?"
        )

    _fn = fn
    if not (hasattr(_fn, '__self__') and _fn.__self__):
        raise ValueError("It is not a classmethod")

    def _fn(*a, **kw):
        return fn(*a, **kw)

    _fn.__name__ = fn.__name__

    a = Actor(
        _fn, actor_name=actor_name, queue_name=queue_name,
        priority=priority, broker=broker, options=options,
    )

    setattr(fn.__self__, fn.__name__, a)


class Test:

    @classmethod
    def add(cls, name):
        return name


print(Test.add)
actor(Test.add)
print(Test.add)
print(Test.add('plop'))

```
I don't use the decorator, because with a decorator you have not the `fn.__name__`. Then the classmethod is replaced by the actor on a wrapper of the real classmethod

**Comment by Bogdanp** [comment]
I see. Thanks for the example!
