### ISSUE TITLE
`middleware.Pipelines` not included in API reference

### ISSUE THREAD

**Issue by rpkilby** [Bogdanp/dramatiq#50]
The pipeline middleware is not included in the reference docs, so the only way to learn about `pipe_ignore` and `pipe_target` is in the [cookbook](https://dramatiq.io/cookbook.html#pipelines).

**Comment by Bogdanp** [comment]
Good catch! Fixing now, thanks!

**Comment by rpkilby** [comment]
Thanks!

**Comment by Bogdanp** [comment]
Released: https://dramatiq.io/reference.html#dramatiq.middleware.Pipelines

Thanks again!
