### ISSUE TITLE
RabbitMQ broker doesn't seem to retry publishing on SSL socket errors

### ISSUE THREAD

**Issue by shshe** [Bogdanp/dramatiq#507]
# Issues

GitHub issues are for bugs.  If you have questions, please ask them on the [discussion board](https://reddit.com/r/dramatiq).

## Checklist

* [x] Does your title concisely summarize the problem?
* [x] Did you include a minimal, reproducible example?
* [x] What OS are you using?
* [x] What version of Dramatiq are you using?
* [x] What did you do?
* [x] What did you expect would happen?
* [x] What happened?

## What OS are you using?

Ubuntu 20.04 and MacOS 12.6

## What version of Dramatiq are you using?

Dramatiq 1.1.13

## What did you do?

Enqueue messages over a long running process.

## What did you expect would happen?

Messages should be published reliably.

## What happened?

We've recently migrated to a RabbitMQ deployment on AmazonMQ and connect over SSL (where as previously it was plain text). We're seeing the following error occasionally:

```
Socket EOF; <ssl.SSLSocket fd=32, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('x.x.x.x', 40536)>
```

We have a Django and Dramatiq deployment where both the Django and Dramatiq workers can publish messages. We've seen StreamLostErrors appear in our logs on long running processes, but have filtered them out assuming that Dramatiq's underlying retry mechanism will reopen the connection based on this Github Issue:
https://github.com/Bogdanp/django_dramatiq/issues/85

I believe this is where pika is raising the SSL error:
https://github.com/pika/pika/blob/main/pika/adapters/utils/io_services_utils.py#L794-L797

Browsing through the code, it looks like Dramatiq doesn't handle the SSL error, only subclasses of AMQPConnectionError or AMQPChannelError:
https://github.com/Bogdanp/dramatiq/blob/master/dramatiq/brokers/rabbitmq.py#L341-L354

**Comment by arkhodakov** [comment]
It's an old ticket, but maybe it can be helpful for somebody.

Actually, `dramatiq` handles the specified error using error classes `AMQPConnectionError` and `AMQPChannelError`. It also retries the connection afterwards. The errors are logged by internal `pika` loggers and can only be silenced.

To not silence all `pika` errors, I'm using a context manager that silences errors temporarily. `loguru` is used to configure logging.

``` python
import logging
from loguru import logger

class LoggerSilencer:
    """Context manager to temporarily silence loggers.

    Attributes:
        loggers: The list of loggers to silence (by names)
        level: The level name or severity with which the message should be logged
    """

    def __init__(self, loggers: str | list[str], level: str | int = "ERROR") -> None:
        self.loggers = loggers if isinstance(loggers, list) else [loggers]
        self.level = level
        self.levels: dict[str, int] = {}

        levels: list[str] = list(logger._core.levels.keys())  # type: ignore
        if level not in levels:
            raise ValueError(f"Invalid level name: {level}. Must be one of: {levels}")

    def __enter__(self):
        for logger_name in self.loggers:
            logger = logging.getLogger(logger_name)
            self.levels[logger_name] = logger.level

            logger.handlers = [InterceptHandler()]
            logger.setLevel(self.level)

    def __exit__(self, exc_type, exc_val, exc_tb):  # noqa: ANN001
        for logger_name, level in self.levels.items():
            logger = logging.getLogger(logger_name)
            logger.setLevel(level)
```

Use it when you enqueue a message:

``` python
with LoggerSilencer(loggers="pika", level="CRITICAL"):
    dramatiq.get_broker().enqueue(message)
```

**Comment by spumer** [comment]
Looks like you need restore handlers too, not only level

**Comment by Bogdanp** [comment]
Closing since this is just pika being overly verbose w/ its logging.
