### ISSUE TITLE
Feature request: aborting messages

### ISSUE THREAD

**Issue by rpkilby** [Bogdanp/dramatiq#51]
Would it be possible to abort messages by ID? Similar to celery's [task revocation](http://docs.celeryproject.org/en/latest/userguide/workers.html?highlight=revoke#revoke-revoking-tasks). Optionally, the [feature matrix](https://dramatiq.io/motivation.html#compared-to) could be updated to reflect that task cancellation isn't supported.

**Comment by rpkilby** [comment]
Whoops, duplicate of #37.

**Comment by Bogdanp** [comment]
Reopening this because enough people have requested it thus far that I'm likely to add it.

**Comment by virusdefender** [comment]
I think it's an important feature, waiting~

**Comment by b1ngz** [comment]
Revoking tasks is useful, any plan to add it?

**Comment by Bogdanp** [comment]
I'm closing this since [dramatiq-abort](https://flared.github.io/dramatiq-abort/) implements this functionality.

**Comment by ToGoBananas** [comment]
@Bogdanp Hi, any plans to implement cancelling for dramatiq-gevent?

I am getting [CRITICAL] Failed to set exception (Abort) in thread

**Comment by olegstepura** [comment]
> I'm closing this since dramatiq-abort implements this functionality.

`dramatiq-abort` only allows to cancel tasks if using redis backend. RabbitMQ case seem to be not covered still.
