### ISSUE TITLE
New release, please!

### ISSUE THREAD

**Issue by anton-petrov** [Bogdanp/dramatiq#514]
Hi, @Bogdanp! 
Maybe it's time to release a new version of [dramatiq](https://github.com/Bogdanp/dramatiq)? 
Python 3.11 was released not too long ago -- it would be great to have a version compatible with modern python 😎
Of course, we can install a package with reference to a specific commit, but it's still better and more convinient to get dramatiq from PyPi, for example, v1.14.0.

**Comment by orsinium** [comment]
+1, I'd like to have released the [mypy support I contributed](https://github.com/Bogdanp/dramatiq/pulls?q=is%3Apr+author%3Aorsinium+is%3Aclosed). Our codebase is huge and relies on dramatiq a lot, and type-checking all task calls would be great.

**Comment by orsinium** [comment]
It's been 8 months or so since the last release 👀

**Comment by nguaman** [comment]
+1

**Comment by Bogdanp** [comment]
I will release the new version when I have the bandwidth to do so. In the mean time, you can install the latest version from Git if you like. Opening issues like these, and especially piling on with "+1", only serves to distract and annoy me.

**Comment by nguaman** [comment]
@Bogdanp Calm down. The +1 is to note that there are several people expecting a new version, nothing more. It is not to irritate you or to annoy you.

Since 8 months have passed since the last release, and it seems that the project died or is not maintained.

Have a good weekend and rest.

**Comment by orsinium** [comment]
Sorry for bothering you, we meant no offense. The reactions and comments here are to give a bit of transparency on how much this particular change (in this case, uploading a release) is needed for the community. And so happened that uploading a release is one of a few things that we can't contribute, only ask.
