### ISSUE TITLE
How to make Dramatiq return a GUID when send() so the result can be retrived later by async polling?

### ISSUE THREAD

**Issue by staticdev** [Bogdanp/dramatiq#518]
# Issues

GitHub issues are for bugs.  If you have questions, please ask them on the [discussion board](https://reddit.com/r/dramatiq).

## Checklist

* [x] Does your title concisely summarize the problem?
* [x] Did you include a minimal, reproducible example?
* [x] What OS are you using?
* [x] What version of Dramatiq are you using?
* [x] What did you do?
* [x] What did you expect would happen?
* [x] What happened?

## What OS are you using?

N/A.

## What version of Dramatiq are you using?

1.13.0

## What did you do?

Read the user guide and it is not clear how to fulfill the following requirement:
* I have an API that POST some job in a Redis queue through dramatiq actor send(). The caller of this endpoint should receive a **GUID** (universal job id) from the job.
* I have a GET endpoint that you can pass the GUID and check the status of the actor (if it is finished), and if yes, what is the result.

I understand the Result backend is not specifically made for this case, but do you envision a what of how should this be implemented with dramatiq?

## What did you expect would happen?

N/A.

## What happened?

N/A.

**Comment by jkgenser** [comment]
Generate the GUID, pass it to the actor.send as an argument then in your actor code, at the end call save(GUID) to a result store system, eg redis
