### ISSUE TITLE
FeatReq: Support timedelta for delays?

### ISSUE THREAD

**Issue by dragonpaw** [Bogdanp/dramatiq#522]
In GoLang they have a Duration class that is actually pretty nifty. Instead of passing a int of seconds to sleep, you pass a Duration. Python's similar timedelta class doesn't get much love, but I enjoy using it in place of ints for time within my own code a lot. I notice in Dramatiq, the code wants timeouts and delays passed as millis, which makes sense, but isn't intuitive perhaps from the hinting. So I was wondering if Dramatiq could also accept timedeltas and use those, as there's no ambiguity in them. (While still treating ints as millis for backwards compatibility.)

It'd look something like this:
```python
actor.send_with_options(args=(url), delay=timedelta(seconds=2))
```

And within the code it's just:
```python
def send_with_options(
    self, *,
    args: tuple = (),
    kwargs: Optional[Dict[str, Any]] = None,
    delay: Optional[Union[datetime.timedelta,int]] = None,
    **options,
) -> Message[R]:
    if isinstance(delay, timedelta):
        delay = delay.total_seconds() * 1000
```

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/Bogdanp/dramatiq/issues/522">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/Bogdanp/dramatiq/issues/522/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/Bogdanp/dramatiq/issues/522/pledge.svg">
</picture>
</a>

**Comment by odigity** [comment]
I like it.

Since you've already written the code, how about opening a PR for it?  (and maybe a test or two)  Looks like the maintainer already has his hands full...

**Comment by Bogdanp** [comment]
I think this is a good idea and a PR would be appreciated.

**Comment by arseniiarsenii** [comment]
Hi, @h3nnn4n, I noticed, that the changes are not consistent with other parts of the project which also accept delays in milliseconds. timedelta should also be acceptable as:

- actor's min_backoff parameter
- actor's max_backoff parameter
- dramatiq.errors.Retry exception's 'delay' argument

These are some places that come to my mind, there are probably more of them.

Otherwise, thanks for the PR!

**Comment by Bogdanp** [comment]
I think the request here has been covered so I'm going to close this for now. If someone wants to extend the other places where we could use timedeltas, feel free to open a PR.
