### ISSUE TITLE
RuntimeError: Watching for source changes is not supported on win32

### ISSUE THREAD

**Issue by zfei** [Bogdanp/dramatiq#525]
Trying out the hello world example on windows. With the `--watch` flag on, got `RuntimeError: Watching for source changes is not supported on win32.`

I suppose `watchdog` supports windows? Not sure what's wrong here.

`pip list`:

```
Package           Version
----------------- -------
cffi              1.15.1
dramatiq          1.13.0
gevent            22.10.2
greenlet          2.0.1
pika              1.3.1
pip               22.3.1
prometheus-client 0.15.0
pycparser         2.21
setuptools        65.6.3
watchdog          2.2.1
watchdog-gevent   0.1.1
wheel             0.38.4
zope.event        4.6
zope.interface    5.5.2
```

**Comment by Kokoserver** [comment]
i got the same error

**Comment by Bogdanp** [comment]
Watchdog is able to detect source changes on Windows, but the SIGHUP signal is not available on Windows, and reloading is based on sending that signal to the main process.

**Comment by scott-8** [comment]
@Bogdanp Uvicorn handles this by sending a different signal for for Windows ([see here](https://github.com/encode/uvicorn/blob/master/uvicorn/supervisors/basereload.py#L91)). Is this something you could see working? If so, I could submit a PR.

**Comment by Bogdanp** [comment]
@scott-8 sure! If there's a different signal that we can use, that'd be great. As long as it doesn't break interruption (the linked `CTRL_C_EVENT` seems a little suspicious because it sounds like a `SIGINT`, but I don't know enough about Windows signals to say for sure, maybe it's just misnamed?

**Comment by scott-8** [comment]
I played around with it a little bit, it looks to me like like killing a process with `CTRL_C_EVENT ` is just a Windows-specific way of sending a `SIGINT`. I also tried to use `CTRL_BREAK_EVENT` to cause a reload, which triggers a `SIGBREAK`. It works, but it's pretty buggy. I think in order to make this work well we'd need to change how subprocesses are handled.
