### ISSUE TITLE
[Question] Actors comunication

### ISSUE THREAD

**Issue by Jonatha-Varjao** [Bogdanp/dramatiq#534]
I have two repositories, one for each actor, is there a way to communicate this actors?

I'm using 
```python
dramatiq.actor(
            fn=callable,
            actor_name=ENV_VARS.actor_name,
            queue_name=ENV_VARS.actor_queue,
            broker=BROKER,
).send(message.dict())
```

But when I run the actors, some of the messages is processed by its sender instead of passing the job to the other actor

If I run the -Q flag this behavior doesn't happen, but will be a burden if the number of queues increases for each actor

I can use the [enqueueing-messages-from-other-languages ](https://dramatiq.io/advanced.html#enqueueing-messages-from-other-languages) aswell, but in this case how can I get the result if I needed?

**Comment by Bogdanp** [comment]
Please use the mailing list for questions.
