### ISSUE TITLE
How should I colorize my log output

### ISSUE THREAD

**Issue by dream2333** [Bogdanp/dramatiq#539]
I use loguru to output colored logs, but it doesn't work, the output logs are not colored. But when I put loguru in a separate py file, the coloring works, I want to know why? How can I get the output of dramatiq to be colored correctly

**Comment by jenstroeger** [comment]
Sounds related to [How to initialize logging for Actors across multiple processes](https://groups.io/g/dramatiq-users/topic/80938044).
