### ISSUE TITLE
task routing problem

### ISSUE THREAD

**Issue by timchou** [Bogdanp/dramatiq#54]
Hi

I have 

server A,which start dramatiq like this:
dramatiq --path . --processes 4 --threads 4 tasks

server B,start like this:
dramatiq --path . --processes 4 --threads 4 tasks --queues t1

and in my tasks.py,there is a function like this:
@dramatiq.actor(max_retries=0, queue_name="t1")
def func():
    print(122)

now, I run:
func.send()

and this job is sent to server A.

but I wish it sends to server B.

Is there anything wrong with my work?

Thanks:)

**Comment by Bogdanp** [comment]
Yup, that's exactly it. By default, Dramatiq consumes all declared queues so if you want to split queues between workers then you have to specify exactly which queues each worker group should consume! Glad you worked it out.

**Comment by Bogdanp** [comment]
> but server A will never receive the jobs, because the queue 'default' is never declared.

`default` is the queue actors use when you don't explicitly specify a queue. Maybe the example [here](https://dramatiq.io/cookbook.html#binding-worker-groups-to-queues) will help.
