### ISSUE TITLE
Need to limit the number of TCP connections when invoking actor.send

### ISSUE THREAD

**Issue by manjusfi** [Bogdanp/dramatiq#540]
# Issues

GitHub issues are for bugs.  If you have questions, please ask them on the [mailing list](https://groups.io/g/dramatiq-users/topics).

## Checklist

* [x] Does your title concisely summarize the problem?
* [x] Did you include a minimal, reproducible example?
* [x] What OS are you using?
* [x] What version of Dramatiq are you using?
* [x] What did you do?
* [x] What did you expect would happen?
* [x] What happened?

## What OS are you using?
macOS 12.5 (Monterey)

## What version of Dramatiq are you using?
1.13.0

## What did you do?
Trying to send a million messages by starting multiple threads
```
default_broker = RabbitmqBroker(host="127.0.0.1", port=5672, heartbeat=600)
dramatiq.set_broker(default_broker)

@dramatiq.actor(queue_name=queue_name)
def hello_world_webhook(input, input2=None):
	print("hello world")

results = {}
RANGE = 1000000
num_workers = 300
# if max_workers is 300 then we end up with "too many open files" error
with ThreadPoolExecutor(thread_name_prefix="SynapseThread", max_workers=num_workers) as executor:
	for i in range(RANGE):
		results[i] = executor.submit(hello_world_webhook.send, i, RANGE+1)

for i, val in results.items():
	try:
		# Invoking future.result() so that it can throw any exception that was raised inside the thread
		val.result()
	except Exception as e:
		print(f"Caught exception from future... {i}: {e}")
```

## What did you expect would happen?
Successfully send million messages

## What happened?
"too many open files" error

**Comment by Bogdanp** [comment]
Dramatiq will open one connection per thread, so either reduce the size of your pool or increase the max number of open file descriptors.

**Comment by manjusfi** [comment]
@Bogdanp - https://github.com/Bogdanp/dramatiq/pull/542 - can you please consider this PR as this would help everyone - with this change, Dramatiq would no longer create one connection per thread trying to send a message via Actor
