### ISSUE TITLE
The error while launching the worker with a callable setup.

### ISSUE THREAD

**Issue by 4l1fe** [Bogdanp/dramatiq#543]
## Version
`dramatiq 1.14.2`

## I did
Ran the worker in the standard way

`dramatiq --processes 1 --threads 1 tasks:setup_broker`

## Expectation
Get thw worker running.

## Happened
Got the error

```
ValueError: The following actor options are undefined: store_results. Did you forget to add a middleware to your Broker?
```

## Source code

_tasks.py_
```python

def setup_broker():
    result_backend = RedisBackend()
    redis_broker = RedisBroker()
    redis_broker.add_middleware(Results(backend=result_backend))

    dramatiq.set_broker(redis_broker)

@dramatiq.actor(store_results=True)
def extract_image_text(file):
    print('run')
```

**Comment by Bogdanp** [comment]
You'll have to split up your setup module and your tasks module to get this to work. Dramatiq has to load `tasks.py` before it can call `setup_broker`, and since the actor is defined in the same module, its definition also runs before `setup_broker` is called.
