### ISSUE TITLE
Results are automatically deleted after 10 minutes

### ISSUE THREAD

**Issue by Eldellano** [Bogdanp/dramatiq#548]
# Issues

GitHub issues are for bugs.  If you have questions, please ask them on the [mailing list](https://groups.io/g/dramatiq-users/topics).

## Checklist

* [ ] Does your title concisely summarize the problem?
* [ ] Did you include a minimal, reproducible example?
* [ ] What OS are you using?
* [ ] What version of Dramatiq are you using?
* [ ] What did you do?
* [ ] What did you expect would happen?
* [ ] What happened?

## What OS are you using?

Windows 11

## What version of Dramatiq are you using?

1.14.2

## What happened?

Below is an example of how I use the dramatiq. The code works, and after execution you can get the result, but if the result is not taken within 10 minutes, then it seems to be deleted and is no longer available with an error - ResultMissing. Tell me please, what am I doing wrong?

broker = RedisBroker(host='127.0.0.1')
dramatiq.set_broker(broker)
backend = RedisBackend(host='127.0.0.1')
broker.add_middleware(Results(backend=backend))

@dramatiq.actor(queue_name="test", store_results=True, max_age=3600000)
def add_task(url):
    print('task')
    time.sleep(10)
    print('task complete')
    return url

#get result with fastapi
@app.get('/get_result/')
async def get_result(id: str, request: Request):
    message: Message = add_task.message().copy(message_id=id)
    result = message.get_result(backend=backend)
    return {"result": "pending"}

**Comment by Bogdanp** [comment]
You'll want to set the `result_ttl` argument to whatever duration you want: https://dramatiq.io/reference.html#dramatiq.results.Results
