### ISSUE TITLE
Task routing send message with queue name.

### ISSUE THREAD

**Issue by Timaqf** [Bogdanp/dramatiq#55]
at https://github.com/Bogdanp/dramatiq/issues/35#issue-291440219 we discussed I can build message with Message object. so I can target the queue name.

the `queue_name` is a option for message, so why it's not in `Actor.send_with_options` ?

**Comment by Bogdanp** [comment]
Because that's an implementation detail and actors are only supposed to be bound to a single queue, like I said in my last comment on #35. If you want to route messages across different queues to the same function, declare separate actors.

**Comment by stefanzweig** [comment]
> 
> 
> Because that's an implementation detail and actors are only supposed to be bound to a single queue, like I said in my last comment on #35. If you want to route messages across different queues to the same function, declare separate actors.

Hi @Bogdanp , How to declare an actor at runtime? Thank you very much.
