### ISSUE TITLE
Feature: add a TailMessage middleware

### ISSUE THREAD

**Issue by jenstroeger** [Bogdanp/dramatiq#568]
This middleware is motivated by the following three observations:

- The Dramatiq [pipeline](https://dramatiq.io/reference.html#dramatiq.pipeline) requires existing Message objects; however, there are cases where a Message object can’t be created _before_ the pipeline runs.
- An Actor needs to create one or more messages during its execution, and send those messages _only_ on success, and ideally _after_ the Actor’s message was ack’ed and other committing decorators/middlewares have exited.
- Sometimes, an Actor needs to re-run indefinitely, see also [this discussion](https://groups.io/g/dramatiq-users/topic/dramatiq_infinite/100582310).[^1]

I’d like to propose a `TailMessage` middleware (similar to the [`CurrentMessage`](https://dramatiq.io/reference.html#dramatiq.middleware.CurrentMessage) middleware) like so:
```python
class TailMessage(dramatiq.Middleware):

    STATE = threading.local()

    @classmethod
    def enqueue(cls, message, delay = None):
        tail_message_list = getattr(cls.STATE, "tail_message_list")  # Check: can this fail in a valid setup?
        tail_message_list.append((message, delay))

    def before_process_message(self, broker, message):
        setattr(self.STATE, "tail_message_list", [])

    def after_ack(self, broker, message):
        tail_message_list = getattr(self.STATE, "tail_message_list")  # Check: This shouldn't fail.
        for msg, delay in tail_message_list:
            broker.enqueue(msg, delay=delay)
```
~(Perhaps improve the middleware to fit more closely with the [message_with_options()](https://dramatiq.io/reference.html#dramatiq.Actor.message_with_options) approach.)~ The middleware follows closely the existing [Broker.enqueue()](https://dramatiq.io/reference.html#dramatiq.Broker.enqueue) interface, so it should be simple enough to understand.

The idea is to give an Actor a way to buffer messages until the Actor’s message has been ack’ed, and only then send all buffered messages to the queue.

@Bogdanp — what do you think? Happy to provide a feature PR if this looks like a useful, general middleware for Dramatiq.

[^1]: Alternatively, one might be able to refactor [the `pipeline` class](https://github.com/Bogdanp/dramatiq/blob/76578a6ea5017f5a0680279692eee357d7b7f229/dramatiq/composition.py#L31) such that it’s able to handle true generators and then pass [itertools.cycle()](https://docs.python.org/3/library/itertools.html#itertools.cycle) to produce the same message infinitely.

**Comment by Bogdanp** [comment]
This seems niche enough that I'd rather keep it out of the core package.
