### ISSUE TITLE
Missing OpenTelemetry instrumentation

### ISSUE THREAD

**Issue by staticdev** [Bogdanp/dramatiq#571]
# Feature request

**Is your feature request related to a problem?**
When using [dramatiq](https://github.com/Bogdanp/dramatiq), there is no easy way to instrument it with logs, metrics and traces using OpenTelemetry.

**Describe the solution you'd like**
Add instrumentation similar to it's fork https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-remoulade

Upstream issue https://github.com/open-telemetry/opentelemetry-python-contrib/issues/1916

**Comment by octavifs** [comment]
Would you be open to contributions for this PR?

I'm planning on building a similar module to *opentelemetry-instrumentation-remoulade* for a work related project. Possibly also with Opentelemetry metrics support (similar to what you have with the Prometheus middleware).

If there's quorum for it, I think I can prepare a PR to be merged upstream, and some docs for the project.

Cheers!

**Comment by Bogdanp** [comment]
> Would you be open to contributions for this PR?

Yup. A PR would be welcome.

**Comment by Bogdanp** [comment]
I think I'd prefer having this in a separate package after all. If anyone makes one, ping me and I'll add a link!

**Comment by octavifs** [comment]
Hi Bogdan,
I'll reach the opentelemetry guys if I have some time this week.
I've got a middleware implemented, for opentelemetry support, with both traces and metrics integrated. Supports retries, etc. as well.

This is a sample from dev, with the custom keys added on each actor send/process action, showcasing retries
![opentelemetry-dramatiq-middleware-blanked](https://github.com/Bogdanp/dramatiq/assets/3926455/79bc155a-fbd6-413f-8055-a66f5ca13343)

As you said, no need to add this to core, a middleware is more than enough. Just need to test out a bit more the metrics implementation and the packaging, so it will only be a pip install away.

I'll post back when I have some updates. Cheers!

**Comment by manviii27** [comment]
Hey @octavifs,
I needed a help with exposing the dramatiq metrics to my endpoint. Can I get the source code or any reference on how to do it? The documentation wasn't much of a help to me

**Comment by octavifs** [comment]
Hi @manviii27,
If you plan to extract metrics with prometheus, you would need to enable the Prometheus middleware on your broker

```
from dramatiq.middleware.prometheus import Prometheus

redis_broker = RedisBroker(middleware=[Prometheus()])
```

Then the worker process will start to listen on port 9191 by default. You can curl to test it:

```
$ curl http://localhost:9191        
# HELP dramatiq_messages_inprogress The number of messages in progress.
# TYPE dramatiq_messages_inprogress gauge
dramatiq_messages_inprogress{actor_name="dramatiq_test_add",queue_name="default"} 0.0
# HELP dramatiq_message_duration_milliseconds The time spent processing messages.
# TYPE dramatiq_message_duration_milliseconds histogram
dramatiq_message_duration_milliseconds_sum{actor_name="dramatiq_test_add",queue_name="default"} 3.0
dramatiq_message_duration_milliseconds_bucket{actor_name="dramatiq_test_add",le="5.0",queue_name="default"} 1.0
dramatiq_message_duration_milliseconds_bucket{actor_name="dramatiq_test_add",le="10.0",queue_name="default"} 1.0
dramatiq_message_duration_milliseconds_bucket{actor_name="dramatiq_test_add",le="25.0",queue_name="default"} 1.0
dramatiq_message_duration_milliseconds_bucket{actor_name="dramatiq_test_add",le="50.0",queue_name="default"} 1.0
dramatiq_message_duration_milliseconds_bucket{actor_name="dramatiq_test_add",le="75.0",queue_name="default"} 1.0
dramatiq_message_duration_milliseconds_bucket{actor_name="dramatiq_test_add",le="100.0",queue_name="default"} 1.0
dramatiq_message_duration_milliseconds_bucket{actor_name="dramatiq_test_add",le="250.0",queue_name="default"} 1.0
dramatiq_message_duration_milliseconds_bucket{actor_name="dramatiq_test_add",le="500.0",queue_name="default"} 1.0
dramatiq_message_duration_milliseconds_bucket{actor_name="dramatiq_test_add",le="750.0",queue_name="default"} 1.0
dramatiq_message_duration_milliseconds_bucket{actor_name="dramatiq_test_add",le="1000.0",queue_name="default"} 1.0
dramatiq_message_duration_milliseconds_bucket{actor_name="dramatiq_test_add",le="2500.0",queue_name="default"} 1.0
dramatiq_message_duration_milliseconds_bucket{actor_name="dramatiq_test_add",le="5000.0",queue_name="default"} 1.0
dramatiq_message_duration_milliseconds_bucket{actor_name="dramatiq_test_add",le="7500.0",queue_name="default"} 1.0
dramatiq_message_duration_milliseconds_bucket{actor_name="dramatiq_test_add",le="10000.0",queue_name="default"} 1.0
dramatiq_message_duration_milliseconds_bucket{actor_name="dramatiq_test_add",le="30000.0",queue_name="default"} 1.0
dramatiq_message_duration_milliseconds_bucket{actor_name="dramatiq_test_add",le="60000.0",queue_name="default"} 1.0
dramatiq_message_duration_milliseconds_bucket{actor_name="dramatiq_test_add",le="600000.0",queue_name="default"} 1.0
dramatiq_message_duration_milliseconds_bucket{actor_name="dramatiq_test_add",le="900000.0",queue_name="default"} 1.0
dramatiq_message_duration_milliseconds_bucket{actor_name="dramatiq_test_add",le="+Inf",queue_name="default"} 1.0
dramatiq_message_duration_milliseconds_count{actor_name="dramatiq_test_add",queue_name="default"} 1.0
# HELP dramatiq_messages_total The total number of messages processed.
# TYPE dramatiq_messages_total counter
dramatiq_messages_total{actor_name="dramatiq_test_add",queue_name="default"} 1.0
```


Alternatively, if you are using opentelemetry for metrics, you can use my fork of [opentelemetry-python-contrib](https://github.com/octavifs/opentelemetry-python-contrib) which adds Opentelemetry support for tracing and metrics

You can install it with poetry

```
poetry add git+https://github.com/octavifs/opentelemetry-python-contrib.git#subdirectory=instrumentation/opentelemetry-instrumentation-dramatiq
```

Or pip

```
pip install -e 'git+https://github.com/octavifs/opentelemetry-python-contrib.git#egg=opentelemetry-instrumentation-dramatiq&subdirectory=instrumentation/opentelemetry-instrumentation-dramatiq'
```

Check its [README](https://github.com/octavifs/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-dramatiq) if you're interested in using it, as it has some examples of how it should be initialized with the broker.

**Comment by manviii27** [comment]
@octavifs Thank you so much for this.

Just one more thing, I added the prometheus middleware but the metrics are not getting exposed to my endpoint. Any tips on that?

**Comment by robotadam** [comment]
@octavifs I saw this discussion and your fork while looking at our own otel instrumentation. Do you have plans to submit this for inclusion `opentelemetry-python-contrib`, or are you going to leave it as is for now? I'm not sure when I might be able to squeeze time out, but if I can help with testing let me know.
