### ISSUE TITLE
Inconsistent `/tmp` path setup for Prometheus middleware.

### ISSUE THREAD

**Issue by jenstroeger** [Bogdanp/dramatiq#576]
Looking at these two module variables:

https://github.com/Bogdanp/dramatiq/blob/33b49ccf32aa3dd590d92ba8bc05be4e2ddfc887/dramatiq/middleware/prometheus.py#L26-L31

I think that the hard-wired `/tmp/` path of the first should follow the system’s temp path used in the second, i.e.
```python
LOCK_PATH = os.getenv("dramatiq_prom_lock", "%s/dramatiq-prometheus.lock" % tempfile.gettempdir()) 
```
If that is indeed the case, I’m happy to provide a PR.

**Comment by Bogdanp** [comment]
Seems fine to change the former so a PR would be welcome.
