### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by davidt99** [Bogdanp/dramatiq#581]
Any plan for a new release soon? What I'm looking for is the support of [redis-py 5](https://github.com/Bogdanp/dramatiq/pull/567).
I know dramatiq is compatible with it but the version conflict prevents me from bumping it.
Let me know if I can help.

**Comment by davidt99** [comment]
@Bogdanp Can you help with that? I'm willing to step in as a maintainer if needed.

**Comment by Bogdanp** [comment]
Just released. Sorry for the delay, but I'm pretty busy. I don't think I'm ready to hand things off to new maintainers at the moment, but maybe sometime next year.
