### ISSUE TITLE
why not aio-pika?

### ISSUE THREAD

**Issue by ArtemIsmagilov** [Bogdanp/dramatiq#585]
Your code use sync pika. Does it make sense to use aio-pika https://github.com/mosquito/aio-pika ?

**Comment by spumer** [comment]
Why it should be based on aio-pika?

**Comment by ArtemIsmagilov** [comment]
The asynchronous implementation of all code should completely eliminate the blocking of the async event loop.

**Comment by Bogdanp** [comment]
Let's use the mailing list for questions and discussion.
