### ISSUE TITLE
CLI: Allow watching custom include / exclude patterns  [feature-request]

### ISSUE THREAD

**Issue by nhairs** [Bogdanp/dramatiq#594]
First of all, great project :)

Currently the CLI reloader only allows specifying the base path path to watch for changes (`--watch path/to/watch`). However the watcher is configured so that it only listens to changes on `*.py` files ([source code](https://github.com/Bogdanp/dramatiq/blob/master/dramatiq/watcher.py#L16)).

I would like to be able to use the reloader with changes to other files such as configuration files.

It might look like the following:
```python
        # cli.py
        parser.add_argument(
            "-i",
            "--watch-include",
            action="append",
            dest="include_patterns",
            help="Additional patterns to watch for changes",
        )

        parser.add_argument(
            "-x",
            "--watch-exclude",
            action="append",
            dest="exclude_patterns",
            help="Patterns to ignore for changes",
        )
```

Which would then be used like:
```bash
dramatiq [...] --watch path/to/watch -i *.yml -i templates/*.html -x templates/*.png
```

Aside: in documentation / help strings it might be worth noting that prior to Python 3.13 these patterns only support multiple name (`**`) globbing at the start of the pattern ([ref](https://github.com/python/cpython/issues/73435#issuecomment-1569046011))

**Comment by Bogdanp** [comment]
Sounds like a good idea to me. Are you willing to send a PR?

**Comment by nhairs** [comment]
Honestly not a big fan of handing over copyright of my code to a company which is releasing the code under a restrictive licence like LGPL.

Even for a small amount of code that would be required for this sort of PR, this is code I've already written in my own projects - which by handing over copyright and then receiving the code under LGPL means I can no longer use the code I've written (the code is not some internal patch for Dramatiq but a different project).

I'd be less concerned if it was released under a permissive licence like MIT, Apache 2.0, BSD 3 Clause, but ideally I'd prefer to retain ownership of any contributions and instead ensure that the contribution is made under a permissive licence.
