### ISSUE TITLE
Using gevent.monkey.patch_all() will cause socket warnings and breaks --watch

### ISSUE THREAD

**Issue by TomFreudenberg** [Bogdanp/dramatiq#602]
# Issues

I wanted to handle the warning message when having your watchdog.gevent package "ImportWarning: gevent observers require the 'threading' module to be monkeypatched by gevent."

So I added the monkey patch in front of startup:

```python
import gevent.monkey
gevent.monkey.patch_all()
```

After then the warning message is not shown anymore.

But using the `actors.send` message, it will show that warnings:

```
sys:1: ResourceWarning: unclosed <socket object, fd=8, family=2, type=1, proto=6>
sys:1: ResourceWarning: unclosed <socket object, fd=7, family=2, type=1, proto=0>
sys:1: ResourceWarning: unclosed <socket object, fd=6, family=2, type=1, proto=0>
```

In addition, when starting the dramatiq service by using `--watch` won't start the service anymore but hang. Also you can't stop the servive by `ctrl-c` anymore but have to kill by process id.

**Comment by Bogdanp** [comment]
I assume you were using the `dramatiq` command to run these workers and that's why you ran into issues. You should use `dramatiq-gevent` instead when you want the gevent patches to be applied at startup. If that still doesn't work, feel free to reopen this issue.
