### ISSUE TITLE
Modify default middleware options for a newly created broker instance

### ISSUE THREAD

**Issue by alobstedt** [Bogdanp/dramatiq#603]
## What OS are you using?
Ubuntu 22.04

## What version of Dramatiq are you using?
1.15.0

## What did you do?
I've created a new broker instance and tried adding the Retries middleware again. It just gets appended into the `redis_broker.middleware` list.

```
from dramatiq.brokers.redis import RedisBroker
from dramatiq.middleware.retries import Retries

def foo(exception):
    return not isinstance(exception, MySpecialException)

redis_broker = RedisBroker(host=config.get('dramatiq', 'broker_host', fallback='127.0.0.1'),
                           port=config.getint('dramatiq', 'broker_port', fallback=6379),
                           db=config.getint('dramatiq', 'broker_db', fallback=0),
                           username=config.get('dramatiq', 'broker_username'),
                           password=config.get('dramatiq', 'broker_password'))
redis_broker.add_middleware(Retries(retry_when=foo))
```

## What did you expect would happen?
I expected the Retries Middleware of `redis_broker` to be updated and to be able to apply the `retry_when` function.

## What happened?
the 2nd Retries Middleware was appended to `redis_broker.middleware` 

My goal was to achieve that I don't need to define the `throws` parameter for every actor that I create. As we have a distinct Exception we throw whenever we want stop a given task, me and my team would need to remember to always include the `throws` for every single actor.

I thought about just using a "global" `retry_when` that checks for that special Exception, but now I have 2 Retries Middlewares which idk if it even works properly or it's just an unideal solution.

What is currently the intended way for changing the "default" middlewares that get added to the broker on initialization? I think having to provide the full list of all Middlewares during broker init shouldn't be the only proper way to do it, should it? 

Open for other ideas how we can tackle this issue.

**Comment by Bogdanp** [comment]
The recommended approach here is to pass the list of middleware you want to use directly when you create the broker. You can find the list of default middleware in `dramatiq/middleware/__init__.py`.
