### ISSUE TITLE
Too many threads are created, ignore -t parametor

### ISSUE THREAD

**Issue by Claud** [Bogdanp/dramatiq#613]
Thank you for a great project!

## What OS are you using?

Ubuntu 22.04.3 LTS (GNU/Linux 5.15.0-94-generic x86_64)

## What version of Dramatiq are you using?

dramatiq 1.16.0 and Redis

## What did you do?

worker.py

```
import dramatiq
from dramatiq.brokers.redis import RedisBroker
from dramatiq.middleware.asyncio import AsyncIO

broker = RedisBroker(host="localhost")
broker.add_middleware(AsyncIO())
dramatiq.set_broker(broker)

@dramatiq.actor(
    queue_name="default",
    max_retries=40,
    min_backoff=60000,
    max_backoff=300000,
    time_limit=180000,
)
async def worker(id_):
    await handler(id_)

```
run 
```
dramatiq worker -P src/strategies_queue -p 6 --threads 3 -Q default
```

## What did you expect would happen?

I expect 6 processes of 3 threads each

## What happened?

It seems that the given parameters do not work, too many threads are created?

![2024-02-22 17_52_28-master@Trading-Assistance-ubuntu-16gb_ ~](https://github.com/Bogdanp/dramatiq/assets/400004/be216163-ad30-4738-b9d2-9a73c92d1556)

**Comment by Bogdanp** [comment]
This is working as expected. The `-t` argument controls the number of worker threads per process that are spawned, but there may be other threads (eg. consumer threads, prometheus server, etc.) spawned per process as well.
