### ISSUE TITLE
Recognize actor with module name instead of only func name

### ISSUE THREAD

**Issue by z0z0r4** [Bogdanp/dramatiq#640]
# Issues

GitHub issues are for bugs.  If you have questions, please ask them on the [mailing list](https://groups.io/g/dramatiq-users/topics).

## Checklist

* [x] Does your title concisely summarize the problem?
* [x] Did you include a minimal, reproducible example?
* [x] What OS are you using?
* [x] What version of Dramatiq are you using?
* [x] What did you do?
* [x] What did you expect would happen?
* [x] What happened?

Creating two func decorated with `@actor` without setting its `actor_name` in different module, import the first registered func and send message to run, and you may find that dramatiq run the second but not the first func...

It seems dramatiq recognize func defaultly by its func name...

In many cases, the function names in different modules are set to the same. I think that it is an unreasonable design to use the function name as the only index.

https://github.com/Bogdanp/dramatiq/blob/4b6ad185d4656b4ea7109cd38ef3f40ad17e0566/dramatiq/actor.py#L258

Should we change the default `actor_name` to `actor_name = actor_name or f'{fn.__module__}.{fn.__name__}'`?

I am not familiar with the source code. Based on my initial understanding, it seems that actor_name is only used as the key of the destination function and can be set at will without duplication.

**Comment by spumer** [comment]
I think we need to raise error if try to register actor with same name and require change it.

And to auto resolve name conflict is best to use `__qualname__` https://devdocs.io/python~3.12/reference/datamodel#function.__qualname__

`__qualname__` include full path to func

**Comment by z0z0r4** [comment]
maybe I will have a PR recently

**Comment by shshe** [comment]
We've encountered this problem as well. We added a Dramatiq middleware to detect duplicate actor names:

```python
class EnforceUniqueActorNames(Middleware):
    def before_declare_actor(self, broker, actor):
        if actor.actor_name in broker.actors:
            logger.error(
                "Duplicate actor name detected: %s. Actor names must be unique. "
                "Set a unique name using the `actor_name` kwarg or by renaming the "
                "function decorated by @dramatiq.actor.",
                actor.actor_name,
            )
            raise DuplicateActorError
```

Wealso  use a replacement for the standard `@actor` decorator that registers the actors with the module name prefix (aligning it with the same behavior as Celery):


```python
def actor_v2(
    fn: Optional[Callable] = None,
    *,
    actor_name: Optional[str] = None,
    **options,
) -> Union[Actor, Callable]:

    def decorator(fn):
        nonlocal actor_name
        if actor_name is None:
            actor_name = fn.__name__
        full_actor_name = f"{fn.__module__}.{actor_name}"
        return actor(
            fn,
            actor_name=full_actor_name,
            **options,
        )

    if fn is None:
        return decorator
    return decorator(fn)
```
