### ISSUE TITLE
Running programmatically for debuging

### ISSUE THREAD

**Issue by z0z0r4** [Bogdanp/dramatiq#642]
# Issues

GitHub issues are for bugs.  If you have questions, please ask them on the [mailing list](https://groups.io/g/dramatiq-users/topics).

## Checklist

* [ ] Does your title concisely summarize the problem?
* [ ] Did you include a minimal, reproducible example?
* [ ] What OS are you using?
* [ ] What version of Dramatiq are you using?
* [ ] What did you do?
* [ ] What did you expect would happen?
* [ ] What happened?

How can I run dramatiq in code directly instead of CLI?

I can't find any information about it in docs.

**Comment by Bogdanp** [comment]
See the tests.
