### ISSUE TITLE
Example test fixtures / broker.flush_all is not sufficient after test failure

### ISSUE THREAD

**Issue by rpkilby** [Bogdanp/dramatiq#65]
The suggested broker/worker fixtures (used by …:_dramatiq) look like:

```python
from yourapp import broker

@pytest.fixture()
def stub_broker():
  broker.flush_all()
  return broker

@pytest.fixture()
def stub_worker():
  worker = Worker(broker, worker_timeout=100)
  worker.start()
  yield worker
  worker.stop()
```

A test failure *before* the broker/worker can be joined may cause another test to hang indefinitely. eg, 

```python
@dramatiq.actor()
def example():
     ...

def test_a(broker, worker):
    example.send()
    
    raises_unintended_exception()

    # never reached
    broker.join(example.queue_name)
    worker.join()

def test_b(broker, worker):
    example.send()
   
    # hangs indefinitely
    broker.join(example.queue_name)
    worker.join()
```

While `test_a` fails and exits, the broker is in a bad state when it reaches `test_b` and will hang on `join`.

Note that this is not an issue with dramatiq's own `stub_broker` fixture, as a new broker is created and closed for each test. In contrast, `django_dramatiq`'s broker is globally created in the `apps` config, and can only issue a `flush_all()` between tests. Test case:

```python
def test_stub_broker_can_join_after_flush_after_not_joining(stub_broker, stub_worker):
    # Given that I have an actor
    @dramatiq.actor
    def do_work():
        pass

    # "test a"
    stub_broker.flush_all()
    do_work.send()
    # test failure / no joining

    # "test b"
    stub_broker.flush_all()
    do_work.send()
    
    stub_broker.join(do_work.queue_name)
    stub_worker.join()
```

**Comment by Bogdanp** [comment]
I wonder if there's something else going on here, because I don't see how this could happen and I can't reproduce it. I installed the latest versions of dramatiq and pytest in a virtualenv and tried to reproduce this using [this file](https://gist.github.com/Bogdanp/8f882d0c56f17dcbbfccbf071d817972) and couldn't.

The output I got was, predictably:

```
test_bug.py::test_a FAILED
test_bug.py::test_b PASSED

================================================================================================================== FAILURES ==================================================================================================================
___________________________________________________________________________________________________________________ test_a ___________________________________________________________________________________________________________________

broker = <dramatiq.brokers.stub.StubBroker object at 0x10f393b00>, worker = <dramatiq.worker.Worker object at 0x10f68f6d8>

    def test_a(broker, worker):
        example.send()
    
>       raise Exception("test")
E       Exception: test

test_bug.py:35: Exception
===================================================================================================== 1 failed, 1 passed in 0.87 seconds =====================================================================================================
```

**Comment by rpkilby** [comment]
`test_a`/`test_b` *should* pass in dramatiq, because the test_broker is closed and recreated for each test. Those tests wouldn't pass in django_dramatiq, since the broker is a single, global instance. The second code block somewhat simulates what's happening in django_dramatiq.

**Comment by rpkilby** [comment]
> Would you mind creating a small reproducible example that I can take a look at?

Will do.

**Comment by Bogdanp** [comment]
> test_a/test_b should pass in dramatiq, because the test_broker is closed and recreated for each test. Those tests wouldn't pass in django_dramatiq, since the broker is a single, global instance. The second code block somewhat simulates what's happening in django_dramatiq.

The tests in [my example](https://gist.github.com/Bogdanp/8f882d0c56f17dcbbfccbf071d817972) (updated just now for clarity) share a global stub broker for the lifetime of the test suite.

**Comment by rpkilby** [comment]
Ah, gotcha - missed the test file.

**Comment by rpkilby** [comment]
Hm. I'm unable to recreate the original error.

That said, this test still fails:

```python
def test_stub_broker_can_join_after_flush_after_not_joining(stub_broker, stub_worker):
    # Given that I have an actor
    @dramatiq.actor
    def do_work():
        pass

    # "test a"
    stub_broker.flush_all()
    do_work.send()
    # test failure / no joining

    # "test b"
    stub_broker.flush_all()
    do_work.send()
    
    stub_broker.join(do_work.queue_name)
    stub_worker.join()
```

Although adding in the worker recreation does pass

```python



def test_stub_broker_can_join_after_flush_after_not_joining(stub_broker):
    # Given that I have an actor
    @dramatiq.actor
    def do_work():
        pass

    # "test a"
    stub_broker.flush_all()
    worker = Worker(stub_broker, worker_timeout=100)
    worker.start()
    do_work.send()
    # test failure / no joining
    worker.stop()

    # "test b"
    stub_broker.flush_all()
    worker = Worker(stub_broker, worker_timeout=100)
    worker.start()
    do_work.send()

    stub_broker.join(do_work.queue_name)
    worker.join()

    worker.stop()
```

My guess is that I had some unrelated error in my test code that was preventing the worker from instantiating.

**Comment by rpkilby** [comment]
btw - using dramatiq has been an absolute pleasure so far.

And thanks for being so responsive.

**Comment by Bogdanp** [comment]
My pleasure!
