### ISSUE TITLE
Accepting invalid options. Is this a bug?

### ISSUE THREAD

**Issue by ArtemIsmagilov** [Bogdanp/dramatiq#655]
# Issues

GitHub issues are for bugs.  If you have questions, please ask them on the [mailing list](https://groups.io/g/dramatiq-users/topics).

## Checklist

* [x] Does your title concisely summarize the problem?
* [x] Did you include a minimal, reproducible example?
* [x] What OS are you using?
* [x] What version of Dramatiq are you using?
* [x] What did you do?
* [x] What did you expect would happen?
* [x] What happened?

## What OS are you using?
Ubuntu 24.0.4

## What version of Dramatiq are you using?
1.17.0

## What did you do?
I'm adding an invalid option to make sure that dramatiq is not a leaky abstraction

## What did you expect would happen?
I expect to receive an error indicating that the parameter passed is not provided. That is, there should be validation for only available parameters - delay, max_retries and so on

## What happened?
Dramatiq simply accepts any invalid option. However, it saves it in the options argument and prints it to the screen, which is much better than just getting it and losing it.
- https://github.com/celery/celery/issues/9305

I'm expecting something like
```python
print(asdasdasdsad=10)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'asdasdasdsad' is an invalid keyword argument for print()
```

Note.
This is a problem for me because I can make a typo and not know that I made it. It would be cool to fix this, future developers will be very grateful.

Example

```python
# main.py
import dramatiq


@dramatiq.actor
def hello(name):
    print(f'Hi, {name}!')
```

```python
>>> from main import hello
>>> hello.send_with_options(args=("Artem",), asjajaskjdakjkdjka=1)
Message(queue_name='default', actor_name='hello', args=('Artem',), kwargs={}, options={'asjajaskjdakjkdjka': 1, 'redis_message_id': '15fd3a09-a3e3-4bc9-9ebd-e701946f385b'}, message_id='df871b62-b74d-4b9d-b441-1ad77012d839', message_timestamp=1728320404023)
```

I'm not an expert in process managers. Why are options that affect functionality mixed with options that do not?

I'm not sure that this should be the case. How many mistakes can you make and not even know about it?

**Comment by Bogdanp** [comment]
I would not consider this a bug. While I see the misspelling you mention as a potential downside, the upside is this API lets you store and retrieve arbitrary data on a message. At any rate, it's too late to change now since this would be a breaking change.
