### ISSUE TITLE
Add support for Valkey key/value datastore 

### ISSUE THREAD

**Issue by dpgraham4401** [Bogdanp/dramatiq#661]
# Issues

Since Redis [changed it's licensing BSD to a dual clause source available](https://redis.io/blog/redis-adopts-dual-source-available-licensing/), some are worried about the future of Redis. Whether the worry is merited is another conversation, but dramatiq should be able to add support for the defacto redis fork, [valkey](https://valkey.io/).

I haven't tested whether dramtiq would have issues. We're using dramtiq 1.17. 

What steps need to be taken to add support for valkey? 

## Checklist

* [x] Does your title concisely summarize the problem?
* [x] Did you include a minimal, reproducible example? -NA
* [ ] What OS are you using? - NA
* [x] What version of Dramatiq are you using?
* [ ] What did you do? - nothing
* [ ] What did you expect would happen? - should act as a drop in repalcement
* [ ] What happened?

## What version of Dramatiq are you using?

1.17.0

**Comment by Bogdanp** [comment]
As long as they implement the same wire protocol and don't break backwards-compatibility, the Redis broker will work with Valkey.

**Comment by dpgraham4401** [comment]
hey @Bogdanp you're right, currently the Redis broker should work with Valkey, however, that may not always be the case. A PR that resolves this issue could: 
1. Add information on the use of the Redis Broker for Valkey to the docs
2. Preferably test against a valkey [services in CI](https://github.com/Bogdanp/dramatiq/blob/master/.github/workflows/push.yml)

**Comment by Bogdanp** [comment]
I think that if they do ever change things such that the Redis broker stops working with Valkey, then someone will have to write a Valkey-specific broker. Those who care enough about the licensing will probably be able to figure out what the Redis-compatible alternatives are, so I'm not in a rush to advertise them.
