### ISSUE TITLE
config file or config object?

### ISSUE THREAD

**Issue by Timaqf** [Bogdanp/dramatiq#67]
there's many configurable settings item in project, but there is not a friendly config way.
maybe we can use the flask's config way to setting 

LOG_LEVEL, 
BROKER_SETTING, 
BROKER_HOST, 
DEFAULT_NAMESPACE,
RENQUE_TIME,
RedisWatcher  interval
_RedisConsumer prefetch.

and etc.

like flask, settings can be imported from python file or python object or dict.

https://github.com/pallets/flask/blob/master/flask/config.py

**Comment by Bogdanp** [comment]
I was thinking about this last night and I like the way gunicorn does it, but I'll have to think about how something like this would fit into Dramatiq.

**Comment by ericgj** [comment]
Why not leave this to the application to decide?  Everyone has different opinions about how to do config and even what should go into config. What's the advantage of baking it in to the framework?

**Comment by kuba-lilz** [comment]
Configuration isn't limited to values to configure dramatiq itself - it is also necessary to configure code that dramatiq is running.

Say I have tasks that talk to 5 different services - mysql, aws s3, some third party apps, whatever - and each of these require connection strings or similar configuration to establish connections.

Passing connection strings as function/task arguments would be tedious and a possible security problem if broker stores data in plaintext.
Celery exposes `celery.current_app.conf` and flask exposes `flask.current_app.conf` - which are handy places for such data.

Sure each user can roll something himself, but an established method takes some mental load off developers' hands and prevents them from reinventing the wheel.
