### ISSUE TITLE
How to collect prometheus metrics if dramatiq workers run on kubernetes and are scaled ?

### ISSUE THREAD

**Issue by bloogrox** [Bogdanp/dramatiq#68]

**Comment by Bogdanp** [comment]
You'll want to use the endpoints role for [`kuberentes_sd_config`] and label your services appropriately. See [this file](https://github.com/prometheus/prometheus/blob/master/documentation/examples/prometheus-kubernetes.yml#L131-L142) for an example.

[`kubernetes_sd_config`]: https://prometheus.io/docs/prometheus/latest/configuration/configuration/#%3Ckubernetes_sd_config%3E
