### ISSUE TITLE
Feature request: disable time_limit

### ISSUE THREAD

**Issue by rpkilby** [Bogdanp/dramatiq#70]
Should there be a way of allowing time limits to be disabled? eg, passing `None` will bypass setting the deadline. We would simply disable the middleware, except that we use time limits on other tasks.

**Comment by Bogdanp** [comment]
```python
@dramatiq.actor(time_limit=float("inf"))
...
```

Should do the trick.

**Comment by rpkilby** [comment]
Thanks - I'll try that later.

**Comment by Bogdanp** [comment]
@Timaqf that seems redundant with the `middleware` parameter that `Broker`s take.

@rpkilby I'm closing this for now. LMK if you run into issues!

**Comment by rpkilby** [comment]
Hi @Bogdanp. I was reading into the broker code a bit, and this should conflict with the redis broker's `DEFAULT_REQUEUE_DEADLINE`, right? eg, if a task takes more than seven and a half days to complete, the broker will just assume something went wrong and requeue the message. At this point, won't the requeued message be picked up, and two worker threads will be processing the same message?

What is the requeueing behavior of the rabbitmq broker?

**Comment by Bogdanp** [comment]
That's right. You'd have to adjust the requeue deadline with the Redis broker depending on the max length of your tasks. It didn't even occur to me that your tasks could last 7 days or longer when you first opened the issue. :)

> What is the requeueing behavior of the rabbitmq broker?

RMQ moves messages into the "unacked" state when a worker pulls them and it only removes them if the worker (n)acks the message or when it detects the worker disconnected without (n)acking. This means that, as long as your connection with the broker is stable and heartbeats fire correctly -- skipped heartbeats is how it figures out when a client disconnects -- you should be able to reserve messages indefinitely.

**Comment by rpkilby** [comment]
Would is make sense for the redis broker to also use a heartbeat? 

> It didn't even occur to me that your tasks could last 7 days or longer when you first opened the issue. :)

Ideally it shouldn't. At this point in time, this one task can run in an open-ended fashion, potentially taking longer than seven days. Usually, the task should be bounded so that it takes a shorter period of tim, but we're still talking on the order of a day or two.

**Comment by Bogdanp** [comment]
I made it not-breaking after all :)
