### ISSUE TITLE
try to catch pika.exceptions.ConnectionClosed when broker ack and ncak

### ISSUE THREAD

**Issue by Timaqf** [Bogdanp/dramatiq#74]
https://github.com/Bogdanp/dramatiq/blob/450ad4a927ed7fba9927b9bd72244b7e952d574f/dramatiq/brokers/rabbitmq.py#L432

_RabbitmqConsumer only catchs pika.exceptions.ChannelClosed, should it catch  pika.exceptions.ConnectionClosed error too?

**Comment by Bogdanp** [comment]
In my testing, `ConnectionClosed` was never raised in that area regardless of what I did (suddenly kill RMQ, cause a partition, etc.). If you ran into an issue here, feel free to re-open the ticket and please post a stack trace and a description of what you were doing when it happened.
