### ISSUE TITLE
How to use authentication

### ISSUE THREAD

**Issue by jssuzanne** [Bogdanp/dramatiq#8]
Hi,

I don't found the authentication in your documentation, 
How to protect it whatever the broker (rabbitmq, redis, ...)? What parameter ? where ?

**Comment by Bogdanp** [comment]
Thanks! I've been meaning to add these to the docs but I kept forgetting:

https://dramatiq.io/reference.html#dramatiq.brokers.rabbitmq.RabbitmqBroker
https://dramatiq.io/reference.html#dramatiq.brokers.redis.RedisBroker

Let me know if you think I should add anything else.

**Comment by jssuzanne** [comment]
Great, thank you very much.

Maybe add a list with the parameters definition or a link to find them easily.
