### ISSUE TITLE
RabbitMQ rate_limiter backend

### ISSUE THREAD

**Issue by aer0s** [Bogdanp/dramatiq#82]
Why is there no AMQP rate limiter backend? I have been very excited to get away from Celery and I love concise approach that Dramatiq takes. Hit a bit of a roadblock however in that every worker picks up every scheduled task at the same time, i.e workers 1-4 all try to execute the same task at the same time.

https://github.com/Bogdanp/dramatiq/issues/32

The issue thread above looks promising with regard to adding some middleware to prevent concurrent execution and limiting the retry count down to zero. However, I've been using RabbitMQ and it works great as a broker, so can it not be used as the rate limiter backend as well?

**Comment by Bogdanp** [comment]
The reason why there's no rate limiter backend is simple: RabbitMQ is not a database and it doesn't support the various operations needed for a rate-limiter to be built on top of. That said, you can keep using the RMQ broker with a Redis or Memcached rate limiter backend!
