### ISSUE TITLE
Syntax error when i run pip install

### ISSUE THREAD

**Issue by kiorq** [Bogdanp/dramatiq#84]
# Issues

GitHub issues are for bugs.  If you have questions, please ask them on the [discussion board](https://discuss.dramatiq.io).

## Checklist

* [x] Does your title concisely summarize the problem? Yes
* [x] Did you include a minimal, reproducible example? Yes
* [x] What OS are you using? Mac OS
* [x] What version of Dramatiq are you using? Haven't install yet
* [x] What did you do? Try to install using pip
* [x] What did you expect would happen? Dramatiq to be installed
* [x] What happened? Got a syntax error instead

## What OS are you using?
macOS High Sierra -- Version 10.13.4

## What version of Dramatiq are you using?
Don't have it yet

## What did you do?

Run the command `pip install -U 'dramatiq[rabbitmq, watch]'`

## What did you expect would happen?

Have dramatiq installed.

## What happened?

Got this instead...

```
(e2e) kirkdouglas@MacBook-Pro-5 ~/Code/e2etests (redesign) $ pip install -U 'dramatiq[rabbitmq, watch]'
Collecting dramatiq
  Using cached https://files.pythonhosted.org/packages/0b/21/75cbe97997af1e8e61f88265f99a599decadce42777cb8468b6dca3d0e5f/dramatiq-0.15.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/rg/nx_fnb5d3zd2kx_5_bblt8xr0000gq/T/pip-build-C4z4SM/dramatiq/setup.py", line 29
        yield from parse_dependencies(line[len("-r "):])
                 ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/rg/nx_fnb5d3zd2kx_5_bblt8xr0000gq/T/pip-build-C4z4SM/dramatiq/
```

**Comment by kiorq** [comment]
Strange, [setup.py](https://github.com/Bogdanp/dramatiq/blame/f2d593bb32f45c9754fd80737a9733c7a6325a72/setup.py#L33) hasn't been touched in 11 months (at least the part that is giving me a syntax error)....

**Comment by kiorq** [comment]
Ah, it's because i'm using python2.7

**Comment by Bogdanp** [comment]
Yep, sorry about that. It used to be that older versions of Dramatiq didn't have `python_requires` in their `setup.py`, otherwise pip would've pointed out that you're running Python 2.
