### ISSUE TITLE
Please add check. module name should != reserved(existent) module (like `test`)

### ISSUE THREAD

**Issue by dmitry-vakhnenko** [Bogdanp/dramatiq#88]
@Bogdanp thx for lib! It's awesome!

My issue is a enchantment request. Just for `better newbie developer experience`.

My story (reproduce steps).
1) create file with name `test` (or any other `reserved` name)
2) follow guide
3) nothing works, 2 day stupid repeating guide from docs.

When i just rename file, everything magically works.

I know, it may be newbie case, but dramatiq say me nothing (also with `--verbose`).

Also, adding broker connection info with `--verbose` option may be helpful too.

**Comment by Bogdanp** [comment]
Thanks! This should be fixed in `v1.2.0`.
