### ISSUE TITLE
Actor's options are ignored

### ISSUE THREAD

**Issue by davidt99** [Bogdanp/dramatiq#91]
The documentations states that the actor's arbitrary options are passed to the broker and middlewares but that doesn't seem to happen when declaring a queue inside a broker for example.

**Comment by Bogdanp** [comment]
They are only "passed" to those middleware hooks that either take an Actor or a Message. Why do you ask? Is there something specific this is preventing you from doing?

**Comment by davidt99** [comment]
I'm implementing a rabbitmq broker that support rabbitmq's [priority queue](https://www.rabbitmq.com/priority.html). The queue needs `x-max-priority` set when creating the queue. Since the queue name is defined on the actor, I wanted to have this defined on the actor's options as well.

**Comment by Bogdanp** [comment]
It's not ideal (in fact, it's a little ugly), but you can probably achieve this by looking up the actor inside of your `declare_queue` method. I may consider changing the interface for 2.0 to make this sort of thing easier, but I'll leave it as is for now!
