### ISSUE TITLE
Track status of a task

### ISSUE THREAD

**Issue by MaxRichter** [Bogdanp/dramatiq#93]
Hi,

first of all, great library, easy to understand and fast.

I came across the issue, that I was looking for a status of a task. So far I did not see this feature in the documentation, but you linked a database solution in your [https://github.com/Bogdanp/flask_dramatiq_example](flask example ).

Is it also possible to track the task status in the broker and/or backend?

Further, is it possible to distinguish between an existing task in the backend and non-existing one?
I would expect some error for a task that does not exist and a status for an existing task.

Best,
Max

**Comment by dmitry-vakhnenko** [comment]
Hello! I love this library too!

For tracking statuses (success/error) you can follow this instruction:

> https://dramatiq.io/cookbook.html#error-reporting

More info about it you can find here:
> https://dramatiq.io/reference.html#middleware

So, in basic cases maybe you need:
> https://dramatiq.io/reference.html#results
> or
> https://dramatiq.io/cookbook.html#callbacks

-
> Further, is it possible to distinguish between an existing task in the backend and non-existing one?

hm, middleware?

**Comment by MaxRichter** [comment]
Hi @dmitry-vakhnenko,

thank you for the hints and tried some of them, especially the results but I am still not happy with my result.

Let me describe you how what I want to achieve:

1. I sent a Message via an Actor with `message = add.send(1, 2) ` - from there I get back an `message_id` from the broker
2. I want to store this `message_id` e.g. in a MySQL database **before** it is accessible with `message.get_result(backend=backend)` --> Here I do not know if any of the Middleware functions are of any help for this use case
3. If 1 and 2 are in place, I can distinguish between an existing message/task and a non-existing one, by querying the database.
4. Further I can update the status of the message/task in the database over the time of the process.

**Comment by Bogdanp** [comment]
@MaxRichter since this is essentially a question, would you mind moving the discussion over to the forum at https://discuss.dramatiq.io?

To answer your question, though, this is possible via middleware. You can check out the [`AdminMiddleware`](https://github.com/Bogdanp/django_dramatiq/blob/master/django_dramatiq/middleware.py#L11) in `django_dramatiq` for an example.
